build: Add a placeholder rgw role for csv generation
rook/rook pull request #10108
Opened 2022-04-19 20:47 UTC by travisn

**Description of your changes:**
The csv will not properly include the rook-ceph-rgw service account unless there is a role and binding that references the service account. No roles are needed yet for the rgw daemon, so this will add a placeholder only for the purposes of csv generation.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-04-19 21:35 UTC, BlaineEXE approved these changes

2022-04-20 07:31 UTC, leseb requested changes

2022-04-20 07:31 UTC, leseb commented on deploy/examples/common.yaml
> +# Allow the osd pods in this namespace to work with configmaps
Wrong copy/paste?

2022-04-20 17:51 UTC, merged

2022-04-22 06:38 UTC, parth-gr commented
Does this new ServiceAccount need to be added in RBAC.yaml?

2022-04-22 14:37 UTC, travisn commented
> Does this new ServiceAccount need to be added in RBAC.yaml?

Good question, I thought rbac.yaml was generated so I'm curious why it wasn't added there. @BlaineEXE any ideas? Although I stumbled onto a [curious label](https://github.com/rook/rook/blob/release-1.9/build/rbac/rbac.yaml#L1194) in the rbac.yaml, looks leftover from testing.

2022-04-22 19:05 UTC, BlaineEXE commented
> > Does this new ServiceAccount need to be added in RBAC.yaml?
> 
> Good question, I thought rbac.yaml was generated so I'm curious why it wasn't added there. @BlaineEXE any ideas? Although I stumbled onto a [curious label](https://github.com/rook/rook/blob/release-1.9/build/rbac/rbac.yaml#L1194) in the rbac.yaml, looks leftover from testing.

It's possible (but I'm really just guessing) that Helm might do some fancy stuff to remove unused RBAC? Maybe we should look into that.