build: Update min version to k8s 1.17
rook/rook pull request #10123
Opened 2022-04-20 22:55 UTC by travisn

**Description of your changes:**
Support is removed for k8s for various limitations such as priority classes not working and csi driver feature incompleteness and missing snapshots. Documentation is updated with the new min version of k8s 1.17 and also the tests are updated to run on the min version of 1.17.

Let's hold this for a few days to wait for feedback on #10115. 

**Which issue is resolved by this Pull Request:**
Resolves #10115 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-04-25 17:43 UTC, travisn commented
No negative feedback on #10115 so let's go ahead with this

2022-04-25 20:56 UTC, BlaineEXE requested changes
There is really just one issue I see which is the misunderstanding that the "deprecated" labels `failure-domain.beta.kubernetes.io/*` are "unsupported". Kubernetes docs still reference this label, and Kubernetes follows the trend that deprecation comes before removal of support. I think we will have to perpetually support these labels for quite some time since these labels are also tied to other utilities, and users may set these labels themselves for quite some time.

2022-04-25 20:56 UTC, BlaineEXE commented on pkg/operator/ceph/cluster/osd/osd_test.go
> +		"topology.rook.io/row":          "row1",
We should leave these checks. Even though the label is deprecated, support is not fully removed. In K8s, "deprecated" is not synonymous with "unsupported." Kubernetes docs still include them in their well-known labels list: https://kubernetes.io/docs/reference/labels-annotations-taints/

2022-04-25 20:56 UTC, BlaineEXE commented on pkg/operator/ceph/cluster/osd/topology.go
> +	zone, ok := labels[corev1.LabelZoneFailureDomainStable]
Ditto. Even though the label is deprecated, support is not fully removed. Kubernetes docs still include them in their well-known labels list: https://kubernetes.io/docs/reference/labels-annotations-taints/

2022-04-25 20:56 UTC, BlaineEXE commented on pkg/operator/ceph/cluster/osd/topology_test.go
> +	assert.Equal(t, "topology.kubernetes.io/zone=z1", affinity)
Ditto again, the deprecated labels are not "unsupported" labels.

2022-04-26 18:18 UTC, BlaineEXE approved these changes
Looks good to me.

I wonder if it would be good to have a check at the top level of the operator to fail if the kube version isn't high enough (1.17 for now). Pro: It could prevent people from upgrading Rook on a K8s cluster that is too old, saving them from using an unsupported version combination. Con: It would prevent users from using the combination unnecessarily if they don't use any of the 1.17+ features and feel confident about what they're doing.

2022-04-26 18:23 UTC, travisn commented
> I wonder if it would be good to have a check at the top level of the operator to fail if the kube version isn't high enough (1.17 for now). Pro: It could prevent people from upgrading Rook on a K8s cluster that is too old, saving them from using an unsupported version combination. Con: It would prevent users from using the combination unnecessarily if they don't use any of the 1.17+ features and feel confident about what they're doing.

I could see logging a warning, but the philosophy so far has not been to block running on older K8s versions, also mentioned briefly in #10115. Documenting the min version has so far been sufficient.

2022-04-26 18:24 UTC, merged