helm: use correct namespace for provisioner in cephobjectstore template
rook/rook pull request #10154
Opened 2022-04-25 12:50 UTC by bitfisher

Signed-off-by: Markus Schmidleitner <markus.schmidleitner@ocilion.com>

**Description of your changes:**
Use correct namespace for provisioner in cephobjectstore template

**Which issue is resolved by this Pull Request:**
Resolves #10153

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-04-25 14:29 UTC, travisn requested changes
Thanks for the fix. As shown in the CI failure now for the helm upgrade test, the challenge is that upgraded clusters will fail with the following error if the operator is in a different namespace from the cluster:
```
Error: UPGRADE FAILED: cannot patch "ceph-bucket-test-sc" with kind StorageClass: 
StorageClass.storage.k8s.io "ceph-bucket-test-sc" is invalid: provisioner: Forbidden: updates to provisioner are forbidden. , err -> exit status 1
```

To workaround this issue, I'd suggest the following:
1. Add a note to the [upgrade guide](https://github.com/rook/rook/blob/release-1.9/Documentation/ceph-upgrade.md#breaking-changes-in-this-release) that the object store class must be deleted before the upgrade if their operator is in a different namespace from the cluster and their object storage class is enabled.
2. The helm upgrade test must delete the object storage class before upgrade. To help navigate the tests, this might be best done in [ceph_upgrade_test.go](https://github.com/rook/rook/blob/master/tests/integration/ceph_upgrade_test.go#L124) on line 124 by copying line 121 from the test cleanup that deletes the object storage class:

```go
s.helper.BucketClient.DeleteBucketStorageClass(s.namespace, installer.ObjectStoreName, installer.ObjectStoreSCName, "Delete")
```

2022-04-26 12:27 UTC, bitfisher commented
Unfortunately even after setting the correct namespace for provisioner reconciling OBC fails with `unsupported provisioner`.

See https://github.com/rook/rook/issues/5675#issuecomment-1109644166

2022-05-26 18:01 UTC, travisn commented
@bitfisher From the discussion in #10153 it seems you got it working without the namespace prefix, right? So is this PR still needed?

2022-05-30 05:21 UTC, bitfisher commented
Yes, without the namespace prefix it's working as expected, because the operator namespace is used automatically [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/bucket/util.go#L46).
But i think the chart still need to be adjusted because the Release-Namespace is used [there](https://github.com/rook/rook/blob/29c598bc36309ce8c3447aa5a7b2afc903eb2fe7/deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml#L16).

2022-05-31 22:26 UTC, travisn reviewed
Thanks for the explanation, agreed this change is needed. Before merging we just need to have the merge conflict resolved, thanks.

2022-06-28 08:45 UTC, bitfisher commented on Documentation/ceph-upgrade.md
> +* If you use Helm and your operator is in a different namespace from the cluster and object storage class is enabled
Rebased

2022-06-28 14:53 UTC, travisn approved these changes

2022-06-28 14:54 UTC, merged