osd: fix disk uuid management
rook/rook pull request #10212
Opened 2022-05-05 11:57 UTC by satoru-takeuchi

**Description of your changes:**

- disk UUID should only be got for "disk" type device.
- It's not necessary to fail prepare job when failing to get disk UUID
- We should consider that `sgdisk` reports UUID even if there is no GPT.

**Which issue is resolved by this Pull Request:**
Resolves #9948

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2022-05-05 12:28 UTC, leseb commented on pkg/util/sys/device.go
> +		return "", errors.New("sgdisk not found")
Shouldn't we return `err` too?

2022-05-05 12:49 UTC, satoru-takeuchi commented on pkg/util/sys/device.go
> +		return "", errors.New("sgdisk not found")
@leseb Indeed, fixed.

2022-05-05 13:36 UTC, leseb commented on pkg/util/sys/device.go
> +		if strings.Contains(line, "Creating new GPT entries in memory.") {
Can we add a comment that explains why we exit the loop on that condition?

2022-05-05 14:07 UTC, travisn requested changes

2022-05-05 14:07 UTC, travisn commented on pkg/daemon/discover/discover.go
> +		if checkDev.UUID != "UNKNOWN" && dev.UUID != "UNKNOWN" && checkDev.UUID == dev.UUID {
```suggestion
		if checkDev.UUID != "" && dev.UUID != "" && checkDev.UUID == dev.UUID {
```

2022-05-06 19:38 UTC, travisn approved these changes

2022-05-09 09:21 UTC, leseb commented on pkg/clusterd/disk.go
> +	diskUUID := ""
if we keep it empty then this new addition is not needed right? It's not a big deal though...

2022-05-09 09:21 UTC, leseb commented on pkg/util/sys/device.go
> +		if strings.Contains(line, "Creating new GPT entries in memory.") {
?

2022-05-09 09:30 UTC, leseb approved these changes

2022-05-09 10:05 UTC, merged