rgw: support FQDN for RGW endpoint
rook/rook pull request #10232
Opened 2022-05-09 14:28 UTC by parth-gr

Now rgw can be pass by FQDN too,
to avoid problems where it is required
The format should be similar to
Ip(<IP>:<PORT> format), <FQDN>:<PORT> format

Signed-off-by: parth-gr <paarora@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-05-09 15:24 UTC, parth-gr commented on deploy/examples/create-external-cluster-resources.py
> +            "Not a proper endpoint: {}, <IPv4>:<PORT>, format is expected".format(fqdn_rgw_endpoint))
Done

2022-05-10 07:46 UTC, leseb reviewed
How did you validate this?

2022-05-10 07:50 UTC, parth-gr commented
> How did you validate this?

It's already been used for mon-endpoints, so the same functions will be applicable for RGW-endpoint for converting the fqdn to rgw-endpoint, right?

I can't have CI testing for it, because I need to map it to DNS, maybe it is possible?

2022-05-10 14:51 UTC, leseb commented
> > How did you validate this?
> 
> It's already been used for mon-endpoints, so the same functions will be applicable for RGW-endpoint for converting the fqdn to rgw-endpoint, right?
> 
> I can't have CI testing for it, because I need to map it to DNS, maybe it is possible?
> 
> PS: Even I have read about sockets it does the work of listing the Ip through hostname

If we cannot have integration tests, can we have unit tests?

2022-05-11 14:09 UTC, parth-gr commented
> > > How did you validate this?
> > 
> > 
> > It's already been used for mon-endpoints, so the same functions will be applicable for RGW-endpoint for converting the fqdn to rgw-endpoint, right?
> > I can't have CI testing for it, because I need to map it to DNS, maybe it is possible?
> > PS: Even I have read about sockets it does the work of listing the Ip through hostname
> 
> If we cannot have integration tests, can we have unit tests?

Added

2022-05-11 14:15 UTC, leseb approved these changes

2022-05-11 19:08 UTC, BlaineEXE commented
I notice this commit message includes information about RHCS and OCS which are both downstream products. How does this affect upstream users? Let's keep commit messages and descriptions here to only upstream sentiments unless absolutely necessary.

2022-05-11 19:09 UTC, BlaineEXE requested changes
Requesting changes to remove downstream-specific details from the commit message. I think it is better to keep Rook commits all in terms of upstream.

2022-05-11 19:10 UTC, BlaineEXE commented on deploy/examples/create-external-cluster-resources.py
> +                                  help="Rados GateWay endpoint (in <IP>:<PORT> format). Note: FQDN is also supported(in <FQDN>:<PORT> format)")
```suggestion
                                  help="RADOS Gateway endpoint (in <IP>:<PORT> format). Note: FQDN is also supported(in <FQDN>:<PORT> format)")
```

2022-05-12 15:08 UTC, BlaineEXE approved these changes

2022-05-12 17:52 UTC, merged