docs: update tolerations name from controlplane to control-plane
rook/rook pull request #10242
Opened 2022-05-10 19:38 UTC by ttyS0

In the `deploy/examples/operator.yaml` file, the correct name for the control plane toleration key is `node-role.kubernetes.io/control-plane` instead of `node-role.kubernetes.io/controlplane`.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-05-10 20:28 UTC, travisn requested changes
Interesting, in a quick search online I see usages of this toleration both with or without the dash, but in the [K8s docs](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane) with the dash. Sounds good to go with the docs, thanks for catching. Please also make this update to operator-openshift.yaml.

2022-05-10 20:35 UTC, ttyS0 commented
The `operator-openshift.yaml` has been updated as well. 

Thanks!

2022-05-10 20:52 UTC, travisn commented
Looks great. Would you mind just squashing them into a single commit?

2022-05-12 15:06 UTC, BlaineEXE approved these changes

2022-05-12 15:07 UTC, BlaineEXE commented
All good. Thanks.

2022-05-12 16:29 UTC, travisn approved these changes

2022-05-12 16:30 UTC, merged