Remove nodeplugin RBAC and adjust provisioner runner RBAC for CSI PODs
rook/rook pull request #10271
Opened 2022-05-16 08:47 UTC by humblec

- [x] unwanted cephfs csi node plugin RBAC have been removed
- [x] PV rbac has been adjusted for provisioner runner
 
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-05-16 09:01 UTC, humblec commented on deploy/examples/common.yaml
> -  - apiGroups: [""]
Ah :(.. didnt notice that commit ..

2022-05-16 09:01 UTC, humblec commented on deploy/examples/common.yaml
> -  - apiGroups: [""]
let me drop the second commit from here..

2022-05-16 09:02 UTC, subhamkrai commented on deploy/examples/common.yaml
> -  - apiGroups: [""]
sure thanks

2022-05-16 09:21 UTC, humblec commented
Cc @Madhu-1

2022-05-16 09:36 UTC, Madhu-1 requested changes
@humblec please update the commit message and PR title. changes LGTM

2022-05-16 10:03 UTC, humblec commented
> @humblec please update the commit message and PR title. changes LGTM

@madhu-1 adjusted .. thanks.. PTAL

2022-05-17 06:38 UTC, Madhu-1 approved these changes

2022-05-17 13:26 UTC, merged