docs: add prepareosd to placement
rook/rook pull request #10345
Opened 2022-05-27 10:57 UTC by caffeinism

**Description of your changes:**
Add prepareosd as entry available in cluster crd documentation

**Which issue is resolved by this Pull Request:**
Resolves #10331

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-05-27 14:46 UTC, travisn requested changes
Thanks for the doc update! Just a couple suggestions:
- Would you mind also adding `prepareosd` to the example cluster.yaml? Commented out around line 168 similar to the `osd` would be perfect.
- See the commitlint and DCO. Basically, in the commit message if you could provide a sentence describing the change, and also the email signature for the DCO.

2022-05-30 04:06 UTC, caffeinism commented
@travisn Is this ok now?

2022-06-01 12:14 UTC, caffeinism commented
I thought "object" meant "kubernetes object". I fixed it again.

2022-06-01 14:29 UTC, travisn approved these changes

2022-06-01 14:30 UTC, merged