ci: give better folder name
rook/rook pull request #10385
Opened 2022-06-03 04:45 UTC by subhamkrai

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-06-03 13:45 UTC, travisn requested changes
- Could you add some comment in the canary-test-config/action.yaml to point out why it is needed separate from the integration-test-config?
- Please add a more specific commit title such as "ci: more specific ci config folder names"

2022-06-06 05:21 UTC, subhamkrai commented
> * Could you add some comment in the canary-test-config/action.yaml to point out why it is needed separate from the integration-test-config?
added comment in integration-test-config/action.yaml file
> * Please add a more specific commit title such as "ci: more specific ci config folder names"

added

2022-06-06 13:56 UTC, travisn requested changes

2022-06-06 13:56 UTC, travisn commented on .github/workflows/integration-test-config/action.yaml
> +  # This setp is not required for canary integration tests so keeping this new file
Just to be clear, is this valid?
```suggestion
  # This step is required for all the integration tests except the canary tests
```

2022-06-06 14:52 UTC, subhamkrai commented on .github/workflows/integration-test-config/action.yaml
> +  # This setp is not required for canary integration tests so keeping this new file
yes

2022-06-06 15:00 UTC, travisn approved these changes

2022-06-06 15:57 UTC, merged