core: delete v1beta1 cronjob only when v1 not found
rook/rook pull request #10480
Opened 2022-06-21 15:31 UTC by subhamkrai

earlier we're deleting v1beta1 always before creating
v1 job. Now, we delete only when k8s version is
latest(which supports v1  job) and v1 job is not created
which means this is the first time and this is the only time we'll
delete v1beta1.

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-06-21 16:20 UTC, travisn requested changes
Do we need a similar change for the v1beta1 PodDisruptionBudgets?

2022-06-21 16:20 UTC, travisn commented on pkg/operator/ceph/cluster/crash/reconcile.go
> +			if _, err := r.context.Clientset.BatchV1().CronJobs(objectMeta.Namespace).Get(r.opManagerContext, prunerName, metav1.GetOptions{}); err != nil {
How about factoring out to a helper method to delete the cronjob? This looks duplicated.

2022-06-22 11:14 UTC, parth-gr commented
> Do we need a similar change for the v1beta1 PodDisruptionBudgets?

@travisn we dont delete it, we just check which version we need to use and apply it accrodingly.
https://github.com/rook/rook/blob/b0dd11d2bb3972bd2f7b113279737a4fa0abf689/pkg/operator/ceph/cluster/mon/drain.go#L65

2022-06-22 11:22 UTC, parth-gr requested changes

2022-06-22 11:22 UTC, parth-gr commented on pkg/operator/ceph/cluster/crash/crash.go
> +		// delete v1beta1 cronJob if v1Job is not found
I think you can make it more clear here,

// delete v1beta1 cronJob on an update to v1 cronjob, 
only if v1Job is still not created

2022-06-22 14:40 UTC, subhamkrai commented
> Do we need a similar change for the v1beta1 PodDisruptionBudgets?

yes, you want to add in this pr or new pr sounds good?

2022-06-22 16:07 UTC, parth-gr commented
How about adding a unit test for this? 
Fo mainly testing it locally as you needed

2022-06-22 16:40 UTC, travisn requested changes

2022-06-22 16:40 UTC, travisn commented on pkg/operator/ceph/cluster/crash/crash.go
> +func (r *ReconcileNode) deletev1betaAndCreatev1Job(objectMeta metav1.ObjectMeta) error {
It doesn't create the job, right?
```suggestion
func (r *ReconcileNode) deletev1betaJob(objectMeta metav1.ObjectMeta) error {
```

2022-06-23 06:58 UTC, subhamkrai commented on pkg/operator/ceph/cluster/crash/crash.go
> +func (r *ReconcileNode) deletev1betaAndCreatev1Job(objectMeta metav1.ObjectMeta) error {
right

2022-06-23 07:01 UTC, subhamkrai commented
testing:

I  had thtis in the code
```code
if _, err := r.context.Clientset.BatchV1().CronJobs(objectMeta.Namespace).Get(r.opManagerContext, prunerName, metav1.GetOptions{}); err != nil {
		if apierrors.IsNotFound(err) {
			logger.Error("deleting v1beta1")
			err = r.client.Delete(r.opManagerContext, &v1beta1.CronJob{ObjectMeta: objectMeta})
			if err != nil && !apierrors.IsNotFound(err) {
				return errors.Wrapf(err, "failed to delete CronJob v1Beta1 %q", prunerName)
			}
		}
	}
	logger.Error("not deleting")
```

in op logs
```
2022-06-23 06:38:52.452362 E | ceph-crashcollector-controller: deleting v1beta1
2022-06-23 06:38:52.453997 E | ceph-crashcollector-controller: not deleting
...
2022-06-23 06:38:52.599672 E | ceph-crashcollector-controller: not deleting
2022-06-23 06:38:52.603769 E | ceph-crashcollector-controller: not deleting
...
2022-06-23 06:38:56.260595 E | ceph-crashcollector-controller: not deleting
2022-06-23 06:38:56.263438 E | ceph-crashcollector-controller: not deleting
..
2022-06-23 06:38:59.182208 E | ceph-crashcollector-controller: not deleting
2022-06-23 06:38:59.188096 E | ceph-crashcollector-controller: not deleting
....
2022-06-23 06:39:13.356350 E | ceph-crashcollector-controller: not deleting
2022-06-23 06:39:13.358918 E | ceph-crashcollector-controller: not deleting
```

we can see `deleting v1beta1`  is called only once @travisn @parth-gr

2022-06-23 07:02 UTC, subhamkrai commented
> How about adding a unit test for this? For mainly testing it locally as you need

we already have a unit test for this part of the code. maybe I'm missing something that you suggested, could you explain?

2022-06-23 07:39 UTC, parth-gr commented
> > How about adding a unit test for this? For mainly testing it locally as you need
> 
> we already have a unit test for this part of the code. maybe I'm missing something that you suggested, could you explain?

Fine with that

2022-06-23 15:28 UTC, travisn approved these changes

2022-06-23 15:52 UTC, parth-gr approved these changes

2022-06-23 16:07 UTC, merged