docs: add steps to convert existing cephobjectstore into multisite
rook/rook pull request #10735
Opened 2022-08-18 12:48 UTC by thotz

**Description of your changes:**
Most of the users starts with single site, provide the steps to convert
existing cephobjectstore into multisite configurations.

Signed-off-by: Jiffin Tony Thottan <jthottan@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #10416

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-08-18 20:36 UTC, travisn requested changes

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +#### Set up Multisite Configs for already existing CephObjectStore
This should be a higher level title
```suggestion
## Configure an Existing Object Store for Multisite
```

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +      size: 1
In the examples let's use replica 3
```suggestion
      size: 3
```

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +apiVersion: ceph.rook.io/v1
To keep it a bit simpler, I don't think we need this yaml snippet. We can just say we are starting with and existing object store.

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +When a single site `CephObjectStore` CR request comes to Rook, it internally creates zone/zonegroup/realm with the same name as object store. So user can just export them into Kubernetes resources us
```suggestion
When an object store is configured by Rook, it internally creates a zone, zone group, and realm with the same name as the object store. To enable multisite, you will need to create the corresponding zone, zone group, and realm CRs with the same name as the object store. 
```

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +For creating multisite related CRs use the following:
```suggestion
For example, to create multisite CRs for an object store named `my-store`:
```

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +After that modify the `CephObjectStore` CRD and apply below changes on it, this trigger creating `realm system user` secret for multisite.
```suggestion
After that modify the existing `CephObjectStore` CR and apply below changes to trigger creation of the `realm system user` secret for multisite.
```

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +After that modify the `CephObjectStore` CRD and apply below changes on it, this trigger creating `realm system user` secret for multisite.
Where is the `realm system user` secret found? Can we link to somewhere else in the docs for that?

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +After that modify the `CephObjectStore` CRD and apply below changes on it, this trigger creating `realm system user` secret for multisite.
How about pointing out the changes to the object store CR? Is the only change that the pools are removed since they belong to the zone now?

2022-08-18 20:36 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +
How about a separate header?
```
### Renaming the Multisite Resources
```

2022-08-19 19:49 UTC, cbodley commented
> @cbodley : Please take a look on the steps mentioned in the docs. I have tested it manually and everything works fine, This is a variation of https://docs.ceph.com/en/latest/radosgw/multisite/#migrating-a-single-site-system-to-multi-site for Rook

the steps look good to me

2022-08-19 21:04 UTC, travisn requested changes

2022-08-19 21:04 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +After that modify the existing `CephObjectStore` CR to exclude `pool settings` and add reference to `zone`. Apply below changes so that multisite will work smoothly for RGW.
nit: Add a blank line before and after quoted sections
```suggestion

Now modify the existing `CephObjectStore` CR to exclude pool settings and add a reference to the zone. 

```

2022-08-19 21:04 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +#### Using custom names for above procedure
```suggestion
#### Using custom names
```

2022-08-19 21:04 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +If user need to use different name for realm/zone/zonegroup, first rename them in the backend via toolbox pod:
```suggestion
If names different from the object store need to be set for the realm, zone, or zone group, first rename them in the backend via toolbox pod, then following the procedure above.
```

2022-08-19 21:04 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +After that create realm/zonegroup/zone CRs using above names and update the `CephObjectStore` CR as well. Please note rename of multisite settings need to be performed before creating CRs, otherwise
```suggestion
!!! important
    Renaming in the toolbox must be performed **before** creating the multisite CRs
```

2022-08-22 19:51 UTC, travisn requested changes

2022-08-22 19:51 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +      size: 1
```suggestion
      size: 3
```

2022-08-22 19:51 UTC, travisn commented on Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
> +    instances: 3
One instance of rgw is ok for the examples, we just need replica 3 for the pools
```suggestion
    instances: 1
```

2022-08-23 19:17 UTC, travisn requested changes
LGTM, please just squash the commits

2022-08-24 17:26 UTC, travisn approved these changes

2022-08-24 17:26 UTC, merged