docs:updated note label syntax in *.md files
rook/rook pull request #10780
Opened 2022-08-24 10:40 UTC by YashasviChaurasia

The note label is updated in several places in the docs for improved rendering.
Resolves #10458 
Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>

2022-08-24 10:45 UTC, subhamkrai requested changes
commitlint CI is failing. Thanks

2022-08-24 10:58 UTC, YashasviChaurasia commented
> commitlint CI is failing. Thanks

I have committed the message with commit lint standards can you please help me out why is this check failing.
Thank you

2022-08-24 11:13 UTC, subhamkrai commented
> > commitlint CI is failing. Thanks
> 
> I have committed the message with commit lint standards can you please help me out why is this check failing. Thank you

try giving space `docs: updated...`

2022-08-24 11:40 UTC, subhamkrai commented
@YashasviChaurasia you need to use `--amend`.

2022-08-24 11:40 UTC, subhamkrai commented
also, squash your commits in one commit

2022-08-24 12:49 UTC, subhamkrai requested changes

2022-08-24 12:49 UTC, subhamkrai commented on design/ceph/ceph-config-updates.md
> +!!!note on the above
```suggestion
!!! note 
```

2022-08-24 12:49 UTC, subhamkrai commented on design/ceph/ceph-config-updates.md
> +    support integer values as well if at all possible
```suggestion
    support integer values as well if at all possible.
```

2022-08-24 12:49 UTC, subhamkrai commented on design/ceph/interacting-with-rook-resources.md
> +!!!note
```suggestion
!!! note
```

2022-08-25 11:22 UTC, subhamkrai requested changes
@YashasviChaurasia please rebase on master. you have other commits too.

2022-09-22 11:48 UTC, Sheetalpamecha requested changes

2022-09-22 11:48 UTC, Sheetalpamecha commented on pkg/operator/ceph/csi/spec.go
> +
Can avoid extra line

2022-09-22 11:48 UTC, Sheetalpamecha commented on Documentation/Contributing/development-flow.md
> +note!!!
The syntax should be corrected to  - !!! Note

2022-10-17 12:11 UTC, parth-gr commented
@YashasviChaurasia any update??

I see you might be stuck at squashing,

Can you do 
`git remote add upstream https://github.com/rook/rook.git`
`git fetch --all`
`git rebase upstream/master`

2022-10-18 08:34 UTC, YashasviChaurasia commented
> @YashasviChaurasia any update??
> 
> I see you might be stuck at squashing,
> 
> Can you do `git remote add upstream https://github.com/rook/rook.git` `git fetch --all` `git rebase upstream/master`

The problem I am facing is kind of absurd as whenever I squash and submit a PR that is squashed nicely, a new change is requested, and when I modify the change and squash again then, the checks fail, and I have to resubmit multiple times to get the checks to work which further creates multiple PRs, and I need to squash them all again ... and hence this loop never seem to end.

2022-10-18 08:38 UTC, YashasviChaurasia commented
> > @YashasviChaurasia any update??
> > I see you might be stuck at squashing,
> > Can you do `git remote add upstream https://github.com/rook/rook.git` `git fetch --all` `git rebase upstream/master`
> 
> The problem I am facing is kind of absurd as whenever I squash and submit a PR that is squashed nicely, a new change is requested, and when I modify the change and squash again then, the checks fail, and I have to resubmit multiple times to get the checks to work which further creates multiple PRs, and I need to squash them all again ... and hence this loop never seem to end.

I was busy for a while, will try to work and get this done today.
The problem is not with the PR but with the checks, and to re-run the checks, I need to change the PR a little, which is already complete, which causes issues while submitting GitHub PR in a proper format.

2022-10-18 16:34 UTC, YashasviChaurasia commented
```Canary integration tests / multi-cluster-mirroring (pull_request)```
@parth-gr I am unable to understand why this check is failing.
Kindly help me out with this.
Thank you

2022-10-18 17:11 UTC, YashasviChaurasia commented
@parth-gr the rebase if failing and I am not able to switch branches now on the terminal.

2022-10-18 19:10 UTC, BlaineEXE commented
@YashasviChaurasia please rebase your branch on the latest upstream rook master. This pull request is attempting to merge 142 commits that are mostly duplicates of already-existing changes. We simply cannot merge such a PR. If you aren't sure how to rebase on the latest upstream master, please look to the plethora of helpful articles written about it like this one: https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a.

2022-10-18 19:17 UTC, YashasviChaurasia commented
@BlaineEXE I completely understand your point, and I am ready to rebase, but I am unable to do it on my local repo due to some issues I have created.
Can I delete this PR and create a fresh PR, as I am unable to switch branches on my local repo?
Thank you

2022-10-18 19:27 UTC, BlaineEXE commented
> @BlaineEXE I completely understand your point, and I am ready to rebase, but I am unable to do it on my local repo due to some issues I have created. Can I delete this PR and create a fresh PR, as I am unable to switch branches on my local repo? Thank you

You're free to resolve it in any way you need to. For the health of the Rook repository, we cannot merge this PR in its current state. If you create a new PR, it would be most helpful to link to the PR taking over for this one.

2022-10-18 20:20 UTC, YashasviChaurasia commented
@BlaineEXE 
I am closing this issue, and the link to a new issue has been linked below.
I have ensured all the checks pass and only make a clean single commit.
Thank you
New PR: rook/rook#11171

2022-10-18 20:20 UTC, closed without merging