object: gateway.port partially ignored when hostNetwork disabled
rook/rook pull request #10804
Opened 2022-08-26 09:41 UTC by zhucan

Signed-off-by: zhucan <zhucan.k8s@gmail.com>

**Description of your changes:**
If hostNetwork is enabled to cluster and disabled to store, the contianer port is 8080, and service port is 80.

**Which issue is resolved by this Pull Request:**
Resolves #10743 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-08-26 09:42 UTC, zhucan commented
```
[root@rook-node02 ~]# kubectl get service -n rook-ceph rook-ceph-rgw-my-store -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-08-26T09:26:35Z"
  labels:
    app: rook-ceph-rgw
    app.kubernetes.io/component: cephobjectstores.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: my-store
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-rgw
    app.kubernetes.io/part-of: my-store
    ceph_daemon_id: my-store
    ceph_daemon_type: rgw
    rgw: my-store
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
    rook_object_store: my-store
  name: rook-ceph-rgw-my-store
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephObjectStore
    name: my-store
    uid: 831738e0-e8ba-4b74-a725-2c84d23e013f
  resourceVersion: "9403"
  uid: e80db266-0a2d-4aa8-8529-d3eafff103e4
spec:
  clusterIP: 10.100.224.126
  clusterIPs:
  - 10.100.224.126
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: my-store
    rgw: my-store
    rook_cluster: rook-ceph
    rook_object_store: my-store
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

2022-08-26 14:41 UTC, travisn requested changes
There is one more place on line 213 that seems like needs to be fixed as well.

2022-08-29 02:26 UTC, zhucan commented
@travisn done

2022-08-30 11:19 UTC, zhucan commented
@travisn Could you help to merge it?

2022-08-30 14:05 UTC, travisn commented
> There is one more place on line 213 that seems like needs to be fixed as well.

@zhucan Doesn't line 213 also need to be converted from `c.clusterSpec.Network.IsHost()` to `c.store.Spec.IsHostNetwork(c.clusterSpec)`? I don't see that update.

2022-08-31 02:20 UTC, zhucan commented
@travisn I'm sorry, please take a look again.

2022-08-31 15:26 UTC, travisn approved these changes

2022-08-31 15:27 UTC, merged