docs(nixos): explain specific configurations
rook/rook pull request #11029
Opened 2022-09-21 08:04 UTC by yajo

**Description of your changes:**
Explain the fix for https://github.com/rook/rook/issues/10932 to let NixOS users set up Rook more easily.

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/rook/rook/pull/10942#discussion_r971577389

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR. I can't!
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

@moduon MT-1248

2022-09-21 08:27 UTC, parth-gr commented
PLease add a signed-off in the commit message

2022-09-21 08:31 UTC, parth-gr commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
> +```yaml
@travisn how about also leaving this setting commented in the manifest files?

2022-09-26 06:22 UTC, yajo commented
Signed.

2022-09-26 06:55 UTC, parth-gr commented
DCO still fails, can you please fix that,

It shows the error
`Commit sha: [d074f75](https://github.com/rook/rook/pull/11029/commits/d074f754c9fefd04c14fab6a4c50ea36fc29c442), Author: Jairo Llopis, Committer: Jairo Llopis; Expected "Jairo Llopis [973709+yajo@users.noreply.github.com](mailto:973709+yajo@users.noreply.github.com)", but got "Jairo Llopis [jairo@moduon.team](mailto:jairo@moduon.team)".`

2022-09-26 06:55 UTC, parth-gr commented
> DCO still fails, can you please fix that,
> 
> It shows the error `Commit sha: [d074f75](https://github.com/rook/rook/pull/11029/commits/d074f754c9fefd04c14fab6a4c50ea36fc29c442), Author: Jairo Llopis, Committer: Jairo Llopis; Expected "Jairo Llopis [973709+yajo@users.noreply.github.com](mailto:973709+yajo@users.noreply.github.com)", but got "Jairo Llopis [jairo@moduon.team](mailto:jairo@moduon.team)".`

Seems like not a correct sign-off

2022-09-26 08:58 UTC, yajo commented
Let's see now.

2022-09-26 09:16 UTC, parth-gr approved these changes
Looks good to me.
Let @travisn review it once.

2022-09-27 14:30 UTC, travisn requested changes
For the commit message, let's just have a "docs:" prefix, something like this:
```
docs: explain specific nixos configurations
```

2022-09-27 14:30 UTC, travisn commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
> +and they'll be symlinks to stuff located inside the also non-standard path `/nix`.
```suggestion
and they'll be symlinked inside the non-standard path `/nix`.
```

2022-09-27 14:30 UTC, travisn commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
> +If you install Rook with Helm, add this to your `values.yaml`:
How about if we leave the complex example settings out of this doc and just mention the setting names?
```suggestion
If you install Rook with Helm, uncomment the examples settings in `values.yaml`:
- `csiCephFSPluginVolume`
- `csiCephFSPluginVolumeMount`
- `csiRBDPluginVolume`
- `csiRBDPluginVolumeMount`
```

2022-09-28 06:50 UTC, yajo commented
All attended.

2022-09-28 16:39 UTC, travisn commented
> For the commit message, let's just have a "docs:" prefix, something like this:
> 
> ```
> docs: explain specific nixos configurations
> ```

Just one more nit on the commit message, thanks!

2022-10-04 06:28 UTC, yajo commented
You got it!

2022-10-04 13:27 UTC, travisn approved these changes

2022-10-04 13:28 UTC, merged