helm: fix toolbox command, default to cluster image
rook/rook pull request #11127
Opened 2022-10-07 17:59 UTC by LoicGombeaud

**Description of your changes:**
This integrates the [toolbox spec from the examples](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml) into the chart `rook-ceph-cluster`, in order to simplify the setup of the toolbox: just flip `toolbox.enabled` to `true`.

**Which issue is resolved by this Pull Request:**
Resolves #11126 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-10-10 17:39 UTC, travisn requested changes
Please also update the [helm integration test](https://github.com/rook/rook/blob/master/tests/framework/installer/ceph_helm_installer.go#L120), perhaps to comment out that line that sets the image and use the default. The test is passing even without the change, but it will be good to test the default image.

Interestingly, the rook image can still be used even with this change, so it's nice that it's not a breaking change.

2022-10-11 06:39 UTC, sp98 approved these changes

2022-10-12 08:18 UTC, LoicGombeaud commented
> Please also update the [helm integration test](https://github.com/rook/rook/blob/master/tests/framework/installer/ceph_helm_installer.go#L120), perhaps to comment out that line that sets the image and use the default. The test is passing even without the change, but it will be good to test the default image.
> 
> Interestingly, the rook image can still be used even with this change, so it's nice that it's not a breaking change.

Done; I'm not a big fan of commented out code, so I've explicitly set the image to `""`, and added a comment explaining that it will result in the default image being used (i.e. the Ceph image); does that work for you?

2022-10-12 20:25 UTC, travisn commented
> The helm tests are failing after my change, I'll take a look ASAP

Looks like the default image is not getting set during upgrade:
```
Error: INSTALLATION FAILED: Deployment.apps "rook-ceph-tools" is invalid: spec.template.spec.containers[0].image: Required value, err=Failed to run helm command on args [install --create-namespace rook-ceph-cluster rook-release/rook-ceph-cluster --version=v1.9.10 --namespace upgrade -f values-test.yaml] 
```

2022-11-14 23:07 UTC, travisn requested changes
@LoicGombeaud would be great to get the CSI passing and get this merged, thanks!

2022-11-14 23:07 UTC, travisn commented on tests/framework/installer/ceph_helm_installer.go
> +		"image":     "",
I wonder if we need to remove this property completely. It must be picking up this empty string instead of allowing the default value to be set.

2022-11-14 23:08 UTC, travisn commented on tests/framework/installer/ceph_helm_installer.go
> +		"image":     "",
```suggestion
```

2023-01-04 21:59 UTC, travisn approved these changes

2023-01-04 22:00 UTC, merged