docs: updated syntax in markdown files
rook/rook pull request #11171
Opened 2022-10-18 19:42 UTC by YashasviChaurasia

The `Note` label is updated in several places in the docs for improved rendering.
Multiple markdown files have been updated.
Resolves https://github.com/rook/rook/issues/10458

Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>

2022-10-18 20:43 UTC, BlaineEXE requested changes
Not all instances of "note that" indicate a callout. Contextually, a standalone bullet, a block quote, or a bold bit of text like "note"/"info"/"warning"/"important" will be the best indicator.

Also, keep in mind that in order to render correctly, the text of a callout has to be indented to the same level as the type of callout (4 additional spaces).

2022-10-18 20:43 UTC, BlaineEXE commented on Documentation/Contributing/development-flow.md
> +That writing code to prototype the feature while working on the design may be very useful to help flesh out the approach.
```suggestion
!!! Note
    Writing code to prototype the feature while working on the design may be very useful to help flesh out the approach.
```

2022-10-18 20:43 UTC, BlaineEXE commented on design/ceph/ceph-config-updates.md
> +    Currently, `dataDirHostPath` is mapped directly to containers, meaning that each
This isn't really a callout. Let's revert this.

```suggestion
  - Note that currently, `dataDirHostPath` is mapped directly to containers, meaning that each
```

2022-10-18 20:43 UTC, BlaineEXE commented on design/ceph/ceph-config-updates.md
> +All values under config are reported to Ceph as strings, but the yaml should
To render properly, callouts need to have their text indented 4 spaces (to the same level as the type of callout).

```suggestion
!!! Note
    All values under config are reported to Ceph as strings, but the yaml should
```

2022-10-18 20:43 UTC, BlaineEXE commented on Documentation/Contributing/development-flow.md
> +Sometimes you will feel like there is not so much to say, for instance if you are fixing a typo in a text.
```suggestion
!!! Note
    Sometimes you will feel like there is not so much to say, for instance if you are fixing a typo in a text.
```

2022-10-18 20:43 UTC, BlaineEXE commented on design/ceph/interacting-with-rook-resources.md
> +This full spec can easily exceed the 64-character limit imposed on Kubernetes labels.
The phrase "note that" does not always indicate a callout. There is only one callout here. Also, indentation.

```suggestion
!!! Note
    A totally unique string for an application can be built up from (a) app.kubernetes.io/component, (b) app.kubernetes.io/part-of, (c) the resource's namespace, (d) app.kubernetes.io/name, and (e) app.kubernetes.io/instance fields. For the example above, we could join those fields with underscore connectors like this: cephclusters.ceph.rook.io_rook-ceph_rook-ceph_ceph-mon_a. Note that this full spec can easily exceed the 64-character limit imposed on Kubernetes labels.
```

2022-10-18 20:44 UTC, BlaineEXE commented
Also, please make the commit message more clear. "updated syntax" is not clear. Also include the text from the PR description in the body of the commit message.

2022-10-18 20:44 UTC, BlaineEXE commented
oops. accidentally hit close button.

2022-10-19 06:13 UTC, YashasviChaurasia commented
@BlaineEXE is this commit message good enough?

"docs: updated `note` syntax in markdown files
The syntax to write guiding or cautionary notes in markdown files was updated.
The inconsistencies  in the syntax were removed"

Kindly inform me if you want any changes
Thank you

2022-10-19 13:22 UTC, YashasviChaurasia commented
> Can you squash all the commits into a single commit.

Yes sure, but could you give some feedback on the commit message if I should use it or not

2022-10-19 16:24 UTC, BlaineEXE commented
I only see this commit message:

```
docs: updated note syntax in markdown files and squashed commits
Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>
```

A few notes:

1. commit messages should only reflect changes to code. Squashing comments is a regular git process that doesn't need commented on. Let's remove "and squashed commits". Other than that, the subject line is good
2. the commit message should have a body. I think it may have gotten lost in the squashing process. I believe `git commit --amend` should allow you to quickly edit the commit message.
3. @parth-gr I generally see "resolves" and "closes" used interchangeably. That's how Github treats them at least. I think either option is fine for Rook.

2022-10-20 13:52 UTC, parth-gr commented
```
[docs: updated note syntax in markdown files](https://github.com/rook/rook/pull/11171/commits/451d53201fdbc48db60ded49f67846e20c2c6b49) 

The Note label is updated in several places in the docs for improved rendering.
Multiple markdown files have been updated.
Closes: https://github.com/rook/rook/issues/10458

Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>
```
THere should be gap in betwween
```
[docs: updated note syntax in markdown files](https://github.com/rook/rook/pull/11171/commits/451d53201fdbc48db60ded49f67846e20c2c6b49) 

The Note label is updated in several places in the docs for improved rendering.
Multiple markdown files have been updated.
<-gap here->
Closes: https://github.com/rook/rook/issues/10458

Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>
```

2022-10-20 14:43 UTC, parth-gr approved these changes

2022-10-20 15:01 UTC, BlaineEXE approved these changes

2022-10-20 15:03 UTC, merged

2022-10-20 16:43 UTC, YashasviChaurasia commented
This PR helped me learn a lot about squashing and amending commits.
Thank you, @parth-gr @BlaineEXE, for helping me figure out stuff and always being patient.
Thanks a lot