helm: change `pspEnable` default value to `false`
rook/rook pull request #11263
Opened 2022-11-03 16:11 UTC by zalsader

Disable `PodSecurityPolicy` in Ceph Operator helm charts by default

PodSecurityPolicy was [deprecated](https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation) in Kubernetes v1.21, and removed from Kubernetes in v1.25.
Trying to install the [Ceph Operator helm chart](https://rook.io/docs/rook/latest/Helm-Charts/operator-chart/) with the default options fails in Kubernetes v1.25 because `pspEnable` is set to true. This PR changes the default value to false and updates the documentation. I think we should consider removing that option in the future.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-11-03 20:18 UTC, travisn requested changes
Agreed it makes sense to change the default for the PSPs to false, though are you actually hitting an error in k8s 1.25? There is a condition wherever the chart creates PSPs that the K8s version must be less than 1.25 or else the PSPs will be skipped. See [here](https://github.com/rook/rook/blob/master/deploy/charts/library/templates/_cluster-psp.tpl#L5). Is that not working for you? 

There is another location in the [operator chart values.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml#L52) that also needs to be changed.

2022-11-07 21:08 UTC, zalsader commented
I found out that the issue I was having was some networking issue and was not related to `pspEnable`. Nevertheless, it could still be beneficial to disable this by default

2022-11-07 21:22 UTC, travisn commented
> I found out that the issue I was having was some networking issue and was not related to `pspEnable`. Nevertheless, it could still be beneficial to disable this by default

Agreed, let's disable it by default. I'm thinking we should merge this to master, but wait for v1.11 to include in a release. Please add a note with this PR to PendingReleaseNotes.md so we will mention it in the release notes.

Also, how about a commit prefix of `security:` since this doesn't just apply to helm.

2022-11-09 23:48 UTC, travisn approved these changes

2022-11-09 23:48 UTC, merged