ceph: role rook-ceph-mgr is lack of patch verb to compete ceph request(fix 11537)
rook/rook pull request #11538
Opened 2023-01-13 16:43 UTC by gaord

ceph orch command uses patch method to update cephcluster. Adding patch to verbs list of rook-ceph-mgr(Role) to make it work. It was allright with deploy/charts/rook-ceph-cluster/charts/library/templates/_cluster-role.tpl to justify the changes quite a bit.

Signed-off-by: Ben Gao <bengao168@msn.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-01-13 16:54 UTC, jmolmo approved these changes
LGTM

2023-01-13 17:04 UTC, travisn reviewed
While it looks like this will fix #11537, let's first discuss the scenario on that issue to understand the use case. Thanks!

2023-01-18 00:26 UTC, travisn requested changes
@gaord The commitlint action is failing due to an invalid prefix. Let's use the `mgr:` prefix instead for the commit message

2023-01-18 08:45 UTC, gaord commented
oops,forgot commit title.done

2023-01-18 19:43 UTC, travisn approved these changes

2023-01-18 19:44 UTC, merged