core: operator to skip reconcile of mgrs and mds
rook/rook pull request #11802
Opened 2023-03-01 11:06 UTC by microyahoo

**Description of your changes:**
During certain maintenance tasks the admin will own running operations on the ceph mgrs and mds, and the operator should not interfere with those operations. If the operator sees the label has been set, the reconcile will be skipped.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-03-01 21:45 UTC, travisn requested changes
This do-not-reconcile flag was originally added for mons and OSDs to support some operations in the [krew plugin](https://github.com/rook/kubectl-rook-ceph). Do you have specific maintenance tasks that could be considered for adding also to the plugin? 

In general, I hesitate to add this feature to all daemons since when enabled it will cause the operator to not perform expected updates, and can cause problems if left enabled too long. For example, the reconcile really shouldn't be skipped during upgrades. But if it is helpful for some scenario, it certainly can be added.

Please add a description paragraph to the commit message as well. Otherwise, the changes look good to me.

2023-03-02 06:59 UTC, microyahoo commented
> This do-not-reconcile flag was originally added for mons and OSDs to support some operations in the [krew plugin](https://github.com/rook/kubectl-rook-ceph). Do you have specific maintenance tasks that could be considered for adding also to the plugin?
> 
> In general, I hesitate to add this feature to all daemons since when enabled it will cause the operator to not perform expected updates, and can cause problems if left enabled too long. For example, the reconcile really shouldn't be skipped during upgrades. But if it is helpful for some scenario, it certainly can be added.
> 
> Please add a description paragraph to the commit message as well. Otherwise, the changes look good to me.

Hi @travisn, yes, left the label enabled too long will indeed cause problems, but we hope that we can control the restart time and order of pods, instead of letting the program restart randomly.

2023-03-02 17:46 UTC, travisn commented
> Hi @travisn, yes, left the label enabled too long will indeed cause problems, but we hope that we can control the restart time and order of pods, instead of letting the program restart randomly.

You want to control this during upgrades? Or just during maintenance operations? I would be concerned about changing the upgrade sequence because there could be some unpredictable side effects if we test the upgrades without this flag, and then this flag is added to some components during upgrades. It just becomes the responsibility of whoever adds those flags for any potential side effects. If there is a question about how to have better control during upgrades, I'd suggest we open an issue about that.

2023-03-09 02:47 UTC, microyahoo commented
Hi @travisn, sorry for late response, I have created a discussion https://github.com/rook/rook/discussions/11860 to follow it, thanks again.

2023-04-22 20:02 UTC, closed without merging