Fix documentation indentation
rook/rook pull request #11825
Opened 2023-03-02 23:36 UTC by ajschmidt8

**Description of your changes:**

It seems that this `deviceFilter` list item is indented too far.

This PR de-indents it one level.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-03-02 23:54 UTC, travisn requested changes
Thanks for catching this, just one suggestion... The commit message needs to have a prefix from .commitlintrc.json, such as:
```
docs: fix devicefilter documentation indentation
```

2023-03-03 00:00 UTC, ajschmidt8 commented
> Thanks for catching this, just one suggestion... The commit message needs to have a prefix from .commitlintrc.json, such as:
> 
> ```
> docs: fix devicefilter documentation indentation
> ```

updated.

2023-03-03 00:03 UTC, travisn approved these changes
LGTM, github actions just appear to be down right now, will merge after they're running again...

2023-03-06 12:54 UTC, subhamkrai commented
@mergifyio rebase

2023-03-06 12:55 UTC, subhamkrai commented
> LGTM, github actions just appear to be down right now, will merge after they're running again...

CI is back

2023-03-06 15:02 UTC, merged