docs: an update to disaster recovery with new scenario
rook/rook pull request #11895
Opened 2023-03-13 16:07 UTC by gaord

**Description of your changes:**

add recovering steps when rook crs and ceph daemons are all deleted.
here is the context: https://github.com/rook/rook/discussions/11821

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-03-17 20:38 UTC, travisn reviewed
@gaord That's great to hear you were able to fully recover your cluster even after the entire rook namespace was deleted. We have wanted to document this scenario for a long time as seen in #7154 and https://github.com/rook/kubectl-rook-ceph/issues/74. It's great to see the steps were not even too complicated. 

@gauravsitlani Could you repro this recover to get more validation since you have been investigating it?

I will have some suggestions on the formatting of the document, but will wait first to see if it's possible for someone else to verify the steps. 

Thanks for the contribution!

2023-03-20 10:05 UTC, gaord commented
> @gaord That's great to hear you were able to fully recover your cluster even after the entire rook namespace was deleted. We have wanted to document this scenario for a long time as seen in #7154 and [rook/kubectl-rook-ceph#74](https://github.com/rook/kubectl-rook-ceph/issues/74). It's great to see the steps were not even too complicated.
> 
> @gauravsitlani Could you repro this recover to get more validation since you have been investigating it?
> 
> I will have some suggestions on the formatting of the document, but will wait first to see if it's possible for someone else to verify the steps.
> 
> Thanks for the contribution!

Glad to be able to contribute to ceph/rook community. any questions over the course of repro?

2023-03-28 11:42 UTC, galexrt requested changes
@travisn @gauravsitlani How should we proceed with this PR/ document?

The instructions look sane enough that after fixing up the formatting points, I think would be okay to merge and improve upon in future PRs. What do you think?

@gaord Are you available to update the formatting comments in the whole document?

2023-03-28 11:42 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +"ceph-secret" and "mon-secret" are to be filled with client.admin's keyring string. "ceph-username" to be string "client.admin". "fsid" to be original ceph cluster id. They could be found in dataDirH
```suggestion
`ceph-secret` and `mon-secret` are to be filled with `client.admin`'s keyring contents. `ceph-username` to be string `client.admin`. `fsid` to be original ceph cluster id. These files can be found in `$dataDirHostPath/rook-ceph/client.admin.keyring` and `$dataDirHostPath/rook-ceph/rook-ceph.config`.
```

2023-03-28 11:42 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +"mapping" tell rook where to schedule monitor's pods. you could search in dataDirHostPath in all ceph cluster hosts for mon-m,mon-o,mon-k. If you find mon-m in host 10.138.55.120, you should fill 10.
```suggestion
`mapping` tell rook where to schedule monitor's pods. you could search in `dataDirHostPath` in all Ceph cluster hosts for `mon-m,mon-o,mon-k`. If you find `mon-m` in host `10.138.55.120`, you should fill `10.138.55.120` in mapping for `m`. Others are the same.
```

2023-03-28 11:42 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +Now with correct information hold in yamls rook-ceph-mon.yaml and rook-ceph-mon-endpoints.yaml, you are ready to go restore.
```suggestion
Now with correct information hold in YAMLs `rook-ceph-mon.yaml` and `rook-ceph-mon-endpoints.yaml`, you are ready to continue with the final restore steps.
```

2023-03-28 11:42 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +Remember to update maxMonId as the max numeric order of current monitor ids(15 for id "o" for example).
```suggestion
Remember to update `maxMonId` as the max numeric order of current monitor ids (15 for id "o" for example).
```

2023-03-29 15:58 UTC, gaord commented
> @travisn @gauravsitlani How should we proceed with this PR/ document?
> 
> The instructions look sane enough that after fixing up the formatting points, I think would be okay to merge and improve upon in future PRs. What do you think?
> 
> @gaord Are you available to update the formatting comments in the whole document?

@galexrt Done.

2023-04-03 10:52 UTC, gaord commented
> @gaord can you share a demo / test steps if you can try reproducing and demonstrating here ?

The steps should be complete in general for restoring. Is there anything not working in the lab?

2023-04-03 21:05 UTC, travisn requested changes
Looks good, I just have some wording suggestions, thanks!

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +Now with correct information hold in YAMLs `rook-ceph-mon.yaml` and `rook-ceph-mon-endpoints.yaml`, you are ready to continue with the final restore steps.
```suggestion
Now that you have the info for the secret and the configmap, you are ready to restore the running cluster.
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +Deploy Rook Ceph using the YAML files or Helm:
```suggestion
Deploy Rook Ceph using the YAML files or Helm, with the same settings you had previously.
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +wait until operator is up right. Then create two CRs you have just crafted:
```suggestion
After the operator is running, create the configmap and secret you have just crafted:
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +create your "new" ceph cluster:
```suggestion
Create your ceph cluster CR (if possible, with the same settings as existed previously):
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +Now your ceph cluster should be back running again.
```suggestion
Now your ceph cluster should be running again.
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +```
Add this line:
```
Now save the secret as `rook-ceph-mon.yaml`, to be created later in the restore.
```

2023-04-03 21:05 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +
Add this line:
```
Now save this configmap in the file rook-ceph-mon-endpoints.yaml, to be created later in the restore.
```

2023-04-04 12:48 UTC, parth-gr commented
@travisn @subhamkrai can we have a krew command for this?

2023-04-04 13:05 UTC, gaord commented
> Looks good, I just have some wording suggestions, thanks!

wording is polished as wish. @travisn

2023-04-04 13:40 UTC, galexrt requested changes
Some last nits from my side after that I'm good with merging it

2023-04-04 13:40 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +When the rook-ceph namespace is accidentally deleted, the good news is that the cluster can be restored. With the content in the directory `dataDirHostPath` and the original OSD disks, the ceph clust
```suggestion
## Restoring the Rook cluster after the Rook namespace is deleted

When the rook-ceph namespace is accidentally deleted, the good news is that the cluster can be restored. With the content in the directory `dataDirHostPath` and the original OSD disks, the ceph cluster could be restored with this guide.
```

2023-04-04 13:40 UTC, galexrt commented on Documentation/Troubleshooting/disaster-recovery.md
> +For Monitor's service ips are also kept in monitor data store you need to keep them consistent. You could modify them in this yaml and let rook operator create them for you, so that you don't have to
Please have an empty line between the start/end of each code block

2023-04-04 14:49 UTC, travisn commented
> > Looks good, I just have some wording suggestions, thanks!
> 
> wording is polished as wish. @travisn

Thanks! Looks good to me, and agreed with @galexrt 's final suggestions.

2023-04-06 03:56 UTC, gaord commented
> Some last nits from my side after that I'm good with merging it

nice formatting. done. @galexrt

2023-04-06 07:51 UTC, galexrt approved these changes

2023-04-06 13:42 UTC, travisn requested changes
A few more formatting issues

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +```console
```suggestion
```yaml
```

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +All the fields in data section need to be encoded in base64. Coding could be done like this:
Blank line before and after a paragraph, otherwise the rendering combines this with the previous bullet.

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +```console
```suggestion
```yaml
```

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +For Monitor's service ips are also kept in monitor data store you need to keep them consistent. You could modify them in this yaml and let rook operator create them for you, so that you don't have to
```suggestion
The Monitor's service IPs are kept in the monitor data store and you need to keep them consistent. After you create this configmap with the service IPs, the rook operator will create the services for you. Along with monitor ids, the service IPs can be found in dataDirHostPath/rook-ceph/rook-ceph.config, for example:
```

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +`mon initial members` and `mon host` are in the same order as a result you can tell which id for which service IP addresses. Modify your `rook-ceph-mon-endpoints.yaml` based on the information in `ro
?

2023-04-06 13:42 UTC, travisn commented on Documentation/Troubleshooting/disaster-recovery.md
> +`mapping` tell rook where to schedule monitor's pods. you could search in `dataDirHostPath` in all Ceph cluster hosts for `mon-m,mon-o,mon-k`. If you find `mon-m` in host `10.138.55.120`, you should
?

2023-04-07 14:08 UTC, gaord commented
> A few more formatting issues
@travisn 
how does it look then.

2023-04-07 14:11 UTC, travisn approved these changes
The rendering looks good now, thanks!

2023-04-07 14:11 UTC, merged