External Cluster EC Metadata/Data Pool is reversed causing PVC creation to fail
rook/rook pull request #11919
Opened 2023-03-16 15:21 UTC by dragon2611

Pool and Metadata Pool Appear to be reversed causing PVC creation to fail

**Description of your changes:**
It seems the data-pool and EC pool on an external cluster are set the wrong way round in the example code for configuring external clusters

dataPool: needs to contain the EC Data pool
pool: needs to contain the Metadata Pool

**Which issue is resolved by this Pull Request:**
Resolves 
https://github.com/rook/rook/issues/11918

2023-03-16 18:06 UTC, travisn requested changes
The changes look good, thanks for the contribution. It appears nobody used the EC pools before for the external clusters. 

To make the commitlint bot happy, try the following:
```
external: pool and metadata ec pools were reversed in scripts
```

2023-03-16 20:23 UTC, dragon2611 commented
Not sure that should have really been a force push on my repo, but I did a git commit --amend to change the commit message, hopefully the bot is happier now.

2023-03-16 20:53 UTC, travisn commented
> Not sure that should have really been a force push on my repo, but I did a git commit --amend to change the commit message, hopefully the bot is happier now.

Looks good now, thanks. Actually the force push is recommended, see our [dev guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) for future reference.

2023-03-16 20:56 UTC, travisn approved these changes
Just waiting for the CI now to merge...

2023-03-16 21:29 UTC, travisn requested changes
Oh, I overlooked that the DCO check is failing. See the [dev guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) on the expected signature in the commit message, thanks.

2023-03-16 22:28 UTC, dragon2611 commented
Hopefully it's happier now.

2023-03-16 22:41 UTC, dragon2611 commented
@travisn seems the DCO check is still not happy?
Only thing I can think of is that email doesn't match the github account that it thinks made the commit (which it seems to have taken from one of my SSH keys)

2023-03-16 22:46 UTC, travisn commented
> @travisn seems the DCO check is still not happy? Only thing I can think of is that email doesn't match the github account that it thinks made the commit (which it seems to have taken from one of my SSH public keys)

It looks like the right format, i'm not sure it validates the email anyway. On occasion it's not clear what it's being picky about, so set it to ignore for this commit.

2023-03-16 22:46 UTC, travisn approved these changes

2023-03-17 00:02 UTC, merged

2023-03-17 07:23 UTC, parth-gr commented
So @travisn @dragon2611 we also need similar change here? https://github.com/rook/rook/blob/44d58ef6053e70d69fd1532e354d50f89ac95ee5/deploy/examples/csi/rbd/storageclass-ec.yaml#L45

2023-03-17 08:50 UTC, dragon2611 commented
@parth-gr That looks ok to me, it seems when using a standard replicated pool you just need pool but for EC you need a standard replicated pool for the metadata and then the EC pool for the data.

dataPool: Should be the EC pool
pool: Should be the replicated metadata pool

2023-03-17 09:14 UTC, parth-gr commented
agree thanks