osd: handle global or node-local device class configuration correctly
rook/rook pull request #11966
Opened 2023-03-23 07:27 UTC by satoru-takeuchi

**Description of your changes:**

Rook uses global or node-local device class configuration if device-level configuratios doesn't exist. However, after introducing device-class level resource configuration, rook set the default value of device class. So global or node-level device class configuration has never been used after that.

**Which issue is resolved by this Pull Request:**
Resolves #11826 #11871

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2023-03-23 08:35 UTC, parth-gr commented on pkg/daemon/ceph/osd/daemon.go
>  						}
Please also add an unit test for it.
Thanks

2023-03-23 15:16 UTC, travisn requested changes
Thanks for the fix!

2023-03-23 15:16 UTC, travisn commented on pkg/daemon/ceph/osd/daemon.go
> +							if agent.storeConfig.DeviceClass != "" {
How about adding a comment here in the code to describe the scenario?

2023-03-29 10:39 UTC, subhamkrai approved these changes

2023-03-29 14:03 UTC, travisn approved these changes

2023-03-29 14:03 UTC, merged