docs: Update core getting started docs for clarity
rook/rook pull request #12146
Opened 2023-04-26 23:31 UTC by travisn

**Description of your changes:**
- Update the getting started guide, prereqs, architecture, and other basic docs with more concise wording and removed some obsolete information. Some links are removed so they don't distract the user from reading the critical information that we are conveying in the rook docs.
- Managing OSDs and mons is one of the most common requests for troubleshooting help. Make these topics more discoverable by symlinking them to the troubleshooting section of the docs.
- Since Cassandra is no longer supported and Yannis is no longer active on the project, move him to Emeritus maintainer.

These updates are a result of a good conversation at Cephalocon with @zdover23 (Ceph docs lead) on what we can do to clarify and improve Rook documentation. More updates to come...

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-04-27 02:30 UTC, sp98 requested changes
Few nits about `you` and `your` references. You can ignore them if they are not very relevant.

2023-04-27 02:30 UTC, sp98 commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
> +Confirm whether your partitions or devices are formatted with filesystems with the following command:
```suggestion
Confirm whether the partitions or devices are formatted with filesystems with the following command:
```

2023-04-27 02:30 UTC, sp98 commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
>  If LVM is required for your scenario, LVM needs to be available on the hosts where OSDs will be running.
```suggestion
If LVM is required, LVM needs to be available on the hosts where OSDs will be running.
```

2023-04-27 02:30 UTC, sp98 commented on Documentation/Getting-Started/Prerequisites/prerequisites.md
>  Some Linux distributions do not ship with the `lvm2` package. This package is required on all storage nodes in your k8s cluster to run Ceph OSDs.
```suggestion
Some Linux distributions do not ship with the `lvm2` package. This package is required on all storage nodes in the k8s cluster to run Ceph OSDs.
```

2023-04-27 02:30 UTC, sp98 commented on Documentation/Getting-Started/example-configurations.md
> +Configuration for Rook and Ceph can be configured in multiple ways to provide block devices, shared filesystem volumes or object storage in a kubernetes namespace. While several examples are provided
```suggestion
Configuration for Rook and Ceph can be configured in multiple ways to provide block devices, shared filesystem volumes or object storage in a kubernetes namespace. While several examples are provided to simplify storage setup, various settings will be needed to configure in order to optimize the production environment.
```

2023-04-27 02:32 UTC, sp98 commented
the docs-check CI seems to be complaining about the symlink location.

2023-04-27 13:26 UTC, travisn commented
> Few nits about `you` and `your` references. You can ignore them if they are not very relevant.

Great suggestions, I was getting tired staring at the docs for so long. This is going to take many separate PRs. :)

2023-04-27 16:00 UTC, galexrt commented on Documentation/Getting-Started/quickstart.md
> +  The [Rook Helm Chart](../Helm-Charts/operator-chart.md) is available to deploy the operator instead of creating the below manifests.
Please check locally using `make docs-preview` if two spaces was enough, these "hint blocks" might require four spaces

2023-04-27 17:56 UTC, travisn commented
> the docs-check CI seems to be complaining about the symlink location.

For now I'm going to revert those changes that symlink these docs, and consider how to structure the troubleshooting docs in a separate PR.

2023-04-27 18:12 UTC, galexrt approved these changes

2023-04-28 16:20 UTC, sp98 approved these changes

2023-04-28 16:26 UTC, merged