fix: typo in logs to print fullname of CephCluster
rook/rook pull request #12217
Opened 2023-05-10 01:37 UTC by takirala

**Description of your changes:**

Observed a log message that is incorrect as we print just the namespace instead of namespace and name when reconciling a CephCluster in the initial stages

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-05-10 14:41 UTC, travisn requested changes
Looks good to print the full namespaced name. Please just update the commit message according to the [dev guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#running-the-integration-tests). You could use the `core:` prefix (instead of `fix:`), and also add a brief commit description in addition to the commit title. Thanks!

2023-05-11 16:17 UTC, takirala commented
@travisn fixed now. Also, the canary integration tests are failing but my PR should not affect those i am hoping.

2023-05-11 17:04 UTC, travisn commented
Looks good, except we want to avoid the merge commits. See the [development guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#updating-your-fork) for a recommendation to rebase to remove the merge commit.

2023-06-08 05:21 UTC, travisn approved these changes

2023-06-08 05:21 UTC, merged