test: allow specifying custom nginx image for multus validation
rook/rook pull request #12231
Opened 2023-05-13 12:07 UTC by iPraveenParihar

**Description of your changes:**
- allow overriding the nginx server image for multus-validation-test-web-server from CLI using `--nginx-image` flag
- default image will be **nginx:stable-alpine**

**Which issue is resolved by this Pull Request:**
Resolves #12175 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-05-16 03:05 UTC, iPraveenParihar commented
Flags - 

![Screenshot from 2023-05-16 08-31-27](https://github.com/rook/rook/assets/30765265/283aa779-3db1-491f-98af-edc0fc7ab7ae)

usage - 
![Screenshot from 2023-05-16 08-33-46](https://github.com/rook/rook/assets/30765265/e7c7d25b-bbea-41e4-8716-450351388938)

2023-05-18 22:35 UTC, BlaineEXE requested changes
Thanks for these changes! We're really glad to see interest in the tool we have just started releasing. 

The changes are concise, and it catches most of the important corners where changes are needed. I'm requesting some changes largely for ensuring a clean codebase and a clear, succinct UI. 

The more important functional changes are verifying the input value is non-empty, and ensuring the image is used for both the web server and clients. We decided to use the same image for both for simplicity, because the image is small, and because the Nginx image is already set up with a non-root user.

2023-05-19 20:33 UTC, BlaineEXE requested changes
Please also squash all commits into one, and include a short paragraph in the commit body explaining what the commit does.

2023-05-19 20:40 UTC, BlaineEXE commented
Also, now that https://github.com/rook/rook/pull/12211 is merged, the image will also have to get set for the image-pull daemonset.

2023-05-20 04:48 UTC, iPraveenParihar commented on cmd/rook/userfacing/multus/validation/validation.go
> +	runCmd.Flags().StringVar(&validationConfig.NginxImage, "nginx-image", "nginx:stable-alpine",
Is this check necessary? Anyhow the command line won't allow empty value for `--nginx-image` flag

2023-05-20 13:11 UTC, iPraveenParihar commented on pkg/daemon/multus/templates.go
> +
Yes, tested it white spaces don't affect the result of unmarshalling.
I'll remove this function.

2023-05-24 18:54 UTC, BlaineEXE approved these changes

2023-05-24 18:55 UTC, BlaineEXE commented
Looks great! Thanks, @iPraveenParihar !

2023-05-24 18:55 UTC, merged