ci: fix minikube execution
rook/rook pull request #12316
Opened 2023-05-31 21:57 UTC by Javlopez

add docker to the pipeline to allow minikube able to use docker driver

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-05-31 22:17 UTC, travisn requested changes
Could you modify this PR temporarily to test if this fixes the issue? For example, trigger this job for the PR. After it's verified, then you can revert the temp change before we merge it.

2023-05-31 23:42 UTC, Javlopez commented
The fix is working 
![image](https://github.com/rook/rook/assets/638376/d4ef14f9-0593-44c1-8196-036816d609aa)

Just I gonna clean up the branch and organize my commits

2023-06-01 15:55 UTC, parth-gr approved these changes

2023-06-01 20:09 UTC, travisn approved these changes

2023-06-01 20:09 UTC, merged