doc: prevent to delete other clusters data on cluster deletion
rook/rook pull request #12334
Opened 2023-06-06 08:22 UTC by satoru-takeuchi

**Description of your changes:**

Current cluster teardown document assumes that there is only one Rook/Ceph cluster. If not, the instruction written in this document might delete the data of other clusters.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2023-06-07 10:25 UTC, satoru-takeuchi commented
@galexrt I hesitate to use `ceph device ls` here. This command shows kernel device names which might be changed after node restart. The worst scenario is as follows.

1. A user gets node:dev pairs from`ceph device ls`.
2. An node is restarted during teardown process and an osd's device name on this node is changed from sdb to sdc.
3. This user wipes sdb, it's an unrelated device, by mistske.

2023-06-07 13:52 UTC, travisn requested changes
Just a few small suggestions on the wording

2023-06-07 21:15 UTC, travisn commented on Documentation/Storage-Configuration/ceph-teardown.md
> +Connect to each machine and delete `/var/lib/rook/rook-ceph`, or the path specified by the `rook-ceph` directory under `dataDirHostPath`.
one more update, thanks ^

2023-06-07 22:32 UTC, satoru-takeuchi commented on Documentation/Storage-Configuration/ceph-teardown.md
> +Connect to each machine and delete `/var/lib/rook/rook-ceph`, or the path specified by the `rook-ceph` directory under `dataDirHostPath`.
Oops, sorry. I forgot to stage this change before commit.

2023-06-08 05:19 UTC, travisn approved these changes

2023-06-08 20:41 UTC, galexrt approved these changes

2023-06-08 20:42 UTC, galexrt commented
@satoru-takeuchi good point regarding the risks of `ceph device ls` thanks!

2023-06-08 20:42 UTC, merged