docs: remove the line generated by gen-crd-api-reference-docs
rook/rook pull request #12368
Opened 2023-06-13 02:03 UTC by Javlopez

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-06-13 16:42 UTC, galexrt commented on build/crds/generate-crd-docs.sh
> +     second_last_line=$(( lines-1 ))
Could we keep the dot in the file?

That it would end like this:
```
Generated with <code>gen-crd-api-reference-docs</code>.
</em></p>
```

2023-06-13 17:06 UTC, travisn requested changes
Please also add a commit description to describe why the change is needed

2023-06-14 14:33 UTC, galexrt approved these changes

2023-06-14 14:39 UTC, galexrt requested changes
Are we using this folder https://github.com/rook/rook/blob/master/Documentation/gen-crd-api-reference-docs/template/pkg.tpl#L46 for the templates? If so, why not just remove the commit from the template so there's no need to do any shell script "magic".

2023-06-14 17:37 UTC, galexrt approved these changes

2023-06-14 17:42 UTC, travisn approved these changes

2023-06-14 19:41 UTC, merged