Remove deprecated annotation
rook/rook pull request #12418
Opened 2023-06-22 21:33 UTC by Jeansen

**Description of your changes:**
Minor update in Documentation. The ingress dashboard example used an deprecated annotation.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-06-22 22:52 UTC, travisn commented
There are a couple more places to update this example as well:
- deploy/examples/dashboard-ingress-https.yaml
- deploy/charts/rook-ceph-cluster/values.yaml

Also, see the recommendation on [commit structure](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) so the Commitlint bot will be happy. A prefix of `docs:` will work.

Thanks!

2023-06-23 07:24 UTC, Jeansen commented
Hm...`deploy/charts/rook-ceph-cluster/values.yaml` looks fine to me.

2023-06-23 15:29 UTC, travisn requested changes
> Hm...`deploy/charts/rook-ceph-cluster/values.yaml` looks fine to me.

It's in a commented example [here](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L418), just not created by default.

> Also, see the recommendation on [commit structure](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) so the Commitlint bot will be happy. A prefix of docs: will work.

Instead of `doc:`, use `docs:`. Also as described in that link if you could add a brief description paragraph, thanks

2023-06-23 16:17 UTC, Jeansen commented
@travisn You are a rigid teacher! And yes,I know, I am lazy - by profession. I wonder why I've overseen the one occurrence in the comment. Actually I did a search for it ... I blame everyone else who distracted me ;-)
I hope now all is to your satisfaction?

2023-06-23 16:27 UTC, travisn commented
> @travisn You are a rigid teacher! And yes,I know, I am lazy - by profession. I wonder why I've overseen the one occurrence in the comment. Actually I did a search for it ... I blame everyone else who distracted me ;-) I hope now all is to your satisfaction?

Thanks for the entertainment, we are all distracted in some way. :) 

The commitlint bot is just a bit picky...

✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   subject may not end with full stop [subject-full-stop]

2023-06-29 14:38 UTC, travisn approved these changes

2023-06-29 14:38 UTC, merged