exporter: Ignore failed deletion of service monitor
rook/rook pull request #12430
Opened 2023-06-26 18:29 UTC by travisn

**Description of your changes:**
If the ceph version does not suppport the exporter, the operator will attempt to delete the service monitor related to the exporter to ensure it does not exist for a node. If the expected rbac does not exist, this will cause unnecessary errors since there would anyway be no service monitor to delete. So we ignore the error of deleting the service monitor for the exporter.

The context is also passed to the exporter so a new kubeconfig does not need to be initiated and cause unnecessary logging about invalid options for the config. The invalid context error was causing many of these errors in the log:
```
W0626 18:00:17.526858       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

**Which issue is resolved by this Pull Request:**
Resolves #12335

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-06-27 06:40 UTC, sp98 requested changes
nit

2023-06-27 06:40 UTC, sp98 commented on pkg/operator/k8sutil/prometheus.go
> +		// Either the service monitor does not exist or there are not privileges to detect it
```suggestion
		// Either the service monitor does not exist or there are no privileges to detect it
```

2023-06-27 10:13 UTC, avanthakkar approved these changes
LGTM!

2023-06-28 02:18 UTC, sp98 approved these changes

2023-06-28 14:20 UTC, merged