external: make black as default python formatter
rook/rook pull request #12505
Opened 2023-07-12 15:05 UTC by parth-gr

Closes: https://github.com/rook/rook/issues/11926

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-07-13 11:48 UTC, subhamkrai requested changes

2023-07-13 11:48 UTC, subhamkrai commented on .vscode/settings.json
> +    "editor.defaultFormatter": "ms-python.black-formatter"
```suggestion
    "editor.defaultFormatter": "ms-python.black-formatter"
    "editor.formatOnSave": true
```

2023-07-14 14:37 UTC, galexrt reviewed
Please add the black python formatter VSCode extension to the `.vscode/extensions.json` file so it is automatically recommended to VSCode users

2023-07-14 15:35 UTC, parth-gr commented on .vscode/settings.json
> +    "editor.defaultFormatter": "ms-python.black-formatter"
Added

2023-07-14 15:42 UTC, galexrt approved these changes

2023-07-17 07:49 UTC, subhamkrai approved these changes

2023-07-17 13:18 UTC, merged