helm: additional ServiceMonitor labels
rook/rook pull request #12605
Opened 2023-07-26 18:20 UTC by jouve

**Description of your changes:**
add a values in rook-ceph to add additional labels to the generated ServiceMonitor

**Which issue is resolved by this Pull Request:**
Resolves #12438

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-07-27 16:02 UTC, travisn requested changes
The changes look good, could you just add a [commit description](https://rook.github.io/docs/rook/v1.12/Contributing/development-flow/#commit-structure) to describe a bit more about the change?

2023-08-03 14:14 UTC, TheRealNoob commented
Thank you!

2023-08-03 14:52 UTC, jouve commented
I added the "Description of your changes" to the commit message

2023-08-03 17:58 UTC, travisn approved these changes

2023-08-03 17:58 UTC, merged