Rr/charts documentation refs
rook/rook pull request #12747
Opened 2023-08-17 12:57 UTC by rowanruseler

**Description of your changes:**
Noticed that since the release of 1.9, the values.yaml file has some
old documentation references. Replaced them with the new locations.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-08-17 13:03 UTC, rowanruseler commented
Sorry, I thought I would be able to add the label skip-ci.

2023-08-17 13:29 UTC, subhamkrai approved these changes

2023-08-17 13:45 UTC, parth-gr commented on deploy/charts/rook-ceph-cluster/values.yaml
> +#  reclaimPolicy: Delete
leave a extra line

2023-08-17 14:33 UTC, travisn requested changes
Thanks for fixing the links! Just one link change...

2023-08-17 14:33 UTC, travisn commented on deploy/charts/rook-ceph-cluster/values.yaml
> +      # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md#storageclass for available configuration
```suggestion
      # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md#storageclass for available configuration
```

2023-08-17 22:40 UTC, travisn reviewed
The links look good. Would you mind squashing the commits now?

2023-08-18 08:23 UTC, rowanruseler commented
> The links look good. Would you mind squashing the commits now?

Thanks, squashed them as requested.

2023-08-18 14:12 UTC, merged