Add port-name to GetServiceMonitor
rook/rook pull request #12825
Opened 2023-08-31 19:32 UTC by weirdwiz

This commit makes the port name configurable to set the port name of the service monitor. This will help keep the ports in the service and the service monitor consistent.

2023-08-31 20:48 UTC, travisn requested changes
A couple suggestions:
- Add a commit prefix as described in the [development guide](https://rook.github.io/docs/rook/v1.12/Contributing/development-flow/#commit-structure), such as `monitoring: `.
- The purpose of this change is to set the port name for the exporter, correct? Please describe the behavior change in the commit title or description. It's more important to say the behavior change in the commit message than to say what method it was in.

Thanks!

2023-09-01 06:23 UTC, subhamkrai requested changes
@weirdwiz please look at Travis comments

2023-09-01 07:23 UTC, avanthakkar approved these changes
Tested locally and exporter runs fine. LGTM!

2023-09-01 13:11 UTC, travisn approved these changes

2023-09-01 13:26 UTC, parth-gr commented on pkg/operator/ceph/cluster/mgr/mgr.go
> +	serviceMonitorPort     = "http-metrics"
How do we configure this by CR, can please tell me which specific CRD and in which component

2023-09-01 17:58 UTC, merged