core: import packages only once
rook/rook pull request #12909
Opened 2023-09-15 13:50 UTC by testwill

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-09-15 15:01 UTC, BlaineEXE approved these changes

2023-09-15 15:03 UTC, BlaineEXE commented
Looks good, but please edit the commit message to have a body. A sentence or two should be find here.

2023-09-15 16:22 UTC, parth-gr reviewed
Looks good!

You did it manually, or there is a tool that suggests us during development and integration

2023-09-15 16:33 UTC, travisn requested changes
Great to have this. I'm surprised goformat or other go tools don't check this. 

Please just update the commit message with a [description](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure), and the commit prefix is not in the accepted list. You can use `core:`.

2023-09-21 21:29 UTC, travisn approved these changes

2023-09-21 21:30 UTC, merged