This PR addresses issue #12660
rook/rook pull request #12983
Opened 2023-10-03 10:36 UTC by mashetty330

**Description of your changes:**

-   Add toleration to rook-ceph operator deployment
-   Toleration seconds is set to 5 seconds for immediate redeployment in-case of zone failures

**Which issue is resolved by this Pull Request:**
Resolves #12660

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-10-03 12:44 UTC, sp98 commented
@mashetty330 Please fix the commit lint CI
How was the local testing for this PR?

2023-10-04 16:24 UTC, travisn requested changes
The changes and the commit message look good now, we will just need to verify manually that this toleration has the desired effect since the CI doesn't test the failed nodes.

2023-10-04 16:26 UTC, travisn requested changes
One more request I missed, please add this toleration also for the helm chart in [deployment.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/deployment.yaml).

2023-10-05 10:23 UTC, mashetty330 commented
> One more request I missed, please add this toleration also for the helm chart in [deployment.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/deployment.yaml).

done

2023-10-05 10:24 UTC, mashetty330 commented
> The changes and the commit message look good now, we will just need to verify manually that this toleration has the desired effect since the CI doesn't test the failed nodes.

Ack. to verify this manually a single node cluster (like minikube) won't help right?

2023-10-05 18:00 UTC, travisn commented
> > The changes and the commit message look good now, we will just need to verify manually that this toleration has the desired effect since the CI doesn't test the failed nodes.
> 
> Ack. to verify this manually a single node cluster (like minikube) won't help right?

Right, we will need a multi-node cluster to verify. Perhaps something like this: 
1. Start a multi-node cluster
2. kubectl -f crds.yaml -f common.yaml -f operator.yaml
3. See the operator pod is running
4. Take the node offline where the operator is running, so the node becomes unreachable
5. Verify that the operator pod fails over to a new pod in a few seconds from the node being marked unreachable.

2023-11-07 04:51 UTC, travisn commented
@mashetty330 Any luck verifying this fix on a multi-node cluster?

2023-12-04 18:09 UTC, travisn approved these changes
LGTM, I verified locally.

2023-12-04 18:09 UTC, merged