docs: fix install command
rook/rook pull request #13066
Opened 2023-10-19 05:44 UTC by jxlwqq

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2023-10-19 13:01 UTC, subhamkrai requested changes
Please sign off your commit, DCO bot is failing

2023-10-19 14:53 UTC, travisn commented
Yes, thanks for catching this. Please just see the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) for the commit structure. Even with a simple change like this, a PR and commit description is needed, thanks!

2023-10-20 07:46 UTC, subhamkrai commented
@jxlwqq ptal ^^

> Yes, thanks for catching this. Please just see the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) for the commit structure. Even with a simple change like this, a PR and commit description is needed, thanks!

2023-10-24 20:59 UTC, travisn approved these changes

2023-10-24 21:00 UTC, merged