build: use /usr/bin/env to look up script interpreters
rook/rook pull request #13230
Opened 2023-11-17 15:26 UTC by galexrt

**Which issue is resolved by this Pull Request:**

For users that have their `/bin/bash` at a "abnormal" place (e.g., NixOS) this makes the scripts and shell vars use `/usr/bin/env` to find the "right" one.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2023-11-20 21:10 UTC, BlaineEXE approved these changes

2023-11-21 11:45 UTC, galexrt commented
I have updated a python script shebang that I missed with my latest changes.

@BlaineEXE @travisn If one of you is on a Mac, do the everyday tasks (e.g., `make crds`) work fine for you with these changes? `/usr/bin/env` and it's `-S` should be available on "any system that has the env" command, but I want to make sure that we don't run into a similar issue as we had with GNU vs BSD `sed` command. :sweat_smile:

2023-11-21 12:58 UTC, obnoxxx requested changes
The change itself looks good to me, But I'd suggest to not restrict the description in the PR title and the commit message to just "bash" but extend to something like "script interpreters" or "commands". After all, the patch touches bash and python3. 

It could be extended to cover SHA256CMD in `Makefile`.  Just a thought.

2023-11-21 16:00 UTC, obnoxxx approved these changes
Thanks for updating the title and commit message, @galexrt .

LGTM

2023-11-21 16:07 UTC, merged