[WIP] dev: improving the handling of arguments within the script
rook/rook pull request #13532
Opened 2024-01-08 14:08 UTC by rkachach

So far all the arguments were being handled as separate getopts flags introducing a lot of boilerplate code for every new flag. The new approach improves the arguments handling by using env variables.

This is a followup PR to address the improvements proposed on https://github.com/rook/rook/pull/13298#pullrequestreview-1768437705

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-01-12 05:49 UTC, sp98 requested changes
nit

2024-01-12 05:49 UTC, sp98 commented on tests/scripts/create-dev-cluster.sh
> +export ROOK_EXAMPLES_DIR="${EXAMPLES_DIR:=deploy/examples}" ## Path to Rook examples directory (i.e github.com/rook/rook/deploy/examples)
just for consistency..

```suggestion
export ROOK_EXAMPLES_DIR="${ROOK_EXAMPLES_DIR:=deploy/examples}" ## Path to Rook examples directory (i.e github.com/rook/rook/deploy/examples)
```

2024-01-12 10:48 UTC, rkachach commented on tests/scripts/create-dev-cluster.sh
> +export ROOK_EXAMPLES_DIR="${EXAMPLES_DIR:=deploy/examples}" ## Path to Rook examples directory (i.e github.com/rook/rook/deploy/examples)
fixed

2024-01-24 16:02 UTC, BlaineEXE approved these changes

2024-01-25 07:42 UTC, sp98 approved these changes

2024-01-25 07:44 UTC, merged

2024-01-25 13:22 UTC, parth-gr commented on tests/scripts/create-dev-cluster.sh
> -	    rook_operator_ns="$OPTARG"
we cant customise namesapce now?