osd: correct counting the devices when metadataDevice is set
rook/rook pull request #13673
Opened 2024-02-02 07:53 UTC by satoru-takeuchi

The validation logic of checking the number of devices is wrong when `metadataDevice` is set and `osdsPerDevice` > 1. `len(cvReports)` is the expected number of OSDs and is the number of specified data devices multiplied by `osdsPerDevice`.

**Issue resolved by this Pull Request:**
Resolves #13637

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2024-02-05 06:29 UTC, sp98 requested changes
Nit. 
Rest looks good.

2024-02-05 06:29 UTC, sp98 commented on pkg/daemon/ceph/osd/volume_test.go
> +
```suggestion
```

2024-02-06 04:10 UTC, sp98 approved these changes

2024-02-06 21:36 UTC, travisn commented
@satoru-takeuchi please just rebase one more time to pick up all the CI fixes

2024-02-07 01:21 UTC, merged