Remove '= ' in import-external-cluster.sh preventing script from importing external cephfs cluster correctly
rook/rook pull request #13780
Opened 2024-02-15 18:12 UTC by timolow

Remove '=' preventing import script from finishing. 

**Issue resolved by this Pull Request:**
Resolves  https://github.com/rook/rook/issues/13679

2024-02-15 19:25 UTC, travisn requested changes
The change looks good, please just see the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) for the needed commit prefix and description, thanks

2024-02-15 22:52 UTC, travisn commented
@timolow It's not the PR title, it's the commit title and description that is needed. Please see the developer guide previously linked.

2024-02-16 13:55 UTC, parth-gr approved these changes
lgtm

2024-02-16 16:22 UTC, timolow commented
> @timolow It's not the PR title, it's the commit title and description that is needed. Please see the developer guide previously linked.

Fixed up the commit issue.

2024-02-16 18:22 UTC, travisn approved these changes
Thanks!

2024-02-16 18:22 UTC, merged