helm: sync the ceph-csi-cephfs clusterroles with ceph-csi
rook/rook pull request #14199
Opened 2024-05-14 11:22 UTC by NymanRobin

The clusterroles permissions of ceph-csi-cephfs nodeplugin and provisioner were not in sync with ceph-csi

The changes to ceph-csi was done in this PR: https://github.com/ceph/ceph-csi/pull/4504

This changes fixes: #14035

2024-05-14 11:56 UTC, parth-gr reviewed
Should we also document how to use `CephFS + fscrypt`?

2024-05-14 12:32 UTC, NymanRobin commented
Yes, ideally, @parth-gr, but currently, I don't have an official ISO image that supports kernel 6.6 and works with Minikube for development purposes. However, if it's acceptable to leave the kernel-related details to the reader, I can proceed with documenting the process and create some deployment examples.

2024-05-14 12:33 UTC, parth-gr commented
> Yes, ideally, @parth-gr, but currently, I don't have an official ISO image that supports kernel 6.6 and works with Minikube for development purposes. However, if it's acceptable to leave the kernel-related details to the reader, I can proceed with documenting the process and create some deployment examples.

lets wait for there ideas @travisn @iamniting

2024-05-14 13:27 UTC, iamniting requested changes
While talking to @Rakshith-R I got to know we also need the below permissions in both the clusterroles

```
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
```

2024-05-14 17:22 UTC, NymanRobin commented
> While talking to @Rakshith-R I got to know we also need the below permissions in both the clusterroles
> 
> ```
>   - apiGroups: [""]
>     resources: ["serviceaccounts"]
>     verbs: ["get"]
>   - apiGroups: [""]
>     resources: ["serviceaccounts/token"]
>     verbs: ["create"]
> ```

Thanks for pointing it out, I had only used it with a secret directly and thus I missed this detail!
The PR is updated now! What does everyone think should this PR include some documentation for the cephfs + fscrypt feature or should we target that for another PR?

2024-05-14 21:27 UTC, travisn reviewed
This has expanded to more than helm. How about the commit prefix `manifest:`, and also more description in the commit message for the privileges being added?

2024-05-15 04:17 UTC, iamniting reviewed
The changes looks good to me, I leave the other decisions to Travis.

2024-05-15 07:34 UTC, NymanRobin commented
Thanks @travisn for pointing out that commit message was not descriptive, sorry for that! 

Also managed to close the PR once while updating it :sweat_smile: 
Now the commit message should be more descriptive of what privileges are added and what is the reason behind them

2024-05-15 12:52 UTC, parth-gr commented
> Should we also document how to use `CephFS + fscrypt`?

we should have the feature documented IMO, with this PR or a follow up never mind

2024-05-15 17:43 UTC, travisn commented
LGTM, @Rakshith-R please also review

2024-05-16 06:35 UTC, Rakshith-R approved these changes
Thanks, 
It looks good to me.

2024-05-16 06:57 UTC, Madhu-1 reviewed
If the target is only to update RBAC the changes looks good but for complete implementation, As per we are enabling a Key `CSI_ENABLE_ENCRYPTION` in the configmap https://rook.io/docs/rook/latest-release/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/?h=encryption#enable-rbd-encryption-support, when this key is set we need to mount configmap to the cephfs as well like we do for rbd which is missing in this PR.

2024-05-16 11:53 UTC, NymanRobin commented
I see your point @Madhu-1, I did not initially considered it in this PR as it is outside of the scope of the issue I submitted.

However, I am not opposed to extending the scope of this PR as it probably would make most sense to finish it all at once, depending on what others who have partaken in the conversation think? I should be able to extend this PR in reasonable time
I also see from the link that the rbd case just have a note for the kernel version so I think we can simply do the same for cephfs case

I found the rbd PR #9940 for reference

2024-05-20 11:05 UTC, NymanRobin commented
I have updated the pull request to include the mounting of the ConfigMap and the relevant documentation.
I extended the existing documentation since this feature utilizes the same parameter and ConfigMap. @Madhu-1, please review these changes and let me know if you have any concerns or suggestions.

2024-05-20 11:09 UTC, parth-gr approved these changes

2024-06-11 13:56 UTC, iamniting approved these changes

2024-06-11 19:50 UTC, travisn commented
@Madhu-1 Any more feedback on this?

2024-06-18 14:28 UTC, Madhu-1 approved these changes

2024-06-18 14:29 UTC, Madhu-1 commented
> @Madhu-1 Any more feedback on this?

@travisn @NymanRobin sorry i missed the pings on this PR.

2024-07-01 21:27 UTC, merged