mds: block of active mds ip only
rook/rook pull request #14258
Opened 2024-05-23 12:53 UTC by subhamkrai

Revert "csi: remove cephFs networkFence code temporarily"

mds: block of active mds ip only

currently, it was blocking both the mds ip
instead its should block ip of of mds which is in
the same node which is down.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-05-27 06:47 UTC, subhamkrai commented
@mergifyio rebase

2024-07-15 02:28 UTC, subhamkrai commented
All the testing has been done and it's working as expected. Ready to merge after @Madhu-1 approval

2024-07-15 10:01 UTC, Madhu-1 requested changes

2024-07-16 11:08 UTC, subhamkrai commented on pkg/operator/ceph/cluster/watcher.go
> +				watcherIPlist = append(watcherIPlist, watcherIP)
as in networkFence we are passing it as list in `networkFence CR CIDR field` for list of watcherIPs and cephFS uses same function so passing it as list. 

btw I'm not the original contributor to this part of code but I'm sharing my understanding

2024-07-16 11:09 UTC, subhamkrai commented on pkg/operator/ceph/cluster/watcher.go
> +		return pkgerror.Wrapf(err, "failed to create network fence for node %q", node.Name)
having `node.Name`  that's why `Wrapf`

2024-07-17 05:24 UTC, subhamkrai commented on pkg/operator/ceph/cluster/watcher.go
> +		if pv.Spec.CSI.Driver == fmt.Sprintf("%s.cephfs.csi.ceph.com", cluster.Namespace) {
right @Madhu-1 it will be operator namespace only

2024-07-17 05:24 UTC, subhamkrai commented on pkg/operator/ceph/cluster/watcher.go
> +		if len(splitVolumeInUseBased) == 2 && splitVolumeInUseBased[0] == fmt.Sprintf("%s.cephfs.csi.ceph.com", cluster.Namespace) {
right @Madhu-1 it will be operator namespace only

2024-07-17 07:24 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +		logger.Infof("node %q require fencing, found cephfs volumes in use", node.Name)
change volume to subvolume

2024-07-17 07:24 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +			err = c.fenceCephFSVolume(ctx, node, cluster, clusterInfo, cephFSPVList[i])
change volume to subvolume

2024-07-17 07:24 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +			// We only need to create the network fence for any one of cephFS pv.
change volume to subvolume

2024-07-17 07:24 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +			// continue to fence next cephfs volume if active client not found
change volume to subvolume

2024-07-17 07:24 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +				watcherIPlist = append(watcherIPlist, watcherIP)
break/return once you find the required ip

2024-07-17 07:33 UTC, subhamkrai commented on pkg/operator/ceph/cluster/watcher.go
> +		logger.Infof("node %q require fencing, found cephfs volumes in use", node.Name)
done

2024-07-17 07:35 UTC, Madhu-1 approved these changes

2024-07-17 07:35 UTC, Madhu-1 commented on pkg/operator/ceph/cluster/watcher.go
> +			logger.Errorf("failed to fence cephfs subvolumes %q, trying next cephfs subvolume", cephFSPVList[i].Name)
`cephfs subvolumes` to `cephfs subvolume`

2024-07-17 08:07 UTC, Madhu-1 approved these changes

2024-07-17 15:41 UTC, parth-gr approved these changes

2024-07-17 17:48 UTC, merged