build: fix go mod checksum mismatch error
rook/rook pull request #14283
Opened 2024-05-30 12:26 UTC by obnoxxx

The build was failing locally for me with a go module checksum mismatch error:

```console
verifying github.com/portworx/sched-ops@v0.20.4-openstorage-rc3: checksum mismatch
	downloaded: h1:46EZ+vYCJ3qmQolvgDCrGuPz8Tf0vIds41RuF0dqVEw=
	go.sum:     h1:tXnHsjZT2wZ2BCXf8avDoya7zGyCgLNUC8Upt+WEQrY=
``

The last change to go.sum related to this module was from PR #13852

This change to go.sum fixes the issue for me.

It is the result of the following commands:

````console
rm go.sum
go mod tidy
``

  1. Add a description of the changes (frequently the same as the commit description)
  2. Enter the issue number next to "Resolves #" below (if there is no tracking issue resolved, **remove that section**)
  3. Review our Contributing documentation at https://rook.io/docs/rook/latest/Contributing/development-flow/
  4. Follow the steps in the checklist below, starting with the **Commit Message Formatting**.

**Issue resolved by this Pull Request:**
Resolves #14282 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-05-30 13:28 UTC, BlaineEXE requested changes
@obnoxxx these changes are causing all builds to fail, so I don't think we can accept them into source.

I'm not really sure why your environment is showing this issue. It seems telling me that none of the other devs are reporting this issue. Similarly, running `make build` in my env doesn't result in this change.

I'd like to understand what part of the make tooling is resulting in this change. There maybe some issue we need to resolve. 

Could you reset your repo to the latest master, then run `make build` and report whether this file changes?

2024-05-30 13:59 UTC, obnoxxx commented
@BlaineEXE  wrote: 
> @obnoxxx these changes are causing all builds to fail, so I don't think we can accept them into source.
> 
> I'm not really sure why your environment is showing this issue. It seems telling me that none of the other devs are reporting this issue. Similarly, running `make build` in my env doesn't result in this change.
> 
> I'd like to understand what part of the make tooling is resulting in this change. There maybe some issue we need to resolve.

good point. I can try to dig deeper to understand better.


> 
> Could you reset your repo to the latest master, then run `make build` and report whether this file changes?

`make build`does not modify `go.sum`but it fails:

```console
$git fetch origin
$git reset --hard origin/master
$ make clean
$ make -j build
 ...
downloading k8s.io/component-base v0.29.3
verifying github.com/portworx/sched-ops@v0.20.4-openstorage-rc3: checksum mismatch
	downloaded: h1:46EZ+vYCJ3qmQolvgDCrGuPz8Tf0vIds41RuF0dqVEw=
	go.sum:     h1:tXnHsjZT2wZ2BCXf8avDoya7zGyCgLNUC8Upt+WEQrY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [build/makelib/golang.mk:179: go.mod.check] Error 1
$ git diff --quiet && echo NO diff 
NO diff
$ 
```

2024-05-30 14:28 UTC, BlaineEXE commented
I wonder if there is some local file present that's causing problems. I have encountered something like this a few times over the years.

This is what I usually try:
```
cd ..
mv rook/ rook-old/
git clone https://github.com/rook/rook
cd rook
make build
```

2024-05-30 16:39 UTC, obnoxxx commented
@BlaineEXE  wrote:

> I wonder if there is some local file present that's causing problems.

quite possible.


>  I have encountered something like this a few times over the years.
> 
> This is what I usually try:
> 
> ```
> cd ..
> mv rook/ rook-old/
> git clone https://github.com/rook/rook
> cd rook
> make build
> ```

I just tried this and it immediately fails with the checksum mismatch error.

So it does not seem to be due to a  local file in my old checkout.

2024-06-04 17:33 UTC, obnoxxx commented
closing the PR as it can not be accepted into the tree in this form. But leaving the issue #14282  open because I am still seeing it even though I seem to be the only one right now ...

2024-06-04 17:33 UTC, closed without merging