external: add final args used to the upgrade configmap
rook/rook pull request #14407
Opened 2024-07-02 14:59 UTC by parth-gr

Recently we have introuced external-cluster-user-command cm Which help user to look at the previous command run, So with this PR we will add another data field arg on this confimap which will have the final processed flags that are being used
So user can use them directly either in config.ini or cmd line args

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-02 19:24 UTC, travisn requested changes
Is there documentation to update so the user is aware of how to find these params to use with the config file?

2024-07-03 08:32 UTC, parth-gr commented
> Is there documentation to update so the user is aware of how to find these params to use with the config file?

Yes we have a separate PR for this https://github.com/rook/rook/pull/14382

2024-07-03 14:41 UTC, parth-gr commented
Testing:
```
sh-5.1$ python3 a.py --rbd-data-pool-name ocs-storagecluster-cephblockpool --format bash
export EXTERNAL_CLUSTER_USER_COMMAND="--rbd-data-pool-name ocs-storagecluster-cephblockpool --format bash"
export ARGS="['verbose: False', 'rgw-pool-prefix: default', 'restricted-auth-permission: False', 'v2-port-enable: False', 'format: bash', 'cephfs-filesystem-name: ocs-storagecluster-cephfilesystem', 'cephfs-metadata-pool-name: ocs-storagecluster-cephfilesystem-metadata', 'cephfs-data-pool-name: ocs-storagecluster-cephfilesystem-data0', 'rbd-data-pool-name: ocs-storagecluster-cephblockpool', 'rgw-skip-tls: False', 'skip-monitoring-endpoint: False', 'dry-run: False', 'upgrade: False']"
export ROOK_EXTERNAL_FSID=a85f49da-9d9d-4f72-bb54-430508d22a80
export ROOK_EXTERNAL_USERNAME=client.healthchecker
export ROOK_EXTERNAL_CEPH_MON_DATA=a=172.30.142.195:3300
export ROOK_EXTERNAL_USER_SECRET=AQDbWYVm+XQ5DRAAV0tAEvAEgExiako67tzzvQ==
export CSI_RBD_NODE_SECRET=AQBB84Rm0/M3GBAAVwDpMCj41n5OEey4mx4kxg==
export CSI_RBD_NODE_SECRET_NAME=csi-rbd-node
export CSI_RBD_PROVISIONER_SECRET=AQBB84Rm0JBhCRAAjkjYdQoGvYqpOm2cNzFrIQ==
export CSI_RBD_PROVISIONER_SECRET_NAME=csi-rbd-provisioner
export CEPHFS_POOL_NAME=ocs-storagecluster-cephfilesystem-data0
export CEPHFS_METADATA_POOL_NAME=ocs-storagecluster-cephfilesystem-metadata
export CEPHFS_FS_NAME=ocs-storagecluster-cephfilesystem
export CSI_CEPHFS_NODE_SECRET=AQBB84Rm55kQOxAAZD8DWauEWdyfqpIdfhAChQ==
export CSI_CEPHFS_PROVISIONER_SECRET=AQBB84Rmj3ekKBAALb8JdpcOMcCt9+SMw+kZjQ==
export CSI_CEPHFS_NODE_SECRET_NAME=csi-cephfs-node
export CSI_CEPHFS_PROVISIONER_SECRET_NAME=csi-cephfs-provisioner
export MONITORING_ENDPOINT=10.128.2.72
export MONITORING_ENDPOINT_PORT=9283
export RBD_POOL_NAME=ocs-storagecluster-cephblockpool
export RGW_POOL_PREFIX=default

```

Configmap:

```
[rider@localhost examples]$ kubectl get cm rook-ceph-mon-endpoints -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"openshift-storage","monitors":["172.30.116.159:3300","172.30.142.195:3300","172.30.72.104:3300"],"cephFS":{"netNamespaceFilePath":"","subvolumeGroup":"","kernelMountOptions":"","fuseMountOptions":""},"rbd":{"netNamespaceFilePath":"","radosNamespace":""},"nfs":{"netNamespaceFilePath":""},"readAffinity":{"enabled":false,"crushLocationLabels":null},"namespace":""}]'
  data: c=172.30.116.159:3300,a=172.30.142.195:3300,b=172.30.72.104:3300
  mapping: '{"node":{"a":null,"b":null,"c":null}}'
  maxMonId: "2"
  outOfQuorum: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-03T06:42:20Z"
  finalizers:
  - ceph.rook.io/disaster-protection
  name: rook-ceph-mon-endpoints
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: ocs-storagecluster-cephcluster
    uid: 9e719c33-c948-419f-acbe-6a3047806fcd
  resourceVersion: "425815"
  uid: 4654a730-bf6b-494f-89eb-132d72b0cd53

```

2024-07-03 15:15 UTC, parth-gr commented on deploy/examples/import-external-cluster.sh
> +      -p "'{\"data\":{\"command\":\"$EXTERNAL_CLUSTER_USER_COMMAND\"}}'"
not sure whats issue with this

2024-07-03 16:21 UTC, parth-gr commented on deploy/examples/import-external-cluster.sh
> +      -p "'{\"data\":{\"command\":\"$EXTERNAL_CLUSTER_USER_COMMAND\"}}'"
Resolved

2024-07-03 16:21 UTC, parth-gr commented
@travisn ready for final review

2024-07-03 17:29 UTC, travisn approved these changes

2024-07-03 17:29 UTC, merged