object: rm unnecessary bucket quota setting in bucket.Provision()
rook/rook pull request #14882
Opened 2024-10-21 22:30 UTC by jhoblitt

It appears the user quota is set after the bucket is created and then immediately unset by bucket.setAdditionalSettings(). The logic also partially duplicates bucket.setUserQuota(). A default limit of a single bucket could be achieved by assuming `maxBuckets` is `1`, if the value is no explicitly set. However, that would be a visible change in behavior as users for buckets which do not currently have a bucket quota set would acquire a bucket quota.

Testing to with 1.15.3 to investigate the current behavior. Using this OBC:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test3
provisioner: rook-ceph.ceph.rook.io/bucket
parameters:
  objectStoreName: lfa
  objectStoreNamespace: rook-ceph
reclaimPolicy: Retain
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: test3
  namespace: rook-ceph
spec:
  bucketName: test3
  storageClassName: test3
```

Results in the operator logging the initial bucket quota being set:

```
2024-10-21 22:09:31.009505 I | op-bucket-prov: set user "obc-rook-ceph-test4-6523feb9-6938-46c3-8c86-9443deb4299c" bucket max to 1
```

The change to the bucket quota is not logged after that. However, when inspecting the generated rgw user, there is no bucket quota set:

```
bash-5.1$ radosgw-admin user info --uid=obc-rook-ceph-test4-6523feb9-6938-46c3-8c86-9443deb4299c
{
    "user_id": "obc-rook-ceph-test4-6523feb9-6938-46c3-8c86-9443deb4299c",
    "display_name": "obc-rook-ceph-test4-6523feb9-6938-46c3-8c86-9443deb4299c",
    "email": "",
    "suspended": 0,
    "max_buckets": 1,
    "subusers": [],
    "keys": [
        {
            "user": "obc-rook-ceph-test4-6523feb9-6938-46c3-8c86-9443deb4299c",
            "access_key": "M43S1EH3I05S6D45VPRQ",
            "secret_key": "SLOOXDCy3YqhnNeemS7ijOLIQhCZcVBI2NAAB9bJ"
        }
    ],
    "swift_keys": [],
    "caps": [],
    "op_mask": "read, write, delete",
    "default_placement": "",
    "default_storage_class": "",
    "placement_tags": [],
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "user_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "temp_url_keys": [],
    "type": "rgw",
    "mfa_ids": []
}
```

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-10-22 16:51 UTC, jhoblitt commented
I think the same issue is present in `bucket.Grant()`.

2024-10-22 19:37 UTC, BlaineEXE requested changes
My understanding is that this code sets the `MaxBuckets` quota for users to ensure that S3 users aren't allowed to create their own buckets, circumventing the OBC controls. I don't think this can be removed.

`MaxBuckets` should always be defined as 1 for all users of OBC-created buckets, or 0 for all granted (brownfield) OBC buckets.

2024-10-22 19:39 UTC, jhoblitt commented
> My understanding is that this code sets the `MaxBuckets` quota for users to ensure that S3 users aren't allowed to create their own buckets, circumventing the OBC controls. I don't think this can be removed.
> 
> `MaxBuckets` should always be defined as 1 for all users of OBC-created buckets, or 0 for all granted (brownfield) OBC buckets.
I believe that was the intent but that isn't what happens now.  The user bucket quota is set and then immediately unset when the bucket is provisioned.  I tested this with several live rook deployments.

2024-10-22 19:42 UTC, jhoblitt commented
To be pedantic, the generated users effectively no bucket quota set without this PR.  The intent of this PR is cleanup of an admin API call which we doesn't need to happen to maintain the currently user visible behavior.

This is arguably a bug but one which I'm fearful of fixing because it is possible users are depending upon the current behavior.

2024-10-22 20:18 UTC, BlaineEXE commented
> This is arguably a bug but one which I'm fearful of fixing because it is possible users are depending upon the current behavior.

A fair point. @travisn thoughts?

2024-10-22 21:44 UTC, travisn commented
So the quota feature is essentially broken, right? So the worry is that if we fix it to enable the quota, users might be broken? Or maybe I'm missing some other side effect of the incorrect behavior. 

This at least seems reasonable for a minor release (1.16) and include it in the release notes, or even in 1.15.x if we're clear in the release notes?

2024-10-22 21:53 UTC, BlaineEXE commented
The OBC controller was originally implemented without quota support. It had one quota enabled at that time, the `MaxBuckets` quota, which was used to ensure OBC users couldn't use the S3 API to create new buckets for themselves.

At some point, quota support was added (or modified). At that point, the quota controller overwrote the `MaxBuckets` quota from before, effectively disabling it if I understand correctly.

While there may be some users who are relying on the ability to have OBC users create their own buckets, this was never intended and was for some time disallowed. After thinking about this some more, I would propose to resolve the bug in such a way that the original `MaxBuckets` behavior is restored. I believe some users would consider it a bug that OBC users have elevated permissions.

2024-10-22 21:58 UTC, jhoblitt commented
> So the quota feature is essentially broken, right? So the worry is that if we fix it to enable the quota, users might be broken? Or maybe I'm missing some other side effect of the incorrect behavior.

I believe the intent was that when creating an rgw user for an obc, that user would have a quota limit of 1 bucket to prevent the credentials from being used to create additional buckets.  That effectively isn't working because the `obc.spec.additionalConfig["maxBuckets"]` support is immediately unsettling that quota, unless `maxBuckets` is set. I don't have first hand knowledge if the default user bucket quota has ever been working.  From a quick inspection of the repo history, I suspect the current behavior has been in place for several years, perhaps since 2021 from 90bea8a560355b829a257b5e1b0b44349c22f864 ?

From my perspective, these API calls are functionally dead code that need to be addressed as part of other features I'm working on.

2024-10-23 16:50 UTC, BlaineEXE commented
Even if it's functionally dead, I don't think the appropriate step here is to remove it. The code does attempt to set up a critical permission control, and the existence of the code records that intent. I'd suggest that the proper fix will be to either adjust the `setAdditionalSettings()` such that it leaves `MaxBuckets` as-is. Alternately, if it makes sense across all instances of `setAdditionalSettings()`, it could take an argument that tells it what `MaxBuckets` should be.

2024-10-23 16:55 UTC, jhoblitt commented
Speaking as an operator, I would consider a change in behavior after 3 years a breaking change that under semver should come with a major version bump.  Per Hyrum's Law, if a bug is around long enough it becomes a feature.

2024-10-23 16:57 UTC, jhoblitt commented
To be clear, I have no objection to Rook making a major version bump.

2025-02-03 20:02 UTC, closed without merging