test: specify ceph image correctly
rook/rook pull request #14910
Opened 2024-10-25 11:54 UTC by satoru-takeuchi

`encryption-pvc-kms-ibm-kp` workflow replaces the name of ceph-image. Since the dest value is always empty by mistake, this workflow always fails.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

2024-10-25 13:43 UTC, travisn requested changes
This looks related to #14872 which was backported to 1.15, so no need to backport to 1.14. 

The test is being skipped now, not sure why. @jhoblitt Could you take a look? Thanks!

2024-10-25 18:20 UTC, jhoblitt commented
@travisn I realize I mentioned this was a problem on slack a couple of days ago and hadn't opened a PR yet.  :frowning_face:  #opslife 

`TestCephMgrSuite` is coming from its own workflow file and wasn't modified by https://github.com/rook/rook/pull/14872.  It looks like it has been skipped for > 6 months??? https://github.com/rook/rook/actions/workflows/integration-test-mgr-suite.yaml?page=100

2024-10-25 18:56 UTC, travisn commented
> @travisn I realize I mentioned this was a problem on slack a couple of days ago and hadn't opened a PR yet. ☹️ #opslife
> 
> `TestCephMgrSuite` is coming from its own workflow file and wasn't modified by #14872. It looks like it has been skipped for > 6 months??? https://github.com/rook/rook/actions/workflows/integration-test-mgr-suite.yaml?page=100

Actually we can continue skipping that mgr suite, the test in question is just `encryption-pvc-kms-ibm-kp`. The test loads, but then it skips the main "run encryption KMS IBM Key Protect" step.

2024-10-28 04:52 UTC, satoru-takeuchi commented
@travisn Although you left "requests changes", there was no comment. Did you select change request by mistake? If else, please let me know the appropriate fix.

`encryption-pvc-kms-ibm-kp` has been skipped for a long time. However, it has been ran in v1.15 branch. So I guess at least this change is necessary for v1.15 branch.

2024-10-28 18:59 UTC, travisn commented
> @travisn Although you left "requests changes", there was no comment. Did you select change request by mistake? If else, please let me know the appropriate fix.
> 
> `encryption-pvc-kms-ibm-kp` has been skipped for a long time. However, it has been ran in v1.15 branch. So I guess at least this change is necessary for v1.15 branch.

Ok thank you for the reminder, LGTM. I was looking at the daily CI for the canary tests where it runs, but you are correct that in PRs this test has been skipped for a long time. Merging now to see if the daily CI will pass this test...

2024-10-28 18:59 UTC, travisn approved these changes

2024-10-28 18:59 UTC, merged