docs: add documentation for rbd volumegroupsnapshot
rook/rook pull request #15002
Opened 2024-11-14 06:54 UTC by black-dragon74

This PR adds the sample YAMLs and documentation
for the RBD VolumeGroupSnapshot.

Signed-off-by: Niraj Yadav <niryadav@redhat.com>
(cherry picked from commit 524b6071d2dd17fcdf7ee587ba1b43feaa4dfa1e)

See: https://github.com/rook/rook/pull/14845#issuecomment-2422691070 for more.

2024-11-14 06:54 UTC, black-dragon74 commented
/cc: @nixpanic @travisn

2024-11-14 09:02 UTC, nixpanic commented
Currently Ceph-CSI supports VolumeGroupSnapshot, but the Ceph base image does not yet. Users (or products) may build their own Ceph-CSI container-image based on the Ceph main branch (CI image) and get the functionality.

At the moment, this PR does not have a high priority, I think. It may confuse users that expect VolumeGroupSnapshot to work right out of the box, but that is not the case yet.

2024-11-15 03:19 UTC, travisn requested changes
Let's just put a hold on merging this until there is a ceph release available to support the feature, thanks.

2024-12-06 18:24 UTC, BlaineEXE commented
Depends on #13832 ?

2024-12-06 18:28 UTC, BlaineEXE commented
Depends on #15037 ?

2024-12-09 11:45 UTC, Madhu-1 commented
@BlaineEXE This depends on the ceph release, the current ceph release doesn't have this new feature.

2025-03-01 20:01 UTC, closed without merging