docs: update Ceph Block Pool CRD reference
rook/rook pull request #15033
Opened 2024-11-20 12:54 UTC by emmanuel-ferdman

# PR Summary
Commit 74431443e31eec775a8a89a4228edb78d6cff51e renamed `Documentation/ceph-pool-crd.md` to be `Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md`. This PR updates all references to reflect this change, removes unused links, and fixes extra parentheses in links that previously caused them not to render correctly.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-11-20 17:35 UTC, travisn requested changes
LGTM, I'd just suggest to squash to a single commit.

2024-11-20 18:10 UTC, emmanuel-ferdman commented
@travisn thank you for the review, can you do it on the merge button while selecting "squash"?

2024-11-20 18:17 UTC, travisn commented
> @travisn thank you for the review, can you do it on the merge button while selecting "squash" here in this PR Github page?

Unfortunately the commit history is not formatted as well in that case. We do have instructions [here](https://rook.io/docs/rook/latest-release/Contributing/development-flow/#commit-history) to help with the squash, if you wouldn't mind. Also, a note on the expected [commit structure](https://rook.io/docs/rook/latest-release/Contributing/development-flow/#commit-structure). Thanks

2024-11-21 12:53 UTC, emmanuel-ferdman commented
@travisn got it, squashed the commits and the PR is ready now 😄

2024-11-21 15:02 UTC, travisn approved these changes

2024-11-21 15:02 UTC, merged