Fix codegen again
rook/rook pull request #15076
Opened 2024-11-29 17:24 UTC by obnoxxx

**Description of changes:**

PR #14883  fixed the codegen workflow by copying the git checkout directory to the
    correct location.
    
    Recent work indicates that the copying might not be necessary after all:
https://github.com/rook/rook/pull/14984#discussion_r1837067263

    
    This change aims to fix the codegen workflow again by reverting the changes of #14883  and
using proper workflow yaml settings instead.
 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-12-02 09:27 UTC, arttor reviewed
It looks pretty good but will new coden from #14915 make any project path requirements obsolete?

2024-12-02 09:45 UTC, obnoxxx commented
@arttor  wrote:
> It looks pretty good but will new coden from #14915 make any project path requirements obsolete?

The requirements should not change with the new codegen version, but the changes from that PR don't even work completely yet, even locally

2024-12-02 09:48 UTC, arttor approved these changes

2024-12-02 15:45 UTC, BlaineEXE requested changes
I want to wait on this until after https://github.com/rook/rook/pull/14915

2024-12-02 15:54 UTC, obnoxxx commented
@BlaineEXE  wrote:
> I want to wait on this until after #14915

Well, I considered this as some kind of fall-out preparation for that PR.

And what is the actual change request here? colse this PR?

2024-12-02 16:01 UTC, obnoxxx commented
> @BlaineEXE wrote:
> 
> > I want to wait on this until after #14915
> 
> Well, I considered this as some kind of fall-out preparation for that PR.
> 

Oh, I confused the PR. the fall-out prep PR is #15075 , not this one 

> And what is the actual change request here? close this PR?

2024-12-02 16:59 UTC, BlaineEXE commented
Changing the script will change the workaround we needed to make for the CI, so I want to wait to work on CI until after script updates. However, if https://github.com/rook/rook/pull/14915 is causing codegen to break, then codegen needs to be fixed in https://github.com/rook/rook/pull/14915.

2024-12-05 18:31 UTC, obnoxxx commented
@arttor wrote: 
> It looks pretty good but will new codegen from #14915 make any project path requirements obsolete?

Correct! after #14915  has been merged, I created a substitute PR that just reverts the previous fix and avoids the  `working-directory` part.

2024-12-05 18:34 UTC, obnoxxx commented
@BlaineEXE  wrote: 
> I want to wait on this until after #14915

Simpler substitute created: #15094

2024-12-06 17:54 UTC, BlaineEXE commented
Closed b/c replacement is up

2024-12-06 17:54 UTC, closed without merging