docs: update guides and examples for v1.16 release
rook/rook pull request #15105
Opened 2024-12-06 20:00 UTC by BlaineEXE

Update upgrade guides, docs, and exmaple manifests for the Rook v1.16 release.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-12-06 20:00 UTC, BlaineEXE commented on Documentation/Upgrade/rook-upgrade.md
>      removal migration steps outlined in
Depending on whether the ObjectStore changes @arttor is working on are merged before release, we might want to add a deprecation note at the end about changes to the Swift API.

2024-12-09 18:24 UTC, travisn requested changes

2024-12-09 18:24 UTC, travisn commented on deploy/examples/filesystem-ec.yaml
> -              # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
Is it worth moving these comment cleanups to a separate commit?

2024-12-09 18:24 UTC, travisn commented on deploy/examples/cosi/bucketclaimandaccess.yaml
> +kind: BucketClaim
Was this intended with this PR? Looks like a test yaml.

2024-12-09 19:25 UTC, travisn approved these changes

2024-12-09 23:20 UTC, merged