upgrade: improve operator error logging for ok-to-stop failures
rook/rook pull request #15184
Opened 2024-12-17 17:04 UTC by OdedViner

#14909
This PR improves the error logging when ok-to-stop requests fail in the Rook operator. Instead of only showing a generic exit status (e.g., exit status 16), the operator now captures and logs the detailed error message returned by the Ceph command.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2025-01-16 20:14 UTC, travisn requested changes

2025-01-16 20:14 UTC, travisn commented on pkg/daemon/ceph/client/upgrade.go
>  			return errors.Wrapf(err, "deployment %s cannot be stopped", deployment)
The details of the failure are found in the `buf` return value above. Let's just include that in the error message that is returned. We don't want to add a new log statement here because it retries a number of times while waiting for success, and it would potentially print the same error many times instead of only at the end of the retries if we just update this error message.
```suggestion
			return errors.Wrapf(err, "deployment %s cannot be stopped. %s", deployment, string(buf))
```

2025-01-19 12:55 UTC, OdedViner commented on pkg/daemon/ceph/client/upgrade.go
>  			return errors.Wrapf(err, "deployment %s cannot be stopped", deployment)
Done.
Thank you, Travis, for your comment. I’d like to reproduce the error in my local environment (Minikube). Could you suggest a method or approach to achieve this?

2025-01-21 19:09 UTC, travisn commented on pkg/daemon/ceph/client/upgrade.go
>  			return errors.Wrapf(err, "deployment %s cannot be stopped", deployment)
An OSD is not ok-to-stop if the `min_size` of a pool cannot be satisfied if the OSD goes down. So if you have 3 OSDs and a replica-3 pool (with default min_size=2), one OSD can go down, but two OSDs cannot go down. You could scale down one OSD to simulate one OSD being down, then Rook should hit this code path that another OSD is not ok-to-stop during upgrade.

2025-01-23 18:30 UTC, OdedViner commented on pkg/daemon/ceph/client/upgrade.go
>  			return errors.Wrapf(err, "deployment %s cannot be stopped", deployment)
@travisn On my setup, I am working with Minikube with 1 node and 1 OSD (replica 1). I have not tested with 3 nodes and 3 OSDs. Is it necessary to test this configuration before merging the PR? If yes, I will explore how to deploy such a setup locally on my machine.

2025-01-23 18:32 UTC, travisn commented on pkg/daemon/ceph/client/upgrade.go
>  			return errors.Wrapf(err, "deployment %s cannot be stopped", deployment)
It could be tested with two OSDs in minikube, with replica 2 and `failureDomain: osd` in the pool. But the change for the error message is simple enough I'm ok to merge without testing it.

2025-01-23 18:33 UTC, travisn approved these changes

2025-01-24 15:13 UTC, merged