Watch env variables instead of polling the configmap
rook/rook pull request #15206
Opened 2024-12-19 18:54 UTC by dimm0

**Issue resolved by this Pull Request:**
Resolves #14932

The operator currently polls the configmap for ROOK_DISABLE_DEVICE_HOTPLUG variable a lot, twice for each node in the cluster. It makes 2N requests in a second to the master, where N is the number of nodes. For large clusters the master throttles the client, after which the operator is unable to perform any actions for some period of time.

The proposal is to keep the config variables in an external configmap, but use envFrom to make those the environment variables in the operator. This will eliminate the configmap polling and will allow users to configure the operator using the configmap.

The down side is that changes in configmap will not be propagated to the operator until it restarts.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2025-01-21 18:12 UTC, dimm0 commented
@travisn Ready for testing

2025-01-22 17:36 UTC, travisn requested changes
Several questions:
1. Which has higher precedence, the configmap values when mounted with `envFrom`, or the env vars set directly on the operator pod spec? We need to maintain the current precedence where the configmap settings get higher priority.
2. This requires the configmap to exist, correct? Some old clusters may not have the configmap. It would be nice to avoid this requirement so we can more easily backport the fix, instead of only considering it for the upcoming 1.17 release with a step in the upgrade guide.
3. What if the configmap is updated? Will the env vars be automatically updated? Or we have to restart the operator to apply them?

What about a different approach that would address those concerns? When the rook operator starts, it can load the configmap once, and call `os.Setenv()` to convert the configmap settings to env vars. This will clearly keep the current precedence of configmap settings, and the configmap is full optional. 

And when the configmap is updated, we can update the env vars and trigger some reconcile to apply the settings where needed. For example, we want to trigger the csi driver reconcile so the new settings will be picked up. I don't see a change to the watcher in this PR, so that behavior likely is still there anyway, though with your PR I am not clear if the env vars would be updated in that case.

2025-01-22 21:10 UTC, dimm0 commented
> Several questions:
> 
> 1. Which has higher precedence, the configmap values when mounted with `envFrom`, or the env vars set directly on the operator pod spec?

The ones directly on the pod spec

> We need to maintain the current precedence where the configmap settings get higher priority.

🤷‍♂️

> 2. This requires the configmap to exist, correct? Some old clusters may not have the configmap. It would be nice to avoid this requirement so we can more easily backport the fix, instead of only considering it for the upcoming 1.17 release with a step in the upgrade guide.

Correct, the pod won't start if the CM doesn't exist. For old clusters it won't change until they deploy the new operator which will make the CM appear.

> 3. What if the configmap is updated? Will the env vars be automatically updated? Or we have to restart the operator to apply them?

Need to restart.

> What about a different approach that would address those concerns? When the rook operator starts, it can load the configmap once, and call `os.Setenv()` to convert the configmap settings to env vars. This will clearly keep the current precedence of configmap settings, and the configmap is full optional.
> 
> And when the configmap is updated, we can update the env vars and trigger some reconcile to apply the settings where needed. For example, we want to trigger the csi driver reconcile so the new settings will be picked up. I don't see a change to the watcher in this PR, so that behavior likely is still there anyway, though with your PR I am not clear if the env vars would be updated in that case.

It would be better then to mount the configMap as a file locally:

```
      volumeMounts:
      - name: config-volume
        mountPath: /etc/operator-config.env
  volumes:
    - name: config-volume
      configMap:
        name: rook-ceph-operator-config
```

And do what you described above. This way you don't need to write any polling code - it will be done by kubernetes. The file will be updated when the configMap changes. But this doesn't address 2.

2025-01-22 21:14 UTC, BlaineEXE commented
This sounds like a real issue that Rook needs to address, but I think we need a different implementation. Reading environment variables from configmaps/secrets has a major limitation: variables are not updated automatically when the configmap value changes, which requires a manual pod restart ([source](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically)).

We could potentially read these from a mounted file, which the Rook operator can watch. Or (my suggestion), Rook can watch the configmap in a reconcile loop and update a globally-kept map of configmap values that can be freely read at any time from other reconcile loops.

2025-01-22 21:15 UTC, BlaineEXE requested changes
Also requesting changes to specifically note that I don't think env var from configmap is something that will be good for rook end users.

2025-01-22 21:18 UTC, dimm0 commented
> This sounds like a real issue that Rook needs to address, but I think we need a different implementation. Reading environment variables from configmaps/secrets has a major limitation: variables are not updated automatically when the configmap value changes, which requires a manual pod restart ([source](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically)).

We wrote the same thing at the same time. Yes, the values will opnly be updated if mounted as a file.

> We could potentially read these from a mounted file, which the Rook operator can watch. Or (my suggestion), Rook can watch the configmap in a reconcile loop and update a globally-kept map of configmap values that can be freely read at any time from other reconcile loops.

If this is done, it would be great to use a SharedInformerFactory rather than directly querying the configmap value.

2025-02-13 04:09 UTC, dimm0 commented
Is this on me still to implement?

2025-02-17 21:27 UTC, travisn commented
> Is this on me still to implement?

@dimm0 It wasn't clear from the comments above if you were still planning on it. Would you prefer we find someone else to pick it up?

2025-02-22 01:05 UTC, travisn commented
@dimm0 I worked on the new implementation to follow on from this discussion. See #15442.

One difference in implementation is that when attempting to mount the configmap as a file, I found that updating the configmap was very slow to update the files (30-90 seconds). Since we want immediate update of the settings, I kept the configmap implementation instead of mounting as a file.

2025-02-25 03:21 UTC, dimm0 commented
LGTM

2025-03-05 23:55 UTC, travisn commented
Closing since #15442 was merged to cover this

2025-03-05 23:55 UTC, closed without merging