ceph: add unit tests for zone group
rook/rook pull request #6274
Opened 2020-09-17 02:08 UTC by alimaredia

Add unit tests for CephObjectZoneGroup, with
minor fixes to the realm unit tests.

Signed-off-by: Ali Maredia <amaredia@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-09-17 21:51 UTC, travisn requested changes
Please rebase on the latest

2020-09-17 21:51 UTC, travisn commented on pkg/operator/ceph/object/zonegroup/controller.go
> +			return waitForRequeueIfObjectRealmNotReady, errors.Wrapf(err, "kerrors.IsNotFound Error hit for realm %s", zoneGroup.Spec.Realm)
```suggestion
			return waitForRequeueIfObjectRealmNotReady, errors.Wrapf(err, "realm %q not found", zoneGroup.Spec.Realm)
```

2020-09-18 07:51 UTC, leseb approved these changes

2020-09-18 15:56 UTC, travisn approved these changes

2020-09-18 15:56 UTC, merged