ceph: stop using hosnetwork for ceph-csi rbd
rook/rook pull request #6310
Opened 2020-09-23 13:09 UTC by leseb

**Description of your changes:**

To properly support multus in ceph-csi work was done to remove the usage
of hostnetworking.
Thus removing it from the templates.

Relies on https://github.com/ceph/ceph-csi/pull/1450

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-09-23 13:17 UTC, Madhu-1 commented
Added DNM till we get ceph-csi release out.

2020-09-23 20:56 UTC, dylanzr commented
Is there no opportunity to leave hostNetworking as a configurable option? We heavily leverage this with our rook/ceph/csi deployments and it works quite well for us.

2020-09-23 21:40 UTC, travisn requested changes
Don't we need to have this configurable as @dylanzr mentioned?

2020-09-23 21:46 UTC, dylanzr commented
> Don't we need to have this configurable as @dylanzr mentioned?

More specifically, we'd actually like to see the option available for the csi-provisioner pods as well. Today, that is not configurable so we are trying to come up with a reasonable workaround.

2020-09-23 22:09 UTC, travisn commented
> > Don't we need to have this configurable as @dylanzr mentioned?
> 
> More specifically, we'd actually like to see the option available for the csi-provisioner pods as well. Today, that is not configurable so we are trying to come up with a reasonable workaround.

@dylanzr What isn't working with the provisioner? Are the rbd commands failing to connect to the mons that are on the host network?

2020-09-23 22:26 UTC, dylanzr commented
> > > Don't we need to have this configurable as @dylanzr mentioned?
> > 
> > 
> > More specifically, we'd actually like to see the option available for the csi-provisioner pods as well. Today, that is not configurable so we are trying to come up with a reasonable workaround.
> 
> @dylanzr What isn't working with the provisioner? Are the rbd commands failing to connect to the mons that are on the host network?

In this case, it's communication with ceph-mgr that's failing.

2020-09-23 22:32 UTC, travisn commented
@dylanzr How about opening a new issue with the error you're seeing?

2020-09-23 22:40 UTC, dylanzr commented
> @dylanzr How about opening a new issue with the error you're seeing?

Sure. I'll take some time to weigh our workaround options and open a new issue accordingly. The errors aren't interesting, as there really aren't any. The connections time out and I was able to capture what was failing via strace.

2020-09-24 13:14 UTC, Madhu-1 commented
I think It's better to have a host networking option so if we see any performance issue users can revert it back to the old state.

2020-09-24 13:16 UTC, Madhu-1 commented on cluster/examples/kubernetes/ceph/direct-mount.yaml
>              mountPath: /etc/rook
This needs a new ceph release right? as the base image also need to have this RBD CLI option

2020-09-28 16:24 UTC, leseb commented
I don't really see why this would need to be configurable, although it does not hurt. But ceph-csi soon won't need it so it seems unnecessary to keep the option around.

2020-09-30 08:49 UTC, leseb commented
I just realized one scenario we might still want to support, we should enable hostnetworking in CSI if the Ceph cluster deployed by Rook uses hostnetworking too!

2020-09-30 16:17 UTC, leseb commented
Note from our last meeting:

* detect if the CephCluster CR has Multus enabled, if so then disable hostnetworking in ceph-csi
* detect if the CephCluster CR has hostnetworking enabled, if so then enable hostnetworking in ceph-csi
* if we get multiple clusters and one has multus configured then this is not likely to work unless the new cluster is SDN only
* add an operator option to force hostnetworking specifically, which will take precedence over what we can discover from the CephCluster spec

2021-01-08 11:58 UTC, leseb commented
After looking at the current code, it looks like we have nothing to do. We will just leave hostnetworking enabled for non-multus environments, if Multus annotations have been applied to the Ceph CSI template, the RBD Plugin template is already edited to disable hostnetworking.
It seems we have nothing to do, so closing this.

2021-01-08 11:58 UTC, closed without merging