ceph: remove user unlink while deleting OBC
rook/rook pull request #6338
Opened 2020-09-28 14:33 UTC by thotz

User unlink is performed just before deleting OBC resources.
Since user is internal to OBC and next to remove to delete user,
unlinking user is not necessary.

Resolves: #6300
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-09-28 16:26 UTC, leseb reviewed
Why was that required before and not anymore?

2020-09-28 16:58 UTC, thotz commented
> Why was that required before and not anymore?

It was not required IMO, but it was present from day 1. @travisn any idea??

2020-09-28 19:03 UTC, travisn commented
> > Why was that required before and not anymore?
> 
> It was not required IMO, but it was present from day 1. @travisn any idea??

Not sure, part of the initial code for OBC that was overlooked. If the user doesn't need to be unlinked, sounds good to remove this.

2020-09-29 09:26 UTC, leseb requested changes
Please remove UnlinkUser() too since it was used once.

2020-09-29 15:13 UTC, leseb approved these changes

2020-09-29 15:14 UTC, merged