ceph: create user for each ganesha daemon
rook/rook pull request #6344
Opened 2020-09-29 14:01 UTC by varshar16

Ganesha daemons don't need to acess ceph cluster with admin capabilities.
Instead new user with restricted caps can be used.

Signed-off-by: Varsha Rao <varao@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-09-29 14:09 UTC, leseb requested changes

2020-09-29 14:09 UTC, leseb commented on pkg/operator/ceph/nfs/config.go
> +	osd_caps := fmt.Sprintf("allow rw pool=%s", n.Spec.RADOS.Pool)
```suggestion
	osdCaps := fmt.Sprintf("allow rw pool=%s", n.Spec.RADOS.Pool)
```

Golang uses camelcase.

2020-09-29 14:52 UTC, travisn requested changes
The unit test `TestCephNFSController` is failing, see the git rules for the details.

2020-09-29 17:07 UTC, varshar16 commented on pkg/operator/ceph/nfs/config.go
> +	osd_caps := fmt.Sprintf("allow rw pool=%s", n.Spec.RADOS.Pool)
Fixed.

2020-09-29 17:09 UTC, varshar16 commented
The failure was due to not updating `pkg/operator/ceph/nfs/controller_test.go`.  I have fixed it. Please take another look. @leseb @travisn

2020-09-29 17:17 UTC, travisn approved these changes
LGTM!

2020-09-30 07:57 UTC, leseb approved these changes

2020-09-30 08:49 UTC, merged