ceph: fix GetCephVolumeRawOSDs to return correct blockPath
rook/rook pull request #6375
Opened 2020-10-06 05:12 UTC by sp98

In case of multiple OSDs per device, GetCephVolumeRawOSDs returns the same device path for all the osds. This PR fixes this issue

Signed-off-by: Santosh Pillai <sapillai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-10-06 07:33 UTC, sp98 commented
@leseb There could be one more issue with the method `[GetCephVolumeRawOSDs](https://github.com/rook/rook/blob/adab0e07e5180b843a134eb284c8433b637657b8/pkg/daemon/ceph/osd/volume.go#L727)`. If the user has specified `block` argument for this method, shouldn't we expect the method to return only 1 or 0 (if no entries found) `osdInfo` results ?

2020-10-06 07:58 UTC, leseb commented
I had it fixed here https://github.com/rook/rook/pull/4879/commits/70f9747fe93dde4cdb81507405e0fe918e6784d5, what's the use case? Today we don't have multiple OSD support on a single disk with raw mode.

2020-10-06 08:06 UTC, sp98 commented
> I had it fixed here [70f9747](https://github.com/rook/rook/commit/70f9747fe93dde4cdb81507405e0fe918e6784d5), what's the use case? Today we don't have multiple OSD support on a single disk with raw mode.

No specific use case. I see the rook is internally calling this method by providing `block` argument. So `[]oposd.OSDInfo` returned by the method should only have a single entry or empty (if no matches are found)

2020-10-06 22:53 UTC, travisn commented
> I had it fixed here [70f9747](https://github.com/rook/rook/commit/70f9747fe93dde4cdb81507405e0fe918e6784d5), what's the use case? Today we don't have multiple OSD support on a single disk with raw mode.

I don't see that in master. Is that commit not merged?

2020-10-07 07:58 UTC, leseb commented
> > I had it fixed here [70f9747](https://github.com/rook/rook/commit/70f9747fe93dde4cdb81507405e0fe918e6784d5), what's the use case? Today we don't have multiple OSD support on a single disk with raw mode.
> 
> @leseb I don't see that in master. Is that commit not merged?

Correct, it's not merged because the PR (https://github.com/rook/rook/pull/4879) associated with it cannot merge since we are waiting for 14.2.12 and 15.2.5. Also, I never separated the commit in a PR since this bug does not affect anything today since multiple OSD per device is not supported by raw mode.

2020-10-07 08:02 UTC, leseb requested changes
This is incomplete, we only need to fix the `args` to not have an empty string in the exec call. I'd wait for https://github.com/rook/rook/pull/4879/commits/70f9747fe93dde4cdb81507405e0fe918e6784d5 to merge as part of https://github.com/rook/rook/pull/4879 since currently, this is not affecting anything and thus close this one. 

wdyt @sp98?

2020-10-08 05:07 UTC, sp98 commented
> This is incomplete, we only need to fix the `args` to not have an empty string in the exec call. I'd wait for [70f9747](https://github.com/rook/rook/commit/70f9747fe93dde4cdb81507405e0fe918e6784d5) to merge as part of #4879 since currently, this is not affecting anything and thus close this one.
> 
> wdyt @sp98?

Yes, we can close this one.

2020-10-08 05:07 UTC, closed without merging