ceph: add --public-addr args to ceph mds command
rook/rook pull request #6701
Opened 2020-11-25 08:00 UTC by sp98

add --public-addr=<podIP> args to ceph mds command when host network is not enabled.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #5938

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2020-11-25 08:41 UTC, leseb requested changes
We never got to the bottom of this issue, there are still a few questions left unanswered https://github.com/rook/rook/issues/5938#issuecomment-672721830. Also, we have made it this far without having to do any changes. The issue suggests that mgr might need to be changed as well. To me, it looks like an env issue but at the same time the fix does not seem to hurt. But again why fixing something that is not broken even though the current change kinda makes sense? 🤔

2020-11-25 11:29 UTC, sp98 commented
> We never got to the bottom of this issue, there are still a few questions left unanswered [#5938 (comment)](https://github.com/rook/rook/issues/5938#issuecomment-672721830). Also, we have made it this far without having to do any changes. The issue suggests that mgr might need to be changed as well. To me, it looks like an env issue but at the same time the fix does not seem to hurt. But again why fixing something that is not broken even though the current change kinda makes sense?

agree. 
mgr seems to have this change already - https://github.com/rook/rook/blob/4d8af284a0adeef13cb3282361afe95e78082e1f/pkg/operator/ceph/cluster/mgr/spec.go#L256-L262

2021-01-24 13:12 UTC, arminfelder commented
I guess this issue is caused by some magic inside Ceph, not Rook, therefor I would advocate to go forward with  @sp98 fix as it does not do not any harm, and fixing the mechanism in Ceph to work with every kind of Kubernetes CNI is out of scope

2021-01-28 19:32 UTC, travisn commented
@leseb @sp98 Shall we go ahead with this change? Seems like it's needed for some clusters, and shouldn't affect existing clusters negatively

2021-01-28 19:41 UTC, travisn commented
rebased to trigger the latest tests...

2021-01-28 20:02 UTC, merged