ceph: Investigate object store cleanup issue in the integration tests
rook/rook pull request #6860
Opened 2020-12-18 22:47 UTC by travisn

**Description of your changes:**
The object store is nearly always timing out in the smoke suite of the Jenkins integration tests when the object store is being deleted. The object store controller is not responding to the delete request because it is still busy with the object store creation reconcile loop for several minutes. 

In local tests and in the github actions, the same test succeeds with no issues.

For now, logging is simply added to help track down the issue in Jenkins.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test full]

2021-01-05 15:25 UTC, leseb commented
Just restarted Jenkins to see if we can trigger the error.

2021-01-07 02:45 UTC, travisn commented
@leseb A timeout was added to ensure the dashboard api commands don't hang too long, and it's confirmed in the operator log for the CI. Let's get a green master build again!

2021-01-07 04:48 UTC, thotz submitted a review, later dismissed
Overall changes LGTM. But not sure whether it is right to have the  log levels used in PR > Info

2021-01-07 08:10 UTC, leseb requested changes
Small nits.

2021-01-07 08:10 UTC, leseb commented on pkg/operator/ceph/object/objectstore.go
> +	logger.Infof("enabling rgw dashboard")
```suggestion
	logger.Info("enabling rgw dashboard")
```

2021-01-07 08:10 UTC, leseb commented on pkg/operator/ceph/object/objectstore.go
> +		logger.Infof("setting the dashboard api secret key")
```suggestion
		logger.Info("setting the dashboard api secret key")
```

2021-01-07 08:10 UTC, leseb commented on pkg/operator/ceph/object/objectstore.go
> +		logger.Infof("done setting the dashboard api secret key")
```suggestion
		logger.Info("done setting the dashboard api secret key")
```

2021-01-07 08:10 UTC, leseb commented on pkg/operator/ceph/object/objectstore.go
> +	logger.Infof("disabling the dashboard api user and secret key")
```suggestion
	logger.Info("disabling the dashboard api user and secret key")
```

2021-01-07 14:14 UTC, leseb approved these changes

2021-01-07 14:34 UTC, travisn commented
> Overall changes LGTM. But not sure whether it is right to have the log levels used in PR > Info

@thotz I'd like to use Info messages since there weren't any around setting the dashboard api. Some info logging is good so we can have insight into the operator during a normal reconcile.

2021-01-07 18:57 UTC, merged