ceph: allow disable liveness check for mds daemonset
rook/rook pull request #6883
Opened 2020-12-28 02:04 UTC by jshen28

Allow to disable liveness probes for mds pod

Signed-off-by: shenjiatong <yshxxsjt715@gmail.com>

**Description of your changes:**

Allow to disable liveness probes for mds pod

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-01-05 16:16 UTC, leseb requested changes
This is not enough you need to add `KeyMds` to the `probeFnMap` in ConfigureLivenessProbe`.

2021-01-11 06:19 UTC, jshen28 commented
@leseb thank you for pointing it out. I've added corresponding entries and hopes it works this time.

2021-01-11 09:35 UTC, leseb requested changes
Small nit

2021-01-11 09:35 UTC, leseb commented on pkg/apis/ceph.rook.io/v1/livenessprobe.go
> +// GetOSDLivenessProbe returns the liveness probe for the OSD service
```suggestion
// GetMdsLivenessProbe returns the liveness probe for the MDS service
```

2021-01-11 09:56 UTC, jshen28 commented on pkg/apis/ceph.rook.io/v1/livenessprobe.go
> +// GetOSDLivenessProbe returns the liveness probe for the OSD service
ah... thank you. I'll fix it.

2021-01-11 10:19 UTC, leseb approved these changes

2021-01-11 10:20 UTC, merged