ceph: do not print pointer memory address
rook/rook pull request #7194
Opened 2021-02-10 14:33 UTC by leseb

When printing pointers of struct (regardless if it is also a slice or
not) we must implement a stringer interface so they can be displayed
properly, this is especially useful when looking at the prepare job
logs.

Before this patch:

```
2021-02-10 06:39:06.783508 D | inventory: discovered disks are [0xc00029c240 0xc00024a000 0xc00086c480 0xc00024a480]
```

After this patch:

```
2021-02-10 14:27:39.553846 D | inventory: discovered disks are:
[LocalDisk{Name: dm-0,  Parent: ,       HasChildren: false, DevLinks: /dev/disk/by-id/dm-uuid-LVM-aIFRq5P3hwE2YhukbOmsEZoLY61HxvX62A1xxb6ajTymVE0N8S4Ga0KWlHSgpvNw /dev/disk/by-id/dm-name-ceph--e29bf82e--86f1--4c8e--8412--c468def5a844-osd--block--2044a1ea--6e5e--4423--88cf--8947bf6957d1, Size: 32208060416, UUID: 5f9bac96-22f8-480c-bdcd-98bcef61baab, Serial: , Type: lvm, Rotational: true, Readonly: false, Partitions: [], Filesystem: ceph_bluestore, Vendor: , Model: , WWN: , WWNVendorExtension: , Empty: false, CephVolumeData: , RealPath: /dev/mapper/ceph--e29bf82e--86f1--4c8e--8412--c468def5a844-osd--block--2044a1ea--6e5e--4423--88cf--8947bf6957d1, KernelName: dm-0: Encrypted: false  LocalDisk{Name: dm-1,  Parent: ,       HasChildren: false, DevLinks: /dev/disk/by-id/dm-uuid-LVM-GyLVW5UxDRcws8PwsbQuY2CjrQwdn1VxgPQjsKZ2pGVaS1r2Ct0OGZ4P80yEMtqW /dev/disk/by-id/dm-name-ceph--334c640f--7a7f--4fdb--9db4--2f9459e19f9a-osd--block--66ce11c8--20f0--4600--ae50--e8849c9a0af6, Size: 32208060416, UUID: 01a0d1a5-0dd1-4ada-80af-f8def3c6f9d7, Serial: , Type: lvm, Rotational: true, Readonly: false, Partitions: [], Filesystem: ceph_bluestore, Vendor: , Model: , WWN: , WWNVendorExtension: , Empty: false, CephVolumeData: , RealPath: /dev/mapper/ceph--334c640f--7a7f--4fdb--9db4--2f9459e19f9a-osd--block--66ce11c8--20f0--4600--ae50--e8849c9a0af6, KernelName: dm-1: Encrypted: false  LocalDisk{Name: dm-2,       Parent: ,       HasChildren: false, DevLinks: /dev/disk/by-id/dm-name-ceph--a011b5c2--cc3f--497a--b19a--6d284461cbc4-osd--block--4de5491c--ecf8--455d--9858--547001fd0321 /dev/disk/by-id/dm-uuid-LVM-QGzgO4E228fvT3NsighNABGdvAKxQEhFOh9rKiDLnSOTk7jLZWu2r1RIMXe5GNqW, Size: 32208060416, UUID: 0ee4dbea-bfd1-41d7-8694-dee7457bb685, Serial: , Type: lvm, Rotational: true, Readonly: false, Partitions: [], Filesystem: ceph_bluestore, Vendor: , Model: , WWN: , WWNVendorExtension: , Empty: false, CephVolumeData: , RealPath: /dev/mapper/ceph--a011b5c2--cc3f--497a--b19a--6d284461cbc4-osd--block--4de5491c--ecf8--455d--9858--547001fd0321, KernelName: dm-2: Encrypted: false  LocalDisk{Name: vda1,  Parent: vda,    HasChildren: false, DevLinks: /dev/disk/by-path/pci-0000:00:05.0-part1 /dev/disk/by-label/boot2docker-data /dev/disk/by-partuuid/f9dd32c9-a4a5-654f-aee4-651276fdc754 /dev/disk/by-uuid/0fdf5e49-6b3c-42f2-a1c5-bf77e490dfa4 /dev/disk/by-path/virtio-pci-0000:00:05.0-part1, Size: 19998934528, UUID: , Serial: , Type: part, Rotational: true, Readonly: false, Partitions: [], Filesystem: ext4, Vendor: , Model: , WWN: , WWNVendorExtension: , Empty: false, CephVolumeData: , RealPath: /dev/vda1, KernelName: vda1: Encrypted: false ]
```

Signed-off-by: Sébastien Han <seb@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-02-10 16:02 UTC, travisn requested changes

2021-02-10 16:24 UTC, leseb commented on pkg/daemon/ceph/osd/device.go
> +	return fmt.Sprintf("DesiredDevice{Name: %s, OSDsPerDevice: %d, MetadataDevice: %s, DatabaseSizeMB: %d, DeviceClass: %s, IsFilter: %t, IsDevicePathFilter: %t", d.Name, d.OSDsPerDevice, d.MetadataDevi
The linter complains with `Sprintf format %+v with arg d causes recursive String method callprintf`.

2021-02-10 16:24 UTC, leseb commented on pkg/clusterd/disk.go
> +	logger.Debugf("discovered disks are: \n%v", disks)
Both solutions are correct, one requires a loop, the other does not, I would say it's a matter of preference at this point... Each time we want to print it we would need a loop. Let's discuss more

2021-02-10 17:25 UTC, travisn commented on pkg/clusterd/disk.go
> +	logger.Debugf("discovered disks are: \n%v", disks)
Even if it works either way, from a pattern perspective, I would expect the developer to work with pointers consistently. Let's say we have a slice of pointers to a type that we don't own. Then you would anyway have to iterate over the slice to print it. Using that same pattern for types we both own and don't own would be my recommendation.

2021-02-10 17:25 UTC, travisn commented on pkg/daemon/ceph/osd/device.go
> +	return fmt.Sprintf("DesiredDevice{Name: %s, OSDsPerDevice: %d, MetadataDevice: %s, DatabaseSizeMB: %d, DeviceClass: %s, IsFilter: %t, IsDevicePathFilter: %t", d.Name, d.OSDsPerDevice, d.MetadataDevi
Oh of course :)

2021-02-10 17:39 UTC, BlaineEXE requested changes

2021-02-10 17:39 UTC, BlaineEXE commented on pkg/daemon/ceph/osd/device.go
> +	return fmt.Sprintf("DesiredDevice{Name: %s, OSDsPerDevice: %d, MetadataDevice: %s, DatabaseSizeMB: %d, DeviceClass: %s, IsFilter: %t, IsDevicePathFilter: %t", d.Name, d.OSDsPerDevice, d.MetadataDevi
Solved by pointer dereference 😊 

```suggestion
	return fmt.Sprintf("%+v", *d)
```

See https://play.golang.org/p/hH5nLfTS5gg

2021-02-10 17:39 UTC, BlaineEXE commented on pkg/util/sys/device.go
> +	return fmt.Sprintf("LocalDisk{Name: %s,	Parent: %s,	HasChildren: %t, DevLinks: %s, Size: %d, UUID: %s, Serial: %s, Type: %s, Rotational: %t, Readonly: %t, Partitions: %v, Filesystem: %s, Vendor: %s,
```suggestion
	return fmt.Sprintf("%+v", *d)
```

See https://play.golang.org/p/hH5nLfTS5gg

2021-02-10 19:59 UTC, BlaineEXE commented on pkg/clusterd/disk.go
> +	logger.Debugf("discovered disks are: \n%v", disks)
We can make a simple pretty printer for slices/maps like this: https://play.golang.org/p/I2fPZDmDZLy

2021-02-11 13:08 UTC, leseb commented
In the end, I decided to go with loop approach since this means:

* a clean output (line by line)
* fewer code changes

The stringer interface feels over-engineered, I'd have had considered it more if we were printing this more often.

2021-02-11 14:19 UTC, travisn approved these changes

2021-02-11 14:20 UTC, merged