ceph: remove unnecessary generate key for osd
rook/rook pull request #7299
Opened 2021-02-24 12:39 UTC by jshen28

keyring for osd.x is generated by `ceph volume` command, thus it is
not necessary to try to create it in operator.

Signed-off-by: shenjiatong <yshxxsjt715@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-02-24 12:39 UTC, jshen28 commented
#7279

2021-02-24 14:14 UTC, leseb requested changes
LGTM, just write a better commit message

2021-02-24 14:16 UTC, leseb commented
@jshen28 also please stop opening/closing PR, if there is anything you are not comfortable with (git maybe?) let us know and we can work it out. Thanks!

2021-02-24 18:03 UTC, BlaineEXE commented
A good commit message would include the info you provided here in the description as well as some context by briefly explaining your analysis from #7279

2021-02-25 00:10 UTC, jshen28 commented
@leseb sorry... I would like to test some changes first but have to push to my github repo first... in order to avoid test every time I push, I've thought it might be better to close it first... Then looks like it cannot be reopen again... so I opened another PR...

2021-02-25 10:50 UTC, leseb approved these changes

2021-02-25 13:51 UTC, merged