DMN: ci: confirm whether timout is too short
rook/rook pull request #7400
Opened 2021-03-14 23:21 UTC by satoru-takeuchi

> Don't merge this PR

**Description of your changes:**

The possibility of passing CI is quite low, for example, in CephFlexSuite, CephSmokeSuite, and so on. However, this behavior doesn't happen in my local high-spec machine. CI seemed to be failed timeout. This PR is to confirm whether timeout is too short for github action's runner or not.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-03-15 04:42 UTC, satoru-takeuchi commented
CephSmokeSuite and CephFlexSuite were run 6 times with HEAD 93db66692d449edec13a8e2721876f35a56d3d26

# result

2/6 passecd.
2/6 passed.

There are four patterns(see later) in logs on failures.

CephSmokeSuite:
|test number|result|og pattern if failed|
|--:|:---|:---|
|1|failed|pattern A|
|2|failed|patternC|
|3|succeeded||
|4|succeeded||
|5|failed|battern B|
|6|failed|battern D|

CephFlexSuite:
|test number|result|og pattern if failed|
|--:|:---|:---|
|1|succeeded||
|2|failed|pattern B|
|3|succeeded||
|4|failed|pattern A|
|5|failed|pattern A|
|6|failed|pattern A|

Most frequent pattern is A. I'm not sure the relationship between each pattern.

# logs patterns on failure

## pattern A: failed to mount cephfs

2021-03-14 19:05:57.197102 D | exec: Running command: kubectl exec -n flex-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook
...
2021-03-14 19:06:28.688683 E | utils: Failed to execute: kubectl [exec -n flex-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook] : exit status 32. mount error: no mds server is up or the cluster is laggy
command terminated with exit code 32
    ceph_base_file_test.go:509: 
        	Error Trace:	ceph_base_file_test.go:509
        	            				ceph_base_file_test.go:271
        	            				ceph_flex_test.go:115
        	Error:      	Expected nil, but got: &errors.errorString{s:"kubectl exec command bash failed on pod rook-ceph-tools in namespace flex-ns. Failed to run: kubectl [exec -n flex-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook] : exit status 32"}
        	Test:       	TestCephFlexSuite/TestFileSystem

## Pattern B: failed to call webhook

```
2021-03-15T00:40:03.2577902Z 2021-03-15 00:40:03.257355 I | installer: Starting Rook Cluster with yaml
...
2021-03-15T00:40:03.2612887Z 2021-03-15 00:40:03.257443 I | testutil: Running kubectl [create -f -]
2021-03-15T00:40:03.6975309Z Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found
2021-03-15T00:40:03.7030549Z 2021-03-15 00:40:03.702747 E | utils: Failed to execute stdin: kubectl [create -f -] : exit status 1
2021-03-15T00:40:03.7035943Z 2021-03-15 00:40:03.702772 I | installer: failed to create rook cluster, trying again... Failed to run stdin: kubectl [create -f -] : Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found
2021-03-15T00:40:08.7034234Z 2021-03-15 00:40:08.702878 I | testutil: Running kubectl [create -f -]
2021-03-15T00:40:09.0729695Z Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found
2021-03-15T00:40:09.0804030Z 2021-03-15 00:40:09.078520 E | utils: Failed to execute stdin: kubectl [create -f -] : exit status 1
2021-03-15T00:40:09.0809869Z 2021-03-15 00:40:09.078543 I | installer: failed to create rook cluster, trying again... Failed to run stdin: kubectl [create -f -] : Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found
2021-03-15T00:40:14.0791264Z 2021-03-15 00:40:14.078663 I | testutil: Running kubectl [create -f -]
2021-03-15T00:40:14.4405712Z Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found
2021-03-15T00:40:14.4445842Z 2021-03-15 00:40:14.444112 E | utils: Failed to execute stdin: kubectl [create -f -] : exit status 1
2021-03-15T00:40:14.4632890Z 2021-03-15 00:40:14.444155 E | installer: Rook cluster flex-ns not installed, error -> failed to create rook cluster. Failed to run stdin: kubectl [create -f -] : Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found 
2021-03-15T00:40:14.4647483Z 2021-03-15 00:40:14.444161 E | integrationTest: Rook was not installed successfully: failed to create rook cluster. Failed to run stdin: kubectl [create -f -] : Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-flex-ns-system.rook.io": Post "https://rook-ceph-admission-controller.flex-ns-system.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s": service "rook-ceph-admission-controller" not found 
2021-03-15T00:40:14.4652917Z 2021-03-15 00:40:14.444172 I | installer: test environment variable (default) "TEST_LOG_COLLECTION_LEVEL"=""
2021-03-15T00:40:14.4654024Z 2021-03-15 00:40:14.444182 I | installer: gathering all logs from the test
```

## pattern C:  missing user secret

```
2021-03-15T00:37:48.0117849Z 2021-03-15 00:37:48.011386 I | testutil: All 3 pod(s) with label rook_object_store=teststore are running
2021-03-15T00:37:48.0118636Z 2021-03-15 00:37:48.011412 I | testutil: Running kubectl [apply -f -]
2021-03-15T00:37:48.4090407Z service/rgw-external-teststore created
2021-03-15T00:37:48.4147029Z 2021-03-15 00:37:48.414334 I | integrationTest: Check that RGW pods are Running
2021-03-15T00:37:48.4232213Z 2021-03-15 00:37:48.422737 I | testutil: 3 of 1 pods with label app=rook-ceph-rgw were found
2021-03-15T00:37:48.4360803Z 2021-03-15 00:37:48.434461 I | testutil: 3 of 1 pods with label app=rook-ceph-rgw were found
2021-03-15T00:37:48.4402329Z 2021-03-15 00:37:48.440061 I | integrationTest: RGW pods are running
2021-03-15T00:37:48.4403989Z 2021-03-15 00:37:48.440080 I | integrationTest: Object store created successfully
2021-03-15T00:37:48.4405567Z 2021-03-15 00:37:48.440083 I | integrationTest: Waiting 5 seconds for the object user to be created
2021-03-15T00:37:53.4410033Z 2021-03-15 00:37:53.440236 I | integrationTest: Checking to see if the user secret has been created
2021-03-15T00:37:53.4412392Z 2021-03-15 00:37:53.440267 D | exec: Running command: kubectl get -n smoke-ns secrets -l rook_object_store=teststore -l user=rook-user
2021-03-15T00:37:53.5653711Z 2021-03-15 00:37:53.564745 I | clients: Unable to find user secret
2021-03-15T00:37:53.5655450Z 2021-03-15 00:37:53.564768 I | integrationTest: (0) secret check sleeping for 5 seconds ...
2021-03-15T00:37:58.5655947Z 2021 [...]

2021-03-15 06:39 UTC, subhamkrai commented
@satoru-takeuchi for patter B webhook error https://github.com/rook/rook/pull/7388 this PR will resolve that and will give the status of the cert-manager pod(which state they are in).

2021-03-15 07:14 UTC, satoru-takeuchi commented
@subhamkrai Great! Thanks.

2021-03-15 08:00 UTC, satoru-takeuchi commented
pattern D will be fixed by #7404.

2021-03-15 18:49 UTC, travisn requested changes
#7390 may help with pattern B, I may have found an issue there at the same time.
Marking as changes requested since this PR is just for experimentation.

2021-03-15 20:01 UTC, satoru-takeuchi commented
@travisn Mark it also as draft.

2021-03-30 02:47 UTC, satoru-takeuchi commented
Pattern D is fixed.

2021-03-31 11:21 UTC, satoru-takeuchi commented
I re-ran SmokeSuite and HelmSuite several times in master branch. Thanks to many effort of stabilizing CIs, things has improved significantly. Although not all intermittent failure disppeared, thier probablily got too low. I close this PR for now.

2021-03-31 11:21 UTC, closed without merging