ci: ceph: ignore device_health_metrics in listing rbd images
rook/rook pull request #7404
Opened 2021-03-15 07:57 UTC by satoru-takeuchi

**Description of your changes:**

`rbd ls -l device_health_metrics` sometimes wait forever. It results in the timeout of CI
after a long time (30 minutes by default) as follows.

```
...
2021-03-15T01:49:44.7896081Z === RUN TestCephSmokeSuite/TestBlockStorage_SmokeTest
2021-03-15T01:49:44.7905141Z 2021-03-15 01:49:44.789998 I | integrationTest: Block Storage End to End Integration Test - create, mount, write to, read from, and unmount
2021-03-15T01:49:44.7906815Z 2021-03-15 01:49:44.790015 I | integrationTest: Running on Rook Cluster smoke-ns
2021-03-15T01:49:44.7907806Z 2021-03-15 01:49:44.790019 I | integrationTest: Step 0 : Get Initial List Block
2021-03-15T01:49:44.7909156Z 2021-03-15 01:49:44.790028 D | exec: Running command: kubectl exec -i rook-ceph-tools -n smoke-ns -- ceph osd lspools --connect-timeout=15 --format json
2021-03-15T01:49:46.0122492Z 2021-03-15 01:49:46.011781 D | exec: Running command: kubectl exec -i rook-ceph-tools -n smoke-ns -- rbd ls -l device_health_metrics --format json
2021-03-15T02:17:24.9291728Z panic: test timed out after 30m0s
...
```

Let's ignore to list this pool. It's harmless because this pool is empty in new cluster anyway.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-03-15 08:49 UTC, leseb reviewed
FYI: https://github.com/rook/rook/issues/7405

2021-03-15 09:33 UTC, satoru-takeuchi commented
@leseb I'll investigate #7405 , if it would be able to fix the root cause. I mark.thos PR as draft for now.

2021-03-15 18:41 UTC, travisn requested changes

2021-03-15 18:41 UTC, travisn commented on tests/framework/clients/block.go
> +			break
I think we want to continue with other pools and just ignore this one, right?
```suggestion
			continue
```

2021-03-19 00:20 UTC, travisn commented
@satoru-takeuchi Any more clues on this one? It's our most common test issue now, would be great to fix...

2021-03-19 00:30 UTC, satoru-takeuchi commented
@travisn 

I heard @leseb will fix this problem soon. CMIIW.

2021-03-23 08:56 UTC, leseb commented
> @travisn
> 
> I heard @leseb will fix this problem soon. CMIIW.
> 
> If it would take more times, it's also OK to bypass this problem with this PR for now.

I got distracted by other things. I might only have time next week to come back to this.
I'm not sure if this patch actually bypasses the issue. I believe it only delays the problem until a pool is created.

The problem is that the OSD is crash looping because the permissions on the disk are reset (by udev most likely). So the cluster is never in a good shape. The main problem is that not all runners have this issue.

2021-03-23 10:42 UTC, satoru-takeuchi commented
@leseb Yes,I confirmed that this problem doesn't disappear by this PR. And now I'm working on this issue. Hope it will be fixed in this week. This issue seems to happen frequently very much today.

2021-03-23 10:46 UTC, leseb commented
> @leseb Yes,I confirmed that this problem doesn't disappear by this PR. And now I'm working on this issue. Hope it will be fixed in this week. This issue seems to happen frequently very much today.

Thanks for taking over.

2021-03-24 10:14 UTC, satoru-takeuchi commented
Tmate session after building rook.

```console
$ ls -l /dev/sd*
brw-rw---- 1 root disk 8,  0 Mar 24 09:55 /dev/sda
brw-rw---- 1 root disk 8,  1 Mar 24 09:55 /dev/sda1
brw-rw---- 1 root disk 8, 14 Mar 24 09:55 /dev/sda14
brw-rw---- 1 root disk 8, 15 Mar 24 09:55 /dev/sda15
brw-rw---- 1 root disk 8, 16 Mar 24 10:05 /dev/sdb
brw-rw---- 1 root disk 8, 17 Mar 24 10:05 /dev/sdb1
```

```console
$ dmesg | grep sdb1
[    2.645945]  sdb: sdb1
[   10.131548]  sdb: sdb1
[   11.863341] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null)
```

2021-03-24 10:22 UTC, satoru-takeuchi commented
@leseb I have basic questions about host-based cluster because I'm not familiar with this type cluster. I consider the expected owner:group of block devices for OSD is "root:disk" than "ceph(167):ceph(167)"?  If "ceph:ceph", is there any logic to override existing block device files with new ones?

2021-03-24 10:45 UTC, leseb commented
> @leseb I have basic questions about host-based cluster because I'm not familiar with this type cluster. I consider the expected owner:group of block devices for OSD is "root:disk" than "ceph(167):ceph(167)"? If "ceph:ceph", is there any logic to override existing block device files with new ones?

The `root:disk` permission is the system's default. The reason why we override it to `ceph:ceph` (or `167:167`) is because the OSD daemon run under the `ceph` user and not root.
Does that help?

2021-03-24 10:51 UTC, satoru-takeuchi commented
> The root:disk permission is the system's default. The reason why we override it to ceph:ceph (or 167:167) is because the OSD daemon run under the ceph user and not root.
> Does that help?

@leseb Ah, yes, thank you! I found the chown in osd code just now.

https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L103

I'll continue to investigate this issue especially focusing on udev.

2021-03-24 10:53 UTC, leseb commented
> > The root:disk permission is the system's default. The reason why we override it to ceph:ceph (or 167:167) is because the OSD daemon run under the ceph user and not root.
> > Does that help?
> 
> @leseb Ah, yes, thank you! I found the chown in osd code just now.
> 
> https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L103
> 
> I'll continue to investigate this issue especially focusing on udev.

@satoru-takeuchi I just thought about something that might be a simple fix here: https://github.com/rook/rook/pull/7467, let's see how that work!

2021-03-24 10:59 UTC, satoru-takeuchi commented
@leseb Wow, it's very simple and would be enough to workaround this problem. I'll run HelmSuite and SmokeSuite multiple times to confirm how it works.

2021-03-24 11:41 UTC, satoru-takeuchi commented
@leseb When failure, sdb seems to be attached/detached continuously.

```console
dmesg
....
[ 1116.905811] docker0: port 4(veth40b3653) entered blocking state
[ 1116.905812] docker0: port 4(veth40b3653) entered forwarding state
[ 1119.483639]  sdb: sdb1
[ 1119.984324]  sdb: sdb1
[ 1124.583154]  sdb: sdb1
[ 1125.103205]  sdb: sdb1
[ 1129.676603]  sdb: sdb1
[ 1130.102950]  sdb: sdb1
[ 1134.776521]  sdb: sdb1
[ 1135.250131]  sdb: sdb1
[ 1139.854729]  sdb: sdb1
[ 1140.258897]  sdb: sdb1
[ 1144.942330]  sdb: sdb1
[ 1145.402839]  sdb: sdb1
[ 1150.033066]  sdb: sdb1
[ 1150.434360]  sdb: sdb1
[ 1155.138325]  sdb: sdb1
[ 1155.701090]  sdb: sdb1
[ 1160.217446]  sdb: sdb1
[ 1160.614816]  sdb: sdb1
[ 1165.293167]  sdb: sdb1
[ 1165.700072]  sdb: sdb1
[ 1170.359880]  sdb: sdb1
[ 1170.746992]  sdb: sdb1
[ 1175.430908]  sdb: sdb1
[ 1175.824292]  sdb: sdb1
[ 1180.525786]  sdb: sdb1
[ 1180.976678]  sdb: sdb1
[ 1185.607651]  sdb: sdb1
[ 1185.972740]  sdb: sdb1
[ 1190.719243]  sdb: sdb1
[ 1191.200250]  sdb: sdb1
[ 1195.794035]  sdb: sdb1
[ 1196.226549]  sdb: sdb1
[ 1200.875002]  sdb: sdb1
[ 1201.293201]  sdb: sdb1
[ 1205.953587]  sdb: sdb1
[ 1206.361987]  sdb: sdb1
[ 1211.024444]  sdb: sdb1
[ 1211.405058]  sdb: sdb1
[ 1216.121915]  sdb: sdb1
[ 1216.525097]  sdb: sdb1
[ 1221.203612]  sdb: sdb1
[ 1221.641304]  sdb: sdb1
```

Then block device files are re-created each time and all owner information are cleared. It would be a VM instance matter than udev, but I'm not sure yet. Hope your PR fix this problem.

2021-03-24 11:59 UTC, satoru-takeuchi commented
I'll try to copy the target device to /dev/rook-test. It might be able to avoid continuous device file re-creation.

```
    - name: TestCephHelmSuite
      run: |
       tests/scripts/minikube.sh helm
       tests/scripts/helm.sh up
       DEV=$(lsblk|awk '/14G/ {print $1}'| head -1)
       cp /dev/${DEV} /dev/rook-test
       export DEVICE_FILTER=rook-test
       SKIP_TEST_CLEANUP=false SKIP_CLEANUP_POLICY=false go test -v -timeout 1800s -run CephHelmSuite github.com/rook/rook/tests/integration
```

2021-03-24 13:37 UTC, satoru-takeuchi commented
> I'm trying to copy the target device to /dev/rook-test. It might be able to avoid continuous device file re-creation.

It's impossible since copied device files are not recognized by lsblk.

2021-03-24 16:31 UTC, satoru-takeuchi commented
@leseb Finally I succeeded to bypass this problem. PTAL.

2021-03-25 10:02 UTC, satoru-takeuchi commented
It will be resolved by #7467 in a different way.

2021-03-25 10:02 UTC, closed without merging