[WIP] Ceph: add pool quota usage alerts
rook/rook pull request #7525
Opened 2021-04-06 11:53 UTC by umangachapagain

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

**Description of your changes:**
add quota usage alerts for pools with quota set.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-04-12 05:21 UTC, umangachapagain commented
/cc @anmolsachan

2021-04-12 08:05 UTC, anmolsachan requested changes

2021-04-12 08:05 UTC, anmolsachan commented on cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
> +        description: Storage pool quota usage has crossed 90%.
```suggestion
        description: Storage pool  {{ $labels.name }} quota usage has crossed 90%.
```

2021-04-12 08:05 UTC, anmolsachan commented on cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
> +        message: Storage pool quota bytes is near exhaustion.
```suggestion
        message: Storage pool quota(bytes) is near exhaustion.
```

2021-04-12 08:05 UTC, anmolsachan commented on cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
> +        message: Storage pool quota bytes is critically exhausted.
```suggestion
        message: Storage pool quota(bytes) is critically exhausted.
```

2021-04-12 12:48 UTC, anmolsachan requested changes

2021-04-12 12:48 UTC, anmolsachan commented on cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
> +    - alert: PoolQuotaBytesNearExhaustion
Considering support of other Storage Providers, we can add Ceph to the name of the alert.
```suggestion
    - alert: CephPoolQuotaBytesNearExhaustion
```

2021-04-12 12:48 UTC, anmolsachan commented on cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
> +    - alert: PoolQuotaBytesCriticallyExhausted
Considering the support of other Storage Providers, we can add Ceph to the name of the alert.
```suggestion
    - alert: CephPoolQuotaBytesCriticallyExhausted
```

2021-04-12 17:08 UTC, anmolsachan approved these changes

2021-04-12 17:16 UTC, travisn approved these changes

2021-04-12 17:16 UTC, merged

2021-09-16 22:44 UTC, zerkms commented
@umangachapagain @travisn  I think rules added in this PR are wrong, see https://github.com/rook/rook/issues/8735