ceph: continue to get available devices if failed to get a device info
rook/rook pull request #7608
Opened 2021-04-13 14:48 UTC by satoru-takeuchi

**Description of your changes:**

getAvailableDevices() should continue if something wrong happens in a device than returning immediately with error.

**Which issue is resolved by this Pull Request:**
Resolves #7543

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-04-13 15:28 UTC, leseb requested changes

2021-04-13 20:45 UTC, BlaineEXE commented on pkg/daemon/ceph/osd/daemon.go
> +				rejectedReason = fmt.Sprintf("failed to get device %q info", device.Name)
Why `%s` with `err.Error()` and not `%v` with `err`?

2021-04-13 20:47 UTC, BlaineEXE reviewed
LGTM once Seb's comment is addressed. :+1:

2021-04-13 21:20 UTC, BlaineEXE commented
I think this may also resolve https://github.com/rook/rook/issues/7449, but more investigation might be needed there.

2021-04-14 03:15 UTC, travisn approved these changes

2021-04-14 07:10 UTC, leseb commented on pkg/daemon/ceph/osd/daemon.go
> +				rejectedReason = fmt.Sprintf("failed to get device %q info", device.Name)
No particular reasons but now that I think of it most of the code base uses `%v` with `err`. Essentially after reading this it looks like it's the same:

```
The default format for %v is:

bool:                    %t
int, int8 etc.:          %d
uint, uint8 etc.:        %d, %#x if printed with %#v
float32, complex64, etc: %g
string:                  %s
chan:                    %p
pointer:                 %p
```

Let remain consistent with the code base and use `%v` with `err`.

2021-04-14 07:10 UTC, leseb approved these changes

2021-04-14 07:10 UTC, merged