ceph: support for OBC operations if it uses TLS RGW endpoint
rook/rook pull request #7764
Opened 2021-04-27 09:17 UTC by thotz

**Description of your changes:**
OBC operations will fail if RGW only enabled HTTPS. With this change, OBC operations
will use needed TLS certs to succeed in the operation. Similar changes were made into healthcheck and liveprobe code path of RGW

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-04-27 12:11 UTC, leseb requested changes

2021-04-27 12:11 UTC, leseb commented on pkg/operator/ceph/object/bucket/provisioner.go
> +	if objStore.Spec.Gateway.SecurePort == p.storePort {
Can we add this in the Provisioner during the initialization `initializeCreateOrGrant`? So we don't need to call it each time.

2021-04-27 12:11 UTC, leseb commented on pkg/operator/ceph/object/rgw.go
> +// fetch cacert for internal RGW requests
```suggestion
// GetTLSCACert fetch cacert for internal RGW requests
```

2021-04-27 13:14 UTC, leseb approved these changes

2021-04-27 18:36 UTC, BlaineEXE requested changes

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/rgw.go
> +func GetTLSCACert(objContext *Context, objectStoreSpec *cephv1.ObjectStoreSpec) ([]byte, error) {
Nit. I think this reads a little more easily as `GetTlsCaCert` since the two acronyms (TLS and CA) run together as written.

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/bucket/provisioner.go
> +		return errors.Wrap(err, "failed to fetch cacert for TLS connection")
3 things:
1. CA cert is two words
2. Is there more info you can add to this error to identify it more clearly? E.g., the bucket name, namespace of the request, or anything similar?
3. It seems that "failed to **fetch** CA cert" is not quite accurate given that the method called has "set" in the name

```suggestion
		return errors.Wrap(err, "failed to fetch CA cert for TLS connection")
```

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/bucket/provisioner.go
> +		return errors.Wrap(err, "failed to fetch cacert for TLS connection")
3 things:
1. CA cert is two words
2. Is there more info you can add to this error to identify it more clearly? E.g., the bucket name, namespace of the request, or anything similar?
3. It seems that "failed to **fetch** CA cert" is not quite accurate given that the method called has "set" in the name

```suggestion
		return errors.Wrap(err, "failed to fetch CA cert for TLS connection")
```

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/health.go
> +			return errors.Wrap(err, "failed to fetch cacert for TLS connection")
2 things:
1. CA cert is two words
2. Is there more info you can add to this error to identify it more clearly? E.g., the object store name, user name, or things like that?

```suggestion
		return errors.Wrap(err, "failed to fetch CA cert for TLS connection")
```

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/rgw.go
> +			return nil, err
What additional context can you add to the error to add clarity? E.g., `failed to get secret "<objectStoreSpec.Gateway.SSLCertificateRef>" defined in object store "<objectStoreSpec.name>" gateway.sslCertificateRef`

2021-04-27 18:36 UTC, BlaineEXE commented on pkg/operator/ceph/object/rgw.go
> +			return nil, err
What additional context can you add to the error to add clarity? E.g. `"failed to fetch TLS certificate from %q", ServiceServingCertCAFile`

2021-04-28 20:26 UTC, BlaineEXE approved these changes

2021-04-28 20:27 UTC, merged