ceph: remove an missing field in crd
rook/rook pull request #7919
Opened 2021-05-17 07:57 UTC by satoru-takeuchi

**Description of your changes:**

`CephObjectStore->gateway->type` is not used. Rook has only supported s3-like interface and hasn't had no code which handles `type` field.

In addition, this field was removed from CRD in the following commit.

ceph: auto-gen crds
31db03fece6d11c3054a6488b96d1c6ad3722b84

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-05-17 10:17 UTC, leseb requested changes
If we want to deprecate this flag, we also need a note in the release note. Thanks!

2021-05-17 17:13 UTC, travisn commented
> If we want to deprecate this flag, we also need a note in the release note. Thanks!

If the flag has already been ignored by the code, it seems fine to just remove it without a release note. If there isn't impact to the users or risk of a breaking change, I generally prefer to exclude that info from the release notes.

2021-05-18 01:11 UTC, satoru-takeuchi commented
@leseb 

> If the flag has already been ignored by the code, it seems fine to just remove it without a release note. If there isn't impact to the users or risk of a breaking change, I generally prefer to exclude that info from the release notes.

What do you think?

2021-05-18 08:09 UTC, leseb commented
> > If we want to deprecate this flag, we also need a note in the release note. Thanks!
> 
> If the flag has already been ignored by the code, it seems fine to just remove it without a release note. If there isn't impact to the users or risk of a breaking change, I generally prefer to exclude that info from the release notes.

I overlooked that!

2021-05-18 08:09 UTC, leseb commented
> @leseb
> 
> > If the flag has already been ignored by the code, it seems fine to just remove it without a release note. If there isn't impact to the users or risk of a breaking change, I generally prefer to exclude that info from the release notes.
> 
> What do you think? I also consider the description in note is not necessary.

LGTM.

2021-05-18 08:10 UTC, leseb approved these changes

2021-05-18 08:10 UTC, merged