doc: update the description about creating osds in ceph
rook/rook pull request #7969
Opened 2021-05-22 07:52 UTC by satoru-takeuchi

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

2021-05-24 04:52 UTC, subhamkrai requested changes
commitlint bot is failing.

2021-05-24 05:49 UTC, subhamkrai requested changes

2021-05-24 05:49 UTC, subhamkrai commented on Documentation/ceph-cluster-crd.md
>  in clusters where a local PV provisioner is available.
```suggestion
This type of cluster is recommended to use with CSI drivers which support dynamic volume provisioning and also
in clusters where a local PV provisioner is available.
```

2021-05-24 06:05 UTC, subhamkrai approved these changes
LGTM

2021-05-24 12:31 UTC, leseb approved these changes

2021-05-24 19:40 UTC, travisn requested changes

2021-05-24 19:40 UTC, travisn commented on Documentation/ceph-cluster-crd.md
>  ```yaml
I'd like to keep the examples at the top of this page simple, and have more complex examples later in the doc. What about this?
- This example should match the cluster-on-pvc.yaml example for aws
- We should add a new section later in the doc for this example that creates local PVs and uses a local provisioner

2021-05-24 19:40 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +apiVersion: storage.k8s.io/v1
Please add this example yaml in the examples folder, for example named cluster-on-local-pvs.yaml. It's easier to use the examples if we have them in the example folder.

2021-07-13 18:48 UTC, travisn requested changes

2021-07-13 18:48 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +And below is the settings for PVC-based cluster.
```suggestion
Below are the settings for a PVC-based cluster.
```

2021-07-13 18:48 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
> +              topologyKey: topology.kubernetes.io/zone
Shall we change this constraint to `kubernetes.io/hostname`? Or maybe we don't need the topology spread constraints for the local storage example if we're only creating OSDs on exactly the number of local PVs that are created.

2021-07-13 18:48 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
> +        # dedicated block device to store bluestore database (block.db)
How about if we don't duplicate all the commented settings like metadata/wal? The cluster-on-pvc.yaml example can be followed if needed, and this example can just focus on the local PVs.

2021-07-13 18:48 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
> +  # security:
Similarly, no need for the commented security settings in this example

2021-07-13 18:48 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-local-pvc.yaml
> +# For example, to create the cluster:
How about adding a comment at the top that tells the assumptions of the example? We expect three nodes, each with two available disks. The example will certainly need to be modified with their host and device names.

2021-07-14 13:53 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
> -        # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
This comment still seems good to keep

2021-07-14 21:03 UTC, travisn commented on cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
> -        # IMPORTANT: If volumes specified by the storageClassName are not portable across nodes
The following two lines are also needed

2021-07-14 21:14 UTC, satoru-takeuchi commented
@travisn oops, I overlooked the following lines. fixed.

2021-07-15 22:50 UTC, satoru-takeuchi commented
@travisn Could you take a look this PR again? I reflected all your suggestion.

2021-07-15 22:53 UTC, travisn approved these changes

2021-07-15 22:54 UTC, merged