doc: update ceph-teardown doc
rook/rook pull request #8017
Opened 2021-05-31 06:11 UTC by sp98

update ceph teardown doc to include cleanupPolicy which enables automatic clean up of the dataDirHostPath and the drives

Signed-off-by: Santosh Pillai <sapillai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #7312

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

2021-05-31 07:56 UTC, leseb requested changes

2021-05-31 07:56 UTC, leseb commented on Documentation/ceph-teardown.md
> +Edit the cephCluster and add the `cleanupPolicy`
```suggestion
Edit the `CephCluster` and add the `cleanupPolicy`
```

2021-05-31 07:56 UTC, leseb commented on Documentation/ceph-teardown.md
> +WARNING: DATA WILL BE PERMANENTLY DELETED AFTER DELETING THE `cephCluster` CRD WITH `cleanupPolicy`.
```suggestion
WARNING: DATA WILL BE PERMANENTLY DELETED AFTER DELETING THE `CephCluster` CR WITH `cleanupPolicy`.
```

2021-05-31 07:56 UTC, leseb commented on Documentation/ceph-teardown.md
> +Once the cleanup policy is enabled, any new configuration changes in the cephCluster will be blocked. Nothing will happen unitl the deletion of the CR is requested, so this `cleanupPolicy` change can
```suggestion
Once the cleanup policy is enabled, any new configuration changes in the CephCluster will be blocked. Nothing will happen unitl the deletion of the CR is requested, so this `cleanupPolicy` change can still be reverted.
```

2021-06-01 15:18 UTC, travisn requested changes

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +Once the cleanup policy is enabled, any new configuration changes in the CephCluster will be blocked. Nothing will happen unitl the deletion of the CR is requested, so this `cleanupPolicy` change can
```suggestion
Once the cleanup policy is enabled, any new configuration changes in the CephCluster will be blocked. Nothing will happen until the deletion of the CR is requested, so this `cleanupPolicy` change can still be reverted if needed.
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +## Automatic Cleanup
How about if we just keep this in the same section? We're just recommending to use the automatic cleanup by default now.
```suggestion
## Delete the CephCluster CR
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +## Delete the CephCluster CRD
no need for this header if the other is renamed above

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +Checkout more details about the `cleanupPolicy` [here](https://rook.io/docs/rook/master/ceph-cluster-crd.html#cleanup-policy)
Actually just refer to the .md files in the links, and the build process replaces with the correct html and branch link
```suggestion
Checkout more details about the `cleanupPolicy` [here](ceph-cluster-crd.md#cleanup-policy)
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +These jobs :
```suggestion
These jobs will perform the following operations:
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +- Clean up the `/var/lib/rook` (or the path specified by the `dataDirHostPath`) on all the nodes
```suggestion
- Delete the directory `/var/lib/rook` (or the path specified by the `dataDirHostPath`) on all the nodes
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +- Delete the data on the drives on all the nodes
```suggestion
- Wipe the data on the drives on all the nodes where OSDs were running in this cluster
```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +Note: The cleanup jobs might not start if the resources created on top of Rook Cluster are not deleted completely. [See](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md#delete
```suggestion
Note: The cleanup jobs might not start if the resources created on top of Rook Cluster are not deleted completely. [See](ceph-teardown.md#delete-the-block-and-file-artifacts)

```

2021-06-01 15:18 UTC, travisn commented on Documentation/ceph-teardown.md
> +If the `cleanupPolicy` was applied and the cleanup jobs have completed on all the nodes, then the cluster tear down has been successful. If you have skipped adding the `cleanupPolicy` then follow the
```suggestion
If the `cleanupPolicy` was applied and the cleanup jobs have completed on all the nodes, then the cluster tear down has been successful. If you skipped adding the `cleanupPolicy` then follow the manual steps mentioned below to tear down the cluster.
```

2021-06-01 17:15 UTC, travisn requested changes
one more tiny suggestion...

2021-06-01 17:15 UTC, travisn commented on Documentation/ceph-teardown.md
> +Note: The cleanup jobs might not start if the resources created on top of Rook Cluster are not deleted completely. [See](ceph-teardown.md#delete-the-block-and-file-artifacts)
nit: add a newline

2021-06-03 07:25 UTC, leseb approved these changes

2021-06-03 17:48 UTC, travisn approved these changes

2021-06-03 17:48 UTC, merged