ceph: add ability to set resource limit for OSDs based on device classes
rook/rook pull request #8079
Opened 2021-06-08 15:37 UTC by degorenko

Currently it is not possible to set resource limits based on device classes
for different OSDs. Now adding an ability to use predefined keys for main
cluster spec Resource section to reflect resource limits for different OSDs
with different device classes.

This is an backport of pull request #8028 

Closes: https://github.com/rook/rook/issues/8007
Signed-off-by: Denis Egorenko <degorenko@mirantis.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-08 15:53 UTC, leseb requested changes
Please use `git cherry-pick -x` to bring the commit from master in the release-1.6 branch

2021-06-08 16:18 UTC, travisn reviewed
LGTM, could you just confirm what manual testing you could do on this? Since there were merge conflicts it would be good to test again to make sure something didn't break with the backport.

2021-06-08 16:23 UTC, degorenko commented
does CI builds Rook images per PR ? If so, i can pick it and test locally to be sure release branch is not broken.

2021-06-08 16:25 UTC, travisn commented
> does CI builds Rook images per PR ? If so, i can pick it and test locally to be sure release branch is not broken.

No, the PR builds are not pushed anywhere so you would need to build locally.

2021-06-08 16:26 UTC, leseb approved these changes

2021-06-08 16:34 UTC, degorenko commented
> > does CI builds Rook images per PR ? If so, i can pick it and test locally to be sure release branch is not broken.
> 
> No, the PR builds are not pushed anywhere so you would need to build locally.

Ok, i will need sometime to build images/do testing.

2021-06-12 06:19 UTC, degorenko commented
Tested manually.

2021-06-14 15:26 UTC, travisn approved these changes

2021-06-14 15:26 UTC, merged