ceph: backport installation documentation for Ceph Cluster chart
rook/rook pull request #8088
Opened 2021-06-09 04:23 UTC by henryzhangsta

Adds documentation to 1.6 branch with instructions as to how to install the
chart slated for release in 1.7.

Signed-off-by: Henry Zhang <me@henry.dev>

**Description of your changes:**

As discussed in https://github.com/rook/rook/pull/7778, this adds a documentation section to the 1.6 release that points to the ceph-cluster Helm chart that is currently in master.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-09 04:49 UTC, subhamkrai requested changes

2021-06-09 04:49 UTC, subhamkrai commented on Documentation/helm-ceph-cluster.md
> +Installs a [Ceph](https://ceph.io/) cluster on Rook using the [Helm](https://helm.sh) package manager.
```suggestion
Install a Rook Ceph cluster using the [Helm](https://helm.sh) package manager.
```

2021-06-09 04:49 UTC, subhamkrai commented on Documentation/helm-ceph-cluster.md
> +If the operator was installed in a non-default location, the namespace of the *Rook Operator* installed
```suggestion
If the operator was installed in a non-default location, the namespace of the **Rook Operator** installed
```

2021-06-09 17:58 UTC, travisn requested changes
Just a few small suggestions, thanks!

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +## Warning
```suggestion
## Experimental
```

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +This chart is released to the community for testing but is considered in development. It is currently only available on the `master` channel.
```suggestion
This chart is released to the community for testing but is considered in experimental. It is currently only available on the `master` channel.
```

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +### Development Build
Let's remove this section for this experimental documentation, and just focus on the master channel.

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +helm repo add rook-release https://charts.rook.io/master
Shall we call it rook-master?
```suggestion
helm repo add rook-master https://charts.rook.io/master
```

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +The master channel is the most recent release of Rook that includes in development features.
```suggestion
The master channel is the most recent release of Rook that includes experimental features.
```

2021-06-09 17:58 UTC, travisn commented on Documentation/helm-ceph-cluster.md
> +Once released, the repository should be updated to the `release` channel if you wish to switch to the stable branch.
Helm will allow changing the channel, right? Hopefully we can confirm this won't be an issue later.
```suggestion
Once released (targeted for v1.7), the repository should be updated to the `release` channel at that time for the stable branch.
```

2021-06-10 23:21 UTC, travisn approved these changes

2021-06-10 23:22 UTC, travisn commented
I made a few small changes to the doc, we can review later based on feedback, thanks.

2021-06-10 23:51 UTC, merged