ceph: do not fail prepareOSD job if devices are not passed
rook/rook pull request #8098
Opened 2021-06-09 17:58 UTC by degorenko

If devices are not specified for node return empty desired devices
list and do not fail prepareOSD job.

Closes: #8097
Signed-off-by: Denis Egorenko degorenko@mirantis.com

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-09 18:35 UTC, travisn requested changes
Could you add a unit test case for this? I see a few examples in osd_test.go calling `parseDevices()`, so hopefully it is simple.

2021-06-10 11:43 UTC, leseb approved these changes

2021-06-10 11:50 UTC, sp98 commented
multiple `signed-off-by` in the commit message.

2021-06-10 17:40 UTC, travisn approved these changes

2021-06-10 17:41 UTC, merged