ceph: initialise httpclient for bucketchecker and objectstoreuser
rook/rook pull request #8139
Opened 2021-06-17 07:49 UTC by thotz

**Description of your changes:**
For the TLS communication in AdminOps Api, httpclient is required and
filled with TLS certs. But it is set to nil pointer in `buckethealthchecker` and 
`cephobjectstoreuser`.

Thanks @Krast76 finding the issue even proposing the fix.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #8132

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-17 21:10 UTC, travisn requested changes

2021-06-17 21:10 UTC, travisn commented on pkg/operator/ceph/object/health.go
> +		Timeout: time.Second * 15,
How about defining a const for the 15 seconds? It's used in a few places.

2021-06-18 16:01 UTC, travisn commented on pkg/operator/ceph/object/config.go
> +	HttpTimeOut                    = 15
How about this? Then the other places wouldn't need to multiply by time.Second.
```suggestion
	HttpTimeOut                    = time.Second * 15
```

2021-06-21 12:07 UTC, leseb approved these changes

2021-06-21 13:42 UTC, travisn approved these changes

2021-06-21 13:42 UTC, merged