docs: clarify resource documentation
rook/rook pull request #8145
Opened 2021-06-17 20:08 UTC by pavilalopes

Move MDS related information from the Cluster to the Filesystem document.
Document how resource requests influence Ceph configuration keys.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-17 21:17 UTC, travisn requested changes
Just a tiny suggestion, thanks for the doc update!

2021-06-17 21:17 UTC, travisn commented on Documentation/ceph-filesystem-crd.md
> +If the memory resource is declared Rook will automatically set the MDS configuration `mds_cache_memory_limit`. The configuration value is calculated with the aim that the actual MDS memory consumptio
Until we fix #8143...
```suggestion
If the memory resource limit is declared Rook will automatically set the MDS configuration `mds_cache_memory_limit`. The configuration value is calculated with the aim that the actual MDS memory consumption remains consistent with the MDS pods' resource declaration.
```

2021-06-18 08:26 UTC, pavilalopes commented on Documentation/ceph-filesystem-crd.md
> +If the memory resource is declared Rook will automatically set the MDS configuration `mds_cache_memory_limit`. The configuration value is calculated with the aim that the actual MDS memory consumptio
Done

2021-06-18 13:57 UTC, travisn approved these changes

2021-06-18 13:57 UTC, merged