ceph: enable debug for adminops client if the rook loglevel <= debug
rook/rook pull request #8208
Opened 2021-06-28 06:27 UTC by thotz

The debug for adminOps client can be enabled by setting `Debug` flag.
In this PR, it is enabled for OBC and cephobjectstore not healthchecker.
Also add similar changes while calling `NewS3Agent` in the bucket
provisioner code path.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-06-28 08:15 UTC, leseb requested changes
Funny, I have a similar patch locally that I haven't pushed yet, you beat me to it :)

2021-06-28 08:15 UTC, leseb commented on pkg/operator/ceph/object/bucket/provisioner.go
> +	rookLogLevel, _ := k8sutil.GetOperatorSetting(p.context.Clientset, opcontroller.OperatorSettingConfigMapName, "ROOK_LOG_LEVEL", "INFO")
We can just check like so instead of fetching the cm

`if logger.LevelAt(capnslog.DEBUG) {`

2021-06-28 08:15 UTC, leseb commented on pkg/operator/ceph/object/user/controller.go
> +	if rookLogLevel == "DEBUG" || rookLogLevel == "TRACE" {
ditto

2021-06-29 09:15 UTC, leseb approved these changes

2021-06-29 09:23 UTC, leseb commented
Just to answer anyone who might have concerns, turning on DEBUG on the API does not leak connection credentials 😌

2021-06-30 09:32 UTC, leseb reviewed
Why not the healthchecker btw? /pkg/operator/ceph/object/health.go

2021-06-30 13:33 UTC, leseb requested changes
Why not the healthchecker btw? /pkg/operator/ceph/object/health.go

2021-07-01 06:12 UTC, thotz commented
> Why not the healthchecker btw? /pkg/operator/ceph/object/health.go

Done

2021-07-01 07:34 UTC, leseb approved these changes

2021-07-05 08:22 UTC, merged