ceph: add support for tls certs via k8s tls secrets for rgw
rook/rook pull request #8243
Opened 2021-07-02 13:08 UTC by thotz

**Description of your changes:**
With this PR the RGW can accept TLS certs as K8s TLS secrets

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #2079

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-07-05 09:42 UTC, leseb requested changes

2021-07-05 09:42 UTC, leseb commented on pkg/operator/ceph/object/spec.go
> +		if c.rgwTLSSecretType() == "" {
use switch case?

2021-07-05 09:42 UTC, leseb commented on pkg/operator/ceph/object/spec.go
> +	ctx := context.TODO()
you can directly cast `context.TODO()` below, no need for a new variable.

2021-07-05 09:42 UTC, leseb commented on pkg/operator/ceph/object/spec.go
> +	if rgwTlsSecret != nil {
Why not return an error since the caller can handle errors?

2021-07-06 09:13 UTC, leseb requested changes
Please add a release note

2021-07-06 11:48 UTC, leseb approved these changes

2021-07-06 14:56 UTC, merged

2021-07-06 15:00 UTC, oaudry commented
great job ! many thx