ceph: define specific ServceAccount/RBAC for ceph osd purge job
rook/rook pull request #8340
Opened 2021-07-20 13:51 UTC by ashangit

**Description of your changes:**

Currently ceph osd purge job rely on rook-ceph-system service account which is only created on the rook operator namespace
When multiple clusters are deployed on distinct namespace the ceph osd purge failed to run as the service account is not available
Creating a specific service account rook-ceph-purge-osd with appropriate rights on each cluster namespace and operator namespace to still manage case where cluster is installed along side the operator

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-07-20 15:02 UTC, travisn requested changes
@ashangit The changes look good, just a couple suggestions:
- Can you comment on where you have tested the changes? With the rbac in the two helm charts, and the non-helm manifests, there are at least three places to test it out. The CI would cover creation of the rbac in all three of those scenarios, just not whether the job actually runs.
- See the commitlint bot regarding the commit message formatting

2021-07-21 11:45 UTC, ashangit commented
Changes have been tested

- First test on our sandbox kube clusters relying on helm deployment for operator and cephclusters
  2 ceph clusters are deployed on a dedicated namespace and a 3rd one is deployed on same namespace than the operator
  Job deletion has well run and deleted the appropriate osd for the 3 clusters
  
- Another test has been done on a dev cluster (virtualbox VM with 1 mon/3 osds/1 operator/1 tooolbax running on it) relying on non-helm manifest (crds.yaml, common.yaml, operator.yaml, toolbox.yaml and cluster.yaml deployed without any change from cluster/examples/kubernetes/ceph)
  Job deletion has also well deleted the down osd

2021-07-21 15:24 UTC, travisn commented
@ashangit Could you just rebase and force push again? There was a fix we need to pick up for the CI.

2021-07-22 08:12 UTC, sp98 approved these changes

2021-07-22 13:15 UTC, travisn approved these changes

2021-07-22 13:15 UTC, merged