ceph: mgr dashboard service support externalIPs.
rook/rook pull request #8398
Opened 2021-07-27 13:18 UTC by devlikai

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-07-27 13:22 UTC, leseb requested changes
https://rook.io/docs/rook/master/development-flow.html#commit-structure

2021-07-27 13:41 UTC, travisn requested changes

2021-07-27 13:41 UTC, travisn commented on pkg/operator/ceph/cluster/mgr/spec.go
> +		{Name: "ROOK_DASHBOARD_EXTERNAL_IPS", Value: externalIps},
With the `strings.Join()` we shouldn't need the for loop above
```suggestion
		{Name: "ROOK_DASHBOARD_EXTERNAL_IPS", Value: strings.Join(externalIps, ",")},
```

2021-07-27 13:41 UTC, travisn commented on pkg/operator/ceph/cluster/mgr/mgr.go
> +			if corev1.ServiceTypeClusterIP == svc.Spec.Type {
Does this code block have any side effect? If it's just logging, seems like we don't need it?

2021-07-27 13:41 UTC, travisn commented on pkg/apis/ceph.rook.io/v1/types.go
> +	ExternalIps []string `json:"externalIPs,omitempty"`
Let's add this in the `DashboardSpec` instead of the `ClusterSpec`

2021-07-27 13:41 UTC, travisn commented on cmd/rook/ceph/mgr.go
> +				clusterSpec.Dashboard.ExternalIps = append(clusterSpec.Dashboard.ExternalIps, ip)
You could just assign the results of `Split()` directly and no need for the loop, right?
```suggestion
		clusterSpec.Dashboard.ExternalIps = strings.Split(clusterSpec.Dashboard.ExternalIps, ",")
```

2021-07-27 13:41 UTC, travisn commented on pkg/apis/ceph.rook.io/v1/types.go
> +	ExternalIps []string `json:"externalIPs,omitempty"`
You'll need to run `make codegen` and `make crds` to generate the artifacts needed for this setting.

2021-09-09 13:50 UTC, leseb commented
@devlikai any plan to resume this?

2021-10-01 17:02 UTC, BlaineEXE commented
The commits should have an explanatory body message. Ideally, this would explain the scenario that is enabled by these changes and how it allows the scenario. Commits should probably be squashed together and have a signed-off-by line. Also, do not end a commit subject in punctuation.

2021-11-14 20:01 UTC, closed without merging