docs: added information about which pods will have multus annotations
rook/rook pull request #8415
Opened 2021-07-28 15:52 UTC by rohan47

**Description of your changes:**
Added information about which pods will have multus annotations.

**Which issue is resolved by this Pull Request:**
Resolves #7563 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-07-29 19:47 UTC, travisn requested changes

2021-07-29 19:47 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +Rook Ceph Operator will not have any networks attached.
Does this mean the operator is not expected to need any networks attached? Then how does the operator connect to the cluster to run ceph commands? I'm just not clear how all the networks are connected.

2021-07-29 19:47 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +Only OSD pods will have Public as well as Cluster networks attached. Rest of the Ceph component pods and CSI pods will have Only Public network attached.
```suggestion
Only OSD pods will have both Public and Cluster networks attached. The rest of the Ceph component pods and CSI pods will only have the Public network attached.
```

2021-08-03 16:41 UTC, leseb commented
@rohan47 what's the update here?

2021-08-03 17:05 UTC, rohan47 commented
> @rohan47 what's the update here?

Updated the PR

2021-08-03 17:58 UTC, travisn requested changes

2021-08-03 17:58 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +Rook Ceph Operator will not have any networks attached as it proxies the required commands via a [sidecar container](https://github.com/rook/rook/pull/8272) in the mgr pod.
I'd suggest no need to link the PR
```suggestion
Rook Ceph Operator will not have any networks attached as it proxies the required commands via a sidecar container in the mgr pod.
```

2021-08-03 17:58 UTC, travisn commented on Documentation/ceph-cluster-crd.md
> +#### Known issues with multus:
```suggestion
#### Known issues with multus
```

2021-08-03 18:04 UTC, travisn approved these changes

2021-08-03 18:05 UTC, merged