ceph: remove pool id from the peer
rook/rook pull request #8456
Opened 2021-08-02 17:06 UTC by leseb

We don't need to put this information in the token.
It's not useful and not used anywhere.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-08-02 17:50 UTC, travisn requested changes

2021-08-02 17:50 UTC, travisn commented on pkg/operator/ceph/controller/mirror_peer.go
> +		boostrapToken, err = expandBootstrapPeerToken(ctx, clusterInfo, boostrapToken)
ineffectual assignment since removing this

2021-08-03 07:42 UTC, Madhu-1 commented on pkg/operator/ceph/controller/mirror_peer.go
> +		boostrapToken, err = expandBootstrapPeerToken(ctx, clusterInfo, boostrapToken)
at line 73 : `ineffectual assignment to name (ineffassign)` warning

2021-08-03 07:48 UTC, Madhu-1 approved these changes

2021-08-03 08:49 UTC, sp98 approved these changes

2021-08-03 13:17 UTC, travisn approved these changes

2021-08-03 13:18 UTC, merged