build: update go fmt version
rook/rook pull request #8473
Opened 2021-08-04 06:57 UTC by subhamkrai

till now we were using older go fmt version(1.11).
From now, go fmt version will be same as golang version

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-08-04 08:20 UTC, leseb requested changes

2021-08-04 08:20 UTC, leseb commented on build/makelib/golang.mk
>  # we use a consistent version of gofmt even while running different go compilers.
I think this comment can go away now.

2021-08-04 14:47 UTC, subhamkrai commented on build/makelib/golang.mk
>  # we use a consistent version of gofmt even while running different go compilers.
removed

2021-08-04 15:24 UTC, travisn approved these changes

2021-08-05 15:55 UTC, leseb approved these changes

2021-08-05 16:33 UTC, merged