use serviceAccountName as the key in ceph csi templates
rook/rook pull request #8546
Opened 2021-08-17 04:09 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-08-17 05:17 UTC, humblec commented
@Madhu-1 ptal. Thanks

2021-08-17 05:18 UTC, Madhu-1 approved these changes

2021-08-17 06:53 UTC, sp98 commented
A bit more context about this change in the PR description and PR commit message description would be helpful.

2021-08-17 09:57 UTC, humblec commented
> A bit more context about this change in the PR description and PR commit message description would be helpful.

@sp98 `serviceAccountName` is the replacement for deprecated `serviceAccount`. I thought its pretty explicit or known change.  :)

2021-08-17 10:02 UTC, humblec commented
> > A bit more context about this change in the PR description and PR commit message description would be helpful.
> 
> @sp98 `serviceAccountName` is the replacement for deprecated `serviceAccount`. I thought its pretty explicit or known change. :), regardless I added some reference in the PR description.. Thanks :+1:

2021-08-17 10:40 UTC, subhamkrai requested changes
@humblec please update in commit/pr description message in which Kubernetes version it is depreciated/removed. Anyways, more description always helps.
Thanks for the link, but I didn't get the idea when it is depreciated/removed

2021-08-17 17:32 UTC, travisn commented
@humblec Do you know in which version this new `serviceAccountName` property was added and in which version the `serviceAccount` will be removed? In any case, looks like the CI is passing from K8s 1.16 through 1.22, so it should be fine.

2021-08-18 03:29 UTC, humblec commented
> @humblec Do you know in which version this new `serviceAccountName` property was added and in which version the `serviceAccount` will be removed? In any case, looks like the CI is passing from K8s 1.16 through 1.22, so it should be fine.

@travisn since `core->v1` (https://pkg.go.dev/k8s.io/api/core/v1), it is actually `serviceAccountName` is the  correct key in the pod spec. however v1 api server do an internal mapping if `serviceAccount` is used, so it works.

https://docs.openshift.com/container-platform/3.11/rest_api/core/podtemplate-core-v1.html

2021-08-18 03:49 UTC, subhamkrai approved these changes

2021-08-18 04:41 UTC, merged