ceph: fix error in <ceph orch device ls> test
rook/rook pull request #8549
Opened 2021-08-17 10:17 UTC by jmolmo

Rook orchestrator is going to use PVs as _devices_ for OSDs.

These PVs must use one storage class present in the cluster and configured properly in the manager.
With this change we include this new requirement in the Rook manager module integration test.

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

**Description of your changes:**

Resolves #8530

2021-08-17 13:33 UTC, travisn requested changes
The device test is fixed, but now the status test is still failing:

```
=== RUN   TestCephMgrSuite/TestStatus
2021-08-17 10:30:13.749964 I | integrationTest: Testing .... <ceph orch status>
2021-08-17 10:30:13.749985 D | exec: Running command: kubectl exec -i rook-ceph-tools-78cdfd976c-hbxp6 -n mgr-ns -- timeout 15 ceph orch status --connect-timeout=15
2021-08-17 10:30:28.981536 W | installer: Error executing command "ceph": <exit status 124>
    ceph_mgr_test.go:217: 
        	Error Trace:	ceph_mgr_test.go:217
        	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0004c1248), Stderr:[]uint8{0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x20, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x65, 0x78, 0x69, 0x74, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x31, 0x32, 0x34, 0xa}}
        	Test:       	TestCephMgrSuite/TestStatus
2021-08-17 10:30:28.981949 I | integrationTest: output = . command terminated with exit code 124
    ceph_mgr_test.go:220: 
        	Error Trace:	ceph_mgr_test.go:220
        	Error:      	Not equal: 
        	            	expected: ". command terminated with exit code 124"
        	            	actual  : "Backend: rook\nAvailable: Yes"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1,2 @@
        	            	-. command terminated with exit code 124
        	            	+Backend: rook
        	            	+Available: Yes
        	Test:       	TestCephMgrSuite/TestStatus
```

2021-08-17 13:33 UTC, travisn commented on tests/integration/ceph_mgr_test.go
> +			logger.Infof("Storage class <%q> set in manager config ", storageClassName)
```suggestion
			logger.Infof("Storage class %q set in manager config ", storageClassName)
```

2021-08-17 13:33 UTC, travisn commented on tests/integration/ceph_mgr_test.go
> +			logger.Errorf("Error configuring local storage class in manager config: %q", err)
```suggestion
			assert.Fail(s.T(), "Error configuring local storage class in manager config: %q", err)
```

2021-08-17 13:33 UTC, travisn commented on tests/integration/ceph_mgr_test.go
> +		logger.Errorf("Error creating local storage class: %q ", err)
```suggestion
		assert.Fail(s.T(), "Error creating local storage class: %q ", err)
```

2021-08-18 12:24 UTC, jmolmo commented
> The device test is fixed, but now the status test is still failing:
> 
> ```
> === RUN   TestCephMgrSuite/TestStatus
> ...
> 2021-08-17 10:30:28.981949 I | integrationTest: output = . command terminated with exit code 124

> ```

I have executed the test 20 times, and this error appears only in a couple of times .. in different tests. I need to investigate more... but it seems that "ceph" commands are not working in random moments.. i haven't found any error in mgr/mon logs ... so for the moment no idea about what can be the root cause.

2021-08-18 13:38 UTC, travisn commented
> I have executed the test 20 times, and this error appears only in a couple of times .. in different tests. I need to investigate more... but it seems that "ceph" commands are not working in random moments.. i haven't found any error in mgr/mon logs ... so for the moment no idea about what can be the root cause.

Ok let's go ahead and merge this and we can investigate the ceph command issue separately, but at least it is not severe if the frequency is that low.

2021-08-18 13:38 UTC, travisn approved these changes

2021-08-18 13:38 UTC, merged