ceph: add opa config options to ObjectStoreSpec
rook/rook pull request #8731
Opened 2021-09-16 06:02 UTC by thotz

**Description of your changes:**
This PR adds the options in ObjectStore CRD for configuring OPA
authentication with RGW.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-09-16 14:14 UTC, BlaineEXE commented
@thotz Is this related to a BZ or feature request?

2021-09-16 17:03 UTC, travisn commented
> @thotz Is this related to a BZ or feature request?

Yes it would be helpful just to have more background on requirements for new features, thanks.

2021-09-17 06:42 UTC, thotz commented
> > @thotz Is this related to a BZ or feature request?
> 
> Yes it would be helpful just to have more background on requirements for new features, thanks.

The request was from openshift OPA team via mail, So I created Rook Issue #8737 and mentioned it in the Commit message of this PR

2021-09-17 09:16 UTC, leseb requested changes

2021-09-17 09:16 UTC, leseb commented on pkg/apis/ceph.rook.io/v1/types.go
> +	URL string `json:"url,omitempty"`
```suggestion
	URL string `json:"url"`
```

Since this is required.

2021-09-17 09:16 UTC, leseb commented on pkg/apis/ceph.rook.io/v1/types.go
> +	Token string `json:"token,omitempty"`
```suggestion
	Token string `json:"token"`
```

2021-09-17 09:16 UTC, leseb commented on pkg/operator/ceph/object/spec_test.go
> +	podTemplate.RunFullSuite(cephconfig.RgwType, "default", "rook-ceph-rgw", "mycluster", "quay.io/ceph/ceph:myversion",
What is this actually testing?

2021-09-17 09:16 UTC, leseb commented on pkg/operator/ceph/object/spec.go
> +					strconv.FormatBool(*c.store.Spec.Security.OpenPolicyAgentService.VerifySSL)))
Is the bool pointer really necessary? If it's not required why not just let the default. `false`?

2021-09-17 18:26 UTC, BlaineEXE commented
> > > @thotz Is this related to a BZ or feature request?
> > 
> > 
> > Yes it would be helpful just to have more background on requirements for new features, thanks.
> 
> The request was from openshift OPA team via mail, So I created Rook Issue #8737 and mentioned it in the Commit message of this PR

We need to know how to prioritize incoming feature requests. A new Rook issue is good, but let's get a BZ (or Jira?) against OCS/ODF that PM can prioritize. Since this is a cross-team request, we have to have an understanding of who needs it, when they need it, and why they need it. We cannot guarantee that Rook upstream can spend time on under-the-table requests like this.

2021-09-20 10:30 UTC, thotz commented
> > > > @thotz Is this related to a BZ or feature request?
> > > 
> > > 
> > > Yes it would be helpful just to have more background on requirements for new features, thanks.
> > 
> > 
> > The request was from openshift OPA team via mail, So I created Rook Issue #8737 and mentioned it in the Commit message of this PR
> 
> We need to know how to prioritize incoming feature requests. A new Rook issue is good, but let's get a BZ (or Jira?) against OCS/ODF that PM can prioritize. Since this is a cross-team request, we have to have an understanding of who needs it, when they need it, and why they need it. We cannot guarantee that Rook upstream can spend time on under-the-table requests like this.

I have opened a Jira ticket https://issues.redhat.com/browse/RGW-173 in the RGW kanban board as beginning, try to involve more people to get more understanding about the plan on the ticket

2021-09-20 13:01 UTC, leseb reviewed
Also see my comment about having a new entry like `IdentityManagement` to have OPA and LDAP under it

2021-09-20 19:31 UTC, travisn requested changes

2021-09-20 19:31 UTC, travisn commented on Documentation/ceph-object-store-crd.md
> +  opa:
Let's avoid non-obvious acronyms in the CR property names
```suggestion
  openPolicyAgent:
```

2021-09-20 19:31 UTC, travisn commented on Documentation/ceph-object-store-crd.md
> +The config options include url, token for the OPA service. The TLS certs can be passed with help `caBundleRef`. For more details w.r.t RGW, please refer [Ceph OPA documentation](https://docs.ceph.com
```suggestion
The config options include url, token for the OPA service. The TLS certs can be passed with help `caBundleRef`. For more details, please refer to the [Ceph OPA documentation](https://docs.ceph.com/en/latest/radosgw/opa/).
```

2021-09-20 19:31 UTC, travisn commented on pkg/apis/ceph.rook.io/v1/types.go
> +	VerifySSL *bool `json:"verifySSL,omitempty"`
Is the behavior of "not set" and "false" the same? If so, how about removing the pointer for simplicity? 
```suggestion
	VerifySSL bool `json:"verifySSL,omitempty"`
```

2021-09-20 19:31 UTC, travisn commented on pkg/apis/ceph.rook.io/v1/types.go
> +	// Token is the token for the OPA
```suggestion
	// Token for the OPA
```

2021-09-24 17:17 UTC, BlaineEXE commented
I think https://github.com/rook/rook/pull/8579 is the more high priority item that we definitely have in our requirements for ODF 4.10. Let's focus on that PR first.

2022-06-24 05:15 UTC, thotz commented
I am closing this PR since there is no more interest wrt to this feature atm, not planning to work on it anytime soon. I will open once again when priority changes

2022-06-24 05:15 UTC, thotz commented
I am closing this PR since there is no more interest wrt to this feature atm, not planning to work on it anytime soon. I will open once again when priority changes

2022-06-24 05:15 UTC, closed without merging