ceph: modify CephFS provisioner permission
rook/rook pull request #8739
Opened 2021-09-17 08:17 UTC by Madhu-1

**Description of your changes:**
Like RBD, the CephFS provisioner pod need not run as privileged. as it's not doing any operation like plugin pods which does mounting and unmounting removing the permissions for the same.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-09-17 09:06 UTC, leseb approved these changes

2021-09-17 09:09 UTC, leseb requested changes
After thoughts, I see you have a similar change in https://github.com/ceph/ceph-csi/pull/2518. It's "a lot" of back and forth.
What if ceph-csi would provide its yaml files as code? So that Rook, when pulling a new version for ceph-csi (through go modules) can also get the updated yamls?

2021-09-17 09:15 UTC, Madhu-1 commented
> After thoughts, I see you have a similar change in [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518). It's "a lot" of back and forth.
> What if ceph-csi would provide its yaml files as code? So that Rook, when pulling a new version for ceph-csi (through go modules) can also get the updated yamls?

We don't have such a mechanism in cephcsi and we are not exposing any functions for external consumptions.

2021-09-17 09:26 UTC, Madhu-1 commented
> > > After thoughts, I see you have a similar change in [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518). It's "a lot" of back and forth.
> > > What if ceph-csi would provide its yaml files as code? So that Rook, when pulling a new version for ceph-csi (through go modules) can also get the updated yamls?
> > 
> > 
> > We don't have such a mechanism in cephcsi and we are not exposing any functions for external consumptions.
> 
> Yes but you do have an examples directory right? And it needs to be synced with Rook all the time, right?

Yes correct

2021-09-17 09:31 UTC, leseb commented
> > > > After thoughts, I see you have a similar change in [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518). It's "a lot" of back and forth.
> > > > What if ceph-csi would provide its yaml files as code? So that Rook, when pulling a new version for ceph-csi (through go modules) can also get the updated yamls?
> > > 
> > > 
> > > We don't have such a mechanism in cephcsi and we are not exposing any functions for external consumptions.
> > 
> > 
> > Yes but you do have an examples directory right? And it needs to be synced with Rook all the time, right?
> 
> Yes correct

Honestly, it feels like an annoyance to me. @BlaineEXE @travisn thoughts?

2021-09-17 17:42 UTC, travisn approved these changes

2021-09-17 17:46 UTC, travisn commented
> > > > > After thoughts, I see you have a similar change in [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518). It's "a lot" of back and forth.
> > > > > What if ceph-csi would provide its yaml files as code? So that Rook, when pulling a new version for ceph-csi (through go modules) can also get the updated yamls?
> > > > 
> > > > 
> > > > We don't have such a mechanism in cephcsi and we are not exposing any functions for external consumptions.
> > > 
> > > 
> > > Yes but you do have an examples directory right? And it needs to be synced with Rook all the time, right?
> > 
> > 
> > Yes correct
> 
> Honestly, it feels like an annoyance to me. @BlaineEXE @travisn thoughts?

This would introduce a code dependency between rook and ceph-csi that we don't have today, right? But removing the duplication between repos would certainly be convenient.

2021-09-17 23:03 UTC, BlaineEXE commented
I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?

2021-09-17 23:15 UTC, travisn commented
> I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?

Actually, how would this change work? If the manifests are embedded in the CSI image rather than the Rook image, how would Rook create them?

2021-09-20 06:56 UTC, leseb commented
> > I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?
> 
> Actually, how would this change work? If the manifests are embedded in the CSI image rather than the Rook image, how would Rook create them?

If manifest are stored with embed, the code still needs to parse and unmarshal in a known type, eg: `DaemonSet`

2021-09-20 21:25 UTC, travisn commented
> > > I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?
> > 
> > 
> > Actually, how would this change work? If the manifests are embedded in the CSI image rather than the Rook image, how would Rook create them?
> 
> If manifest are stored with embed, the code still needs to parse and unmarshal in a known type, eg: `DaemonSet`

But if rook is going to read the manifest stored with embed, doesn't it have to be embedded in the rook binary? In that case I don't see how we can move the manifest to the csi repo

2021-09-21 04:33 UTC, Madhu-1 commented
> > > > I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?
> > > 
> > > 
> > > Actually, how would this change work? If the manifests are embedded in the CSI image rather than the Rook image, how would Rook create them?
> > 
> > 
> > If manifest are stored with embed, the code still needs to parse and unmarshal in a known type, eg: `DaemonSet`
> 
> But if rook is going to read the manifest stored with embed, doesn't it have to be embedded in the rook binary? In that case I don't see how we can move the manifest to the csi repo

AFAIK yes we need to embed this to the Rook binary. again if we need that its adds more inter dependency between Rook and CSI releases and it's more work in cephcsi to support this one.

2021-09-21 13:28 UTC, leseb commented
> > > > > I think we wouldn't need any code synchronization if the templates CSI needed were stored using Go 1.16's `embed` file feature, right?
> > > > 
> > > > 
> > > > Actually, how would this change work? If the manifests are embedded in the CSI image rather than the Rook image, how would Rook create them?
> > > 
> > > 
> > > If manifest are stored with embed, the code still needs to parse and unmarshal in a known type, eg: `DaemonSet`
> > 
> > 
> > But if rook is going to read the manifest stored with embed, doesn't it have to be embedded in the rook binary? In that case I don't see how we can move the manifest to the csi repo
> 
> AFAIK yes we need to embed this to the Rook binary. again if we need that its adds more inter dependency between Rook and CSI releases and it's more work in cephcsi to support this one.

`embed` is only to put the template `in` the binary but the template still remains as a file within the package itself. So I believe that if CSI provides the template as code in its API it should work. Rook does not need to read the template file but the object like `corev1.DaemonSet`.

2021-09-21 13:37 UTC, leseb approved these changes
LGTM for now, will bring the topic in the next CSI meeting.

2021-09-21 13:42 UTC, travisn commented
@Madhu-1 The file test is failing consistently in the smoke suite:
```
2021-09-17 08:38:14.317974 I | testutil: Giving up waiting for pod file-test in namespace smoke-ns to be running
    ceph_base_file_test.go:319: 
        	Error Trace:	ceph_base_file_test.go:319
        	            				ceph_base_file_test.go:262
        	            				ceph_smoke_test.go:127
        	Error:      	Should be true
        	Test:       	TestCephSmokeSuite/TestFileStorage_SmokeTest
        	Messages:   	make sure file-test pod is in running state
```

2021-09-21 13:43 UTC, travisn requested changes
CI needs investigation

2021-09-21 14:30 UTC, Madhu-1 commented
> CI needs investigation

Am able to create PVC and mount to application pod locally with this change

```
[root@dhcp53-170 ceph]# kubectl get pvc
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
cephfs-pvc-1   Bound    pvc-21ab0a8c-db0d-4aba-ae9a-45f27bd4f653   1Gi        RWO            rook-cephfs       3m51s
rbd-pvc-test   Bound    pvc-9a2db094-d507-4664-959c-b6bb2a5c1bda   8Gi        RWO            rook-ceph-block   8h
[root@dhcp53-170 ceph]# 
[root@dhcp53-170 ceph]# kubectl get po
NAME                 READY   STATUS    RESTARTS   AGE
csicephfs-demo-pod   1/1     Running   0          26s

[root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i privileged
[root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i secu
      securityContext: {}
[root@dhcp53-170 ceph]# 
```

Let me try to run CI locally.

2021-09-21 14:36 UTC, Madhu-1 commented
> > > CI needs investigation
> > 
> > 
> > Am able to create PVC and mount to application pod locally with this change
> > ```
> > [root@dhcp53-170 ceph]# kubectl get pvc
> > NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> > cephfs-pvc-1   Bound    pvc-21ab0a8c-db0d-4aba-ae9a-45f27bd4f653   1Gi        RWO            rook-cephfs       3m51s
> > rbd-pvc-test   Bound    pvc-9a2db094-d507-4664-959c-b6bb2a5c1bda   8Gi        RWO            rook-ceph-block   8h
> > [root@dhcp53-170 ceph]# 
> > [root@dhcp53-170 ceph]# kubectl get po
> > NAME                 READY   STATUS    RESTARTS   AGE
> > csicephfs-demo-pod   1/1     Running   0          26s
> > 
> > [root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i privileged
> > [root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i secu
> >       securityContext: {}
> > [root@dhcp53-170 ceph]# 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me try to run CI locally.
> 
> FYI, @Madhu-1 you can log into GitHub action runner

```
ssh 4Db8VxxQtXZPbbVqRkAAycKSR@sfo2.tmate.io
The session host disconnected 4 days ago.
Hopefully it will reconnect soon. You may try again later.
Connection to sfo2.tmate.io closed.
```

Let me try to rerun the test tomorrow and see

2021-09-21 14:39 UTC, subhamkrai commented
> > > > CI needs investigation
> > > 
> > > 
> > > Am able to create PVC and mount to application pod locally with this change
> > > ```
> > > [root@dhcp53-170 ceph]# kubectl get pvc
> > > NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> > > cephfs-pvc-1   Bound    pvc-21ab0a8c-db0d-4aba-ae9a-45f27bd4f653   1Gi        RWO            rook-cephfs       3m51s
> > > rbd-pvc-test   Bound    pvc-9a2db094-d507-4664-959c-b6bb2a5c1bda   8Gi        RWO            rook-ceph-block   8h
> > > [root@dhcp53-170 ceph]# 
> > > [root@dhcp53-170 ceph]# kubectl get po
> > > NAME                 READY   STATUS    RESTARTS   AGE
> > > csicephfs-demo-pod   1/1     Running   0          26s
> > > 
> > > [root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i privileged
> > > [root@dhcp53-170 ceph]# kubectl get deployment -nrook-ceph csi-cephfsplugin-provisioner -oyaml |grep -i secu
> > >       securityContext: {}
> > > [root@dhcp53-170 ceph]# 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me try to run CI locally.
> > 
> > 
> > FYI, @Madhu-1 you can log into GitHub action runner
> 
> ```
> ssh 4Db8VxxQtXZPbbVqRkAAycKSR@sfo2.tmate.io
> The session host disconnected 4 days ago.
> Hopefully it will reconnect soon. You may try again later.
> Connection to sfo2.tmate.io closed.
> ```
Yes, it has timeout of 1 hr.
> 
> Let me try to rerun the test tomorrow and see

2021-09-22 07:43 UTC, Madhu-1 commented
```
runner@fv-az120-915:~/work/rook/rook$ kubectl get po -nsmoke-ns
NAME                                                     READY   STATUS      RESTARTS   AGE
rook-ceph-crashcollector-fv-az120-915-68d566c77f-fcvvh   1/1     Running     0          112s
rook-ceph-mgr-a-78c6ff567c-5z4j8                         1/1     Running     0          10m
rook-ceph-mon-a-68bbf96d58-qdc54                         1/1     Running     0          11m
rook-ceph-mon-b-74978dc6dd-szfqh                         1/1     Running     0          11m
rook-ceph-mon-c-85896c99b6-g2pwg                         1/1     Running     0          11m
rook-ceph-osd-0-5f9c94f77d-4jfsb                         1/1     Running     0          9m21s
rook-ceph-osd-prepare-fv-az120-915-9zb57                 0/1     Completed   0          10m
rook-ceph-tools-7865b9c9f6-tdgcl                         1/1     Running     0          10m
runner@fv-az120-915:~/work/rook/rook$ kubectl exec -it rook-ceph-tools-7865b9c9f6-tdgcl -nsmoke-ns -- sh
sh-4.4# ceph -s
  cluster:
    id:     7ae97632-c490-4967-801e-a773d04ae288
    health: HEALTH_ERR
            1 filesystem is offline
            1 filesystem is online with fewer MDS than max_mds
            3 pool(s) have no replicas configured
 
  services:
    mon: 3 daemons, quorum a,b,c (age 11m)
    mgr: a(active, since 10m)
    mds: 0/0 daemons up
    osd: 1 osds: 1 up (since 9m), 1 in (since 11m)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 192 pgs
    objects: 3 objects, 0 B
    usage:   7.9 MiB used, 14 GiB / 14 GiB avail
    pgs:     192 active+clean
 
sh-4.4#
```
ceph cluster is in error state. @travisn @subhamkrai anyone can help here?

2021-09-22 07:52 UTC, subhamkrai commented
> ```
> runner@fv-az120-915:~/work/rook/rook$ kubectl get po -nsmoke-ns
> NAME                                                     READY   STATUS      RESTARTS   AGE
> rook-ceph-crashcollector-fv-az120-915-68d566c77f-fcvvh   1/1     Running     0          112s
> rook-ceph-mgr-a-78c6ff567c-5z4j8                         1/1     Running     0          10m
> rook-ceph-mon-a-68bbf96d58-qdc54                         1/1     Running     0          11m
> rook-ceph-mon-b-74978dc6dd-szfqh                         1/1     Running     0          11m
> rook-ceph-mon-c-85896c99b6-g2pwg                         1/1     Running     0          11m
> rook-ceph-osd-0-5f9c94f77d-4jfsb                         1/1     Running     0          9m21s
> rook-ceph-osd-prepare-fv-az120-915-9zb57                 0/1     Completed   0          10m
> rook-ceph-tools-7865b9c9f6-tdgcl                         1/1     Running     0          10m
> runner@fv-az120-915:~/work/rook/rook$ kubectl exec -it rook-ceph-tools-7865b9c9f6-tdgcl -nsmoke-ns -- sh
> sh-4.4# ceph -s
>   cluster:
>     id:     7ae97632-c490-4967-801e-a773d04ae288
>     health: HEALTH_ERR
>             1 filesystem is offline
>             1 filesystem is online with fewer MDS than max_mds
>             3 pool(s) have no replicas configured
>  
>   services:
>     mon: 3 daemons, quorum a,b,c (age 11m)
>     mgr: a(active, since 10m)
>     mds: 0/0 daemons up
>     osd: 1 osds: 1 up (since 9m), 1 in (since 11m)
>  
>   data:
>     volumes: 1/1 healthy
>     pools:   3 pools, 192 pgs
>     objects: 3 objects, 0 B
>     usage:   7.9 MiB used, 14 GiB / 14 GiB avail
>     pgs:     192 active+clean
>  
> sh-4.4#
> ```
> 
> ceph cluster is in error state. @travisn @subhamkrai anyone can help here?

looks similar to this issue https://github.com/rook/rook/issues/8745

2021-09-22 07:56 UTC, Madhu-1 commented
@leseb am frequently hitting the issue in the CI any idea what could be wrong?

JFYI same template changes work fine  in cephcsi https://github.com/ceph/ceph-csi/pull/2518 and CI is passed

2021-09-22 08:47 UTC, leseb commented
> @leseb am frequently hitting the issue in the CI any idea what could be wrong?
> 
> JFYI same template changes work fine in cephcsi [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518) and CI is passed

Looks like you just needed to rebase.

2021-09-22 11:01 UTC, Madhu-1 commented
> > @leseb am frequently hitting the issue in the CI any idea what could be wrong?
> > JFYI same template changes work fine in cephcsi [ceph/ceph-csi#2518](https://github.com/ceph/ceph-csi/pull/2518) and CI is passed
> 
> Looks like you just needed to rebase.

That helped Thank you.

2021-09-22 13:31 UTC, merged

2021-09-23 03:48 UTC, lhzw commented
Hi, there, when will this be merged to release-1.7? Thank you.

2021-09-23 17:41 UTC, travisn commented
> Hi, there, when will this be merged to release-1.7? Thank you.

Merged now, and will be included in v1.7.4 planned today