ceph: add ldap configs for rgw
rook/rook pull request #8750
Opened 2021-09-17 17:39 UTC by thotz

The Ceph Object Gateway supports integrating with LDAP for authenticating
and creating users, for that required config options need to be added in
cephobjectstore CRD.

Resolves #4315
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-09-17 21:07 UTC, BlaineEXE requested changes
Let's design more explicitly for usability and developer understanding.

Also, I will again ask where the unit tests are for this feature.

We will want community help testing this feature, and it would be most helpful if someone could help us set up an integration test for this so that we can be sure we aren't breaking it in the future.

2021-09-17 21:07 UTC, BlaineEXE commented on pkg/operator/ceph/object/config.go
> +	ldapDir                         = "/etc/ceph/ldap"
How about a different location for these files? Documents I found suggest `/etc/` is often used, which we also shouldn't use. I think `/etc/ldap` would be betters.

2021-09-17 21:07 UTC, BlaineEXE commented on cluster/examples/kubernetes/ceph/object-openshift.yaml
> +#   secret: PASSWORD_CHANGE_ME
If it's a password, we should just call it `password` for maximum clarity.

```suggestion
#   password: CHANGE_ME
```

2021-09-20 12:59 UTC, leseb requested changes
We also need unit tests for the spec generation, thanks!

2021-09-20 12:59 UTC, leseb commented on pkg/apis/ceph.rook.io/v1/types.go
> +	LDAP *LDAPSpec `json:"ldap,omitempty"`
I think this needs to be in a higher level Spec. LDAP and OPA for instance could fall under the same category. Perhaps something `'IdentityManagement`?

2021-09-20 12:59 UTC, leseb commented on pkg/apis/ceph.rook.io/v1/types.go
> +type LDAPSpec struct {
`LDAPSpec` needs a comment

2022-04-01 19:52 UTC, travisn commented
@thotz There are a number of old comments and questions on this PR, what is the status? According to the discussion in #4315, there is still interest in completing this work. Thanks!

2022-04-04 04:41 UTC, thotz commented
> @thotz There are a number of old comments and questions on this PR, what is the status? According to the discussion in #4315, there is still interest in completing this work. Thanks!

One of the ideas was from @leseb to merge this with [opa feature](https://github.com/rook/rook/pull/8731), I was not intended to test both features and it kinda blocked me from further development. I will refresh this PR by addressing existing commands

2022-09-22 20:56 UTC, cccsss01 commented
I am interested in this as well!

2022-11-07 20:56 UTC, travisn commented
Closing in favor of #11091

2022-11-07 20:56 UTC, closed without merging