ceph: pass region to newS3agent()
rook/rook pull request #8766
Opened 2021-09-21 07:41 UTC by thotz

**Description of your changes:**
If the region is specified in the storage class of OBC, use that in the
newS3agent() than using constant "us-east-1".

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-09-21 09:34 UTC, leseb approved these changes

2021-09-21 14:46 UTC, travisn requested changes

2021-09-23 09:17 UTC, thotz commented on pkg/operator/ceph/object/s3-handlers.go
> +		cephRegion = region
Sorry I was not able to find  a way to mock s3 client for this unit test

2021-09-23 09:49 UTC, leseb commented on pkg/operator/ceph/object/s3-handlers.go
> +		cephRegion = region
Can't we read the region out of `sess`?

2021-09-23 17:24 UTC, travisn commented on pkg/operator/ceph/object/s3-handlers.go
> +		cephRegion = region
Another approach could be a helper method to get the region, which would be unit tested. While this small of an issue isn't critical for unit testing, in general we really want to have the mindset of unit testing everything within reason. For now though let's get it into the release today.

2021-09-23 17:24 UTC, travisn approved these changes

2021-09-23 17:24 UTC, merged