ceph: auto-detect rgw pool prefix for external script
rook/rook pull request #8787
Opened 2021-09-22 10:31 UTC by leseb

**Description of your changes:**

When running the script, we will try to auto-detect the prefix of the
rgw pool and not default it anymore to "default".

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-09-22 13:53 UTC, leseb commented
@aruniiird can you please look at the unit test failure and recommend an approach? Thanks

2021-09-30 13:47 UTC, aruniiird requested changes
Before the change, we used to silently ignore `rgw_pool_prefix`, if there is no `rgw_endpoint` is provided and print the output (without `ceph-rgw` storageclass in the output). But with the new change, we are hitting the `Exception`  even for the default run.
Is this expected? or Should we keep the backward compatibility?

2021-09-30 13:47 UTC, aruniiird commented on cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
> +                return self._arg_parser.rgw_pool_prefix
Do we require `found` bool variable as we are returning immediately after finding the rgw-prefix?

2021-09-30 13:47 UTC, aruniiird commented on cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
> +                pool = pool['poolname']  # type: str
Is it ok to make a new variable name here (like `poolname`) ?

2021-11-08 17:11 UTC, leseb commented
`default` seems to be the default prefix so this might not be needed. Tools like Rook, Ceph-Ansible and cephadm create a default multisite config and thus we always have a prefix. Closing for now.

2021-11-08 17:11 UTC, closed without merging