docs: add node restart requirement for csi upgrade issue
rook/rook pull request #8915
Opened 2021-10-05 01:11 UTC by travisn

**Description of your changes:**
The cephfs csi volume plugin if restarted when host networking is not enabled will cause the volumes to hang. In Rook v1.6.0 - v1.6.4 host networking was not enabled by default, causing all cephfs volumes to hang during upgrade from those releases. A note is added to the upgrade guide [as requested](https://github.com/rook/rook/issues/8085#issuecomment-933440203) to help make this issue more visible.

**Which issue is resolved by this Pull Request:**
Related to: #8085 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-10-05 04:45 UTC, Rakshith-R requested changes
Looks good to me, just need to include RBD volumes too.

2021-10-05 04:45 UTC, Rakshith-R commented on Documentation/ceph-upgrade.md
> +**IMPORTANT** If you have CephFS volumes and are upgrading from Rook v1.6.0 - v1.6.4,
```suggestion
**IMPORTANT** If you have CephFS or RBD volumes and are upgrading from Rook v1.6.0 - v1.6.4,
```

Write hangs for RBD volumes, see https://github.com/rook/rook/issues/8085#issuecomment-858578417

2021-10-05 04:45 UTC, Rakshith-R commented on Documentation/ceph-upgrade.md
> +**IMPORTANT** If you have CephFS volumes and are upgrading from Rook v1.6.0 - v1.6.4,
```suggestion
**IMPORTANT** If you have CephFS or RBD volumes and are upgrading from Rook v1.6.0 - v1.6.4,
```

2021-10-06 07:15 UTC, Rakshith-R approved these changes

2021-10-06 09:06 UTC, leseb approved these changes

2021-10-06 09:07 UTC, merged