helm: Enable cephfs volume expansion by default
rook/rook pull request #9128
Opened 2021-11-08 18:42 UTC by travisn

**Description of your changes:**
The cluster helm chart missed adding the default setting for the volume expansion, so now we enable it by default.

**Which issue is resolved by this Pull Request:**
Resolves #9120 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-11-09 04:11 UTC, Rakshith-R requested changes
The `allowVolumeExpansion:` line in cephblocksystem also needs to be added to cephfilesystem.yaml
https://github.com/rook/rook/blob/0a3945db7ce01c422a8630554356a993bd805260/cluster/charts/rook-ceph-cluster/templates/cephblockpool.yaml#L23-L26

https://github.com/rook/rook/blob/0a3945db7ce01c422a8630554356a993bd805260/cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml#L24-L26

2021-11-09 14:38 UTC, Madhu-1 approved these changes

2021-11-10 06:43 UTC, Rakshith-R approved these changes
LGTM, thanks!

2021-11-10 14:02 UTC, leseb approved these changes

2021-11-10 14:02 UTC, merged