ceph: set default FsGroupChangePolicy value to 'None'
rook/rook pull request #9144
Opened 2021-11-11 10:20 UTC by humblec

The None value Indicates that volumes will be mounted
    with no modifications, as the CSI volume driver does not
    support these operations. While volumes are provisioned
    by the RBD CSI driver for filesystem/block mode PVCs
    we dont expect the Fsgroup policy or check from CO side
    to play a role here.
    
    The current default value ie ReadWriteOnceWithFSType cause
    volumes to be examined to determine if volume ownership and permissions
    should be modified to match the pod's security policy. Changes could occur
    if the fsType is defined and the persistent volume's accessModes contains
    ReadWriteOnce.
**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-11-11 13:09 UTC, humblec commented
Considering we have enough e2e tests here to make sure, everything is working as expected, this is ready for review.

Cc @travisn @leseb

2021-11-11 19:11 UTC, travisn commented
To be clear, does the ceph-csi driver not support `ReadWriteOnceWithFSType`? 

If the ceph-csi driver does support `ReadWriteOnceWithFSType`, shouldn't modifying the permissions according to the pod's security policy be the right default?

2021-11-15 08:01 UTC, humblec commented
> To be clear, does the ceph-csi driver not support `ReadWriteOnceWithFSType`?
> 
> If the ceph-csi driver does support `ReadWriteOnceWithFSType`, shouldn't modifying the permissions according to the pod's security policy be the right default?

The check is actually one layer above to ceph csi, also afaict, the fsgroup on the share is NOOP . However I can perform some more testing on this before we get this in.

2021-11-15 15:13 UTC, leseb approved these changes

2021-11-15 18:44 UTC, travisn commented
> > To be clear, does the ceph-csi driver not support `ReadWriteOnceWithFSType`?
> > If the ceph-csi driver does support `ReadWriteOnceWithFSType`, shouldn't modifying the permissions according to the pod's security policy be the right default?
> 
> The check is actually one layer above to ceph csi, also afaict, the fsgroup on the share is NOOP . However I can perform some more testing on this before we get this in.

I'm still not clear, why do we need to change the default? What is broken with the `ReadWriteOnceWithFSType` default? 

Instead of changing the default, what if we just add a sentence that describes when it's recommended to change the default? For example, does this impact mount times of large volumes?

2021-11-16 03:54 UTC, humblec commented
> > 
> > The check is actually one layer above to ceph csi, also afaict, the fsgroup on the share is NOOP . However I can perform some more testing on this before we get this in.
> 
> I'm still not clear, why do we need to change the default? What is broken with the `ReadWriteOnceWithFSType` default?

If we keep the default as `ReadWriteOnceWithFSTpe` and if its not giving any advantages rather only some disadvantages atleast in certain scenarios, we have to changes the default and that was the thought process behind this PR :)

> 
> Instead of changing the default, what if we just add a sentence that describes when it's recommended to change the default? For example, does this impact mount times of large volumes?

Yeah, we are seeing that, this default value delay the pod startup when there are many files in a volume. We are still waiting for the outcome after changing the value to `None`, additionally, I am also planning to carry some extra tests here. so , lets hold this PR till we have a feedback

2021-11-16 15:23 UTC, travisn requested changes
Holding while more testing is being completed.

2021-11-30 11:38 UTC, humblec commented
> > Instead of changing the default, what if we just add a sentence that describes when it's recommended to change the default? For example, does this impact mount times of large volumes?
> 
> Yeah, we are seeing that, this default value delay the pod startup when there are many files in a volume. We are still waiting for the outcome after changing the value to `None`, additionally, I am also planning to carry some extra tests here. so , lets hold this PR till we have a feedback

@travisn we have update from a couple of setups that, if we keep the policy as `none`, the pod startup is very fast and they dont face the issue. so thats indeed good.  :+1:  ,  The only disadvantage with keeping `none` as the default value is that, in case the root vol permission get changed, it wont be validated/corrected by kubelet.  Thinking about the outcome or result of skipping the permission correction from kubelet is that, in worst case the application will fail to access/use the volume properly. If thats the situation, I expect the pod container could fail to start or work properly.  Can we consider it as a good sign for the `admin` to enable or keep the change policy to `OnRootMismatch` in their setup ? wdyt? Based on that, we could pick this PR into or keep the existing defaults.

2021-11-30 16:57 UTC, travisn commented
> > > Instead of changing the default, what if we just add a sentence that describes when it's recommended to change the default? For example, does this impact mount times of large volumes?
> > 
> > 
> > Yeah, we are seeing that, this default value delay the pod startup when there are many files in a volume. We are still waiting for the outcome after changing the value to `None`, additionally, I am also planning to carry some extra tests here. so , lets hold this PR till we have a feedback
> 
> @travisn we have update from a couple of setups that, if we keep the policy as `none`, the pod startup is very fast and they dont face the issue. so thats indeed good. 👍 , The only disadvantage with keeping `none` as the default value is that, in case the root vol permission get changed, it wont be validated/corrected by kubelet. Thinking about the outcome or result of skipping the permission correction from kubelet is that, in worst case the application will fail to access/use the volume properly. If thats the situation, I expect the pod container could fail to start or work properly. Can we consider it as a good sign for the `admin` to enable or keep the change policy to `OnRootMismatch` in their setup ? wdyt? Based on that, we could pick this PR into or keep the existing defaults.

Is this understanding correct?
- With the current default `ReadWriteOnceWithFSType`, volumes with many files will be delayed at startup while permissions are set
- With the setting `none`, volumes with many files will be mounted quickly since permissions are not checked by the kubelet
- With the setting `none`, if permissions get changed unexpectedly, the app may not be able to access the volume and cause failures
- With the setting `OnRootMismatch`, the permissions will only be scanned if the root permissions are different than expected, so volumes should really only be updated when absolutely necessary. 

So your recommendation is to change the default to `OnRootMismatch`? That makes more sense to me than changing the default to `none` if my understanding is correct.

2021-12-01 08:27 UTC, leseb requested changes
I think changing to use `OnRootMismatch` makes more sense especially if FsGroup is used when mounting the volume.

2021-12-13 13:09 UTC, Madhu-1 commented on pkg/operator/ceph/csi/spec.go
> +		err = csiDriverobj.createCSIDriverInfo(r.opManagerContext, r.context.Clientset, CephFSDriverName, k8sutil.GetValue(r.opConfig.Parameters, "CSI_CEPHFS_FSGROUPPOLICY", string(k8scsi.NoneFSGroupPolicy
as part of https://github.com/rook/rook/pull/8459 we are supposed to change the fsgroupPolicy to None but looks like as an overlook the default value never changed, the PR only changed the logging, and yaml files are changed :facepalm: @humblec what's the plan for cephfs fsgroup policy change? are we tracking both cephfs and rbd changes in this PR?

2022-01-27 20:01 UTC, closed without merging