helm: allow further configurability of ingress version
rook/rook pull request #9237
Opened 2021-11-24 10:26 UTC by TomHellier

The ingress api version changed when it went to v1, and this has caused some upheaval
throughout the kubernetes ecosystem. This commit uses a common method of deciding which
ingress api to use, and allows the optional override of the kubernetes version
presented to helm using the helm build-in capabilities.
also add an ingress into the helm integration tests so any regressions to how ingresses
are handled in the future are caught easier.

Closes rook#9174

Signed-off-by: Tom Hellier <me@tomhellier.com>
(cherry picked from commit ba4460247710124d00d8768614f7dd2dcd8c8758)

**Which issue is resolved by this Pull Request:**
Resolves #9232

2021-11-24 14:33 UTC, TomHellier commented
@travisn I've just copied the helm code over, as even resolving the commits and trying to get the tests working wasn't proving very fruitful as the orchestration has changed so significantly.

2021-11-29 11:04 UTC, leseb commented
> Hi @TomHellier, this pull request was opened against a release branch, is it expected? Normally patches should go in the master branch first and then be backported to release branches.

It's alright.

2021-11-29 11:06 UTC, leseb requested changes
Please use `git cherry-pick -x ba4460247710124d00d8768614f7dd2dcd8c8758`, then fix the conflicts and repush. Thanks!

2021-11-29 12:23 UTC, TomHellier commented
@leseb  refixed conflicts

2021-11-29 13:25 UTC, leseb approved these changes

2021-11-29 13:25 UTC, merged