ceph: Add RBAC in helm chart for mgr to create service monitor
rook/rook pull request #9383
Opened 2021-12-10 14:32 UTC by sathieu

**Description of your changes:**

Same as #8118, for Helm chart.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-12-10 15:09 UTC, sathieu commented
My understanding was wrong.

I had to set `monitoring.enabled` to `true` to make this work.

Sorry for the noise...

2021-12-10 17:16 UTC, BlaineEXE commented
Thank you @sathieu for contributing this. We removed recently this bit of code in the operator helm chart because we don't want to strongly tie installation of Rook to Prometheus. 

In our example manifests, we have `deploy/examples/monitoring/rbac.yaml` which deploys the RBAC needed for Prometheus monitoring for users who manually install, and we have the same optional-ness for users of the `rook-ceph-cluster` Helm chart, which can optionally deploy the monitoring RBAC.

Given that not all users are using the `rook-ceph-cluster` chart, I have proposed a different solution that will optionally install the required helm resources in the `rook-ceph` chart. See here: https://github.com/rook/rook/pull/9388

@sathieu would you care to test that new PR's changes to make sure your workflow is working with it?

2021-12-10 17:16 UTC, BlaineEXE requested changes
Requesting changes while we evaluate a different solution.

2021-12-10 17:33 UTC, sathieu commented
I still have another error:

```
2021-12-10 17:31:23.559425 E | op-mgr: failed to deploy prometheus rule. prometheus rule could not be deployed: failed to create prometheusRules. prometheusrules.monitoring.coreos.com is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot create resource "prometheusrules" in API group "
```

2021-12-10 19:55 UTC, BlaineEXE commented on deploy/charts/rook-ceph/values.yaml
> +
Monitoring should not be enabled for all users by default. For our releases that go out to hundreds of users, we'd like this to be false by default, and for those who want monitoring, they enable it via `monitoring.enabled`.

2021-12-10 21:28 UTC, BlaineEXE requested changes
Also, please change the subject to `helm: ...` for our feature tracking. `ceph: ...` is a bit too generic.

2021-12-16 16:55 UTC, BlaineEXE commented
Closing now that https://github.com/rook/rook/pull/9388 is merged.

2021-12-16 16:55 UTC, closed without merging