core: support priority class for crashcollector
rook/rook pull request #9502
Opened 2021-12-28 03:19 UTC by satoru-takeuchi

**Description of your changes:**

Support priorityClass to crashcollectos as mons, mgrs, and osds.

https://rook.io/docs/rook/v1.8/ceph-cluster-crd.html#priority-class-names-configuration-settings

The main use case is applying the high priority to crashcollectors to preempt normal pods under heavy load. Without this feature, we might lose crash information.

Closes: https://github.com/rook/rook/issues/9500

Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #9500

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [x] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2022-01-03 11:27 UTC, leseb requested changes
nit

2022-01-03 11:27 UTC, leseb commented on Documentation/ceph-cluster-crd.md
> +* `all`: Set priority class names for MGRs, Mons, OSDs, and crashcollectos.
```suggestion
* `all`: Set priority class names for MGRs, Mons, OSDs, and crashcollectors.
```

2022-01-04 08:31 UTC, leseb reviewed
Please squash the commits and we should be good to go, thanks!

2022-01-04 13:21 UTC, leseb approved these changes

2022-01-04 17:53 UTC, BlaineEXE reviewed
Do we currently test the priority classes in integration tests? If not, should we do so in one of the canary tests?

2022-01-05 10:37 UTC, satoru-takeuchi commented
@BlaineEXE 

> Do we currently test the priority classes in integration tests? If not, should we do so in one of the canary tests?

Not in canary tests but in unit tests. For example, MON, OSD, and MGR have unit tests that confirm whether priorityClass is really reflected in the new podSpec. For example, here is the mon's test.

https://github.com/rook/rook/blob/51d569eecc52421cf58791f4e2d55491eb2304f2/pkg/operator/ceph/cluster/mon/spec_test.go#L43

How about adding this kind of unit test about crashcollector?

2022-01-11 23:39 UTC, BlaineEXE commented
> @BlaineEXE
> 
> > Do we currently test the priority classes in integration tests? If not, should we do so in one of the canary tests?
> 
> Not in canary tests but in unit tests. For example, MON, OSD, and MGR have unit tests that confirm whether priorityClass is really reflected in the new podSpec. For example, here is the mon's test.
> 
> https://github.com/rook/rook/blob/51d569eecc52421cf58791f4e2d55491eb2304f2/pkg/operator/ceph/cluster/mon/spec_test.go#L43
> 
> How about adding this kind of unit test about crashcollector?

Sounds like a good idea. Thanks

2022-01-18 21:16 UTC, travisn commented
> > @BlaineEXE
> > > Do we currently test the priority classes in integration tests? If not, should we do so in one of the canary tests?
> > 
> > 
> > Not in canary tests but in unit tests. For example, MON, OSD, and MGR have unit tests that confirm whether priorityClass is really reflected in the new podSpec. For example, here is the mon's test.
> > https://github.com/rook/rook/blob/51d569eecc52421cf58791f4e2d55491eb2304f2/pkg/operator/ceph/cluster/mon/spec_test.go#L43
> > 
> > How about adding this kind of unit test about crashcollector?
> 
> Sounds like a good idea. Thanks

@satoru-takeuchi It will be great to get this in soon, how is the test looking?

2022-01-18 21:51 UTC, satoru-takeuchi commented
@travisn Sorry for late reply. I'd caught bad cold. I'm going to updating this PR today.

2022-01-18 22:12 UTC, travisn commented
> @travisn Sorry for late reply. I'd caught bad cold. I'm going to updating this PR today.

Ok thanks, glad to hear you are feeling better!

2022-01-19 17:38 UTC, merged