osd: allow for injecting extra environment variables.
rook/rook pull request #9516
Opened 2022-01-04 13:17 UTC by rzarzynski

This patch is both stripped down (no support for extra argvs) and extended (envs at both prepare and main stages) version
of the Travis Nielsen's patch [1] to accommodate crimson-osd in Rook. Also, the naming convention isn't crimson-specific anymore as the mechanism could be useful with the classical OSD as well (e.g. tuning TCMalloc or even the dynamic linker).

The need for the patch comes from the fact that, although crimson finally exposes the same CLI interface as the classical
OSD, the broadly used development builds have ASan built in. As ASan, by default, complains if it isn't the very first loaded
DSO, we need to set the `ASAN_OPTIONS` environment variable to `verify_asan_link_order=0` to mitigate the early aborts.

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

[1]: https://github.com/rook/rook/pull/8763

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2022-01-04 13:30 UTC, rzarzynski commented
When testing locally I saw a failure that **seems** unrelated:

```
$ make test
...
022-01-04 13:20:56.848289 I | sys: Output:
--- PASS: TestGetPartitions (0.00s)
=== RUN   TestParseUdevInfo
--- PASS: TestParseUdevInfo (0.00s)
=== RUN   TestListDevicesChildListDevicesChild
2022-01-04 13:20:56.848347 I | sys: command lsblk
--- PASS: TestListDevicesChildListDevicesChild (0.00s)
=== RUN   TestGrep
--- PASS: TestGrep (0.00s)
PASS
coverage: 34.4% of statements
ok      github.com/rook/rook/pkg/util/sys       (cached)        coverage: 34.4% of statements
?       github.com/rook/rook/pkg/version        [no test files]
FAIL
make[1]: *** [build/makelib/golang.mk:135: go.test.unit] Error 2
```

2022-01-04 13:41 UTC, leseb requested changes
Overall I'm not sure if using the operator config is the right approach since this will affect all the clusters deployed by the operator. Can't we detect that the OSD is a crimson OSD and then append the needed env variable? Just like we append `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES`?

2022-01-04 13:41 UTC, leseb commented on pkg/operator/ceph/cluster/osd/spec.go
> +	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(context.TODO(), c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
```suggestion
	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(c.clusterInfo.Context, c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
```

No need for a new context.

2022-01-04 13:41 UTC, leseb commented on pkg/operator/ceph/cluster/osd/provision_spec.go
> +	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(context.TODO(), c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
```suggestion
	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(c.clusterInfo.Context, c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
```

2022-01-04 13:41 UTC, leseb commented on pkg/operator/ceph/cluster/osd/provision_spec.go
> +	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(context.TODO(), c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
Why does the prepare job need this? I thought the args were needed only to start the OSD process.

2022-01-04 13:41 UTC, leseb commented on pkg/operator/ceph/cluster/osd/spec.go
> +	// Inject extra envrinoment variables.
```suggestion
	// Inject extra environment variables.
```

2022-01-04 13:44 UTC, rzarzynski commented on pkg/operator/ceph/cluster/osd/spec.go
> +	// Inject extra envrinoment variables.
Oops, thanks for pointing this out.

2022-01-04 13:45 UTC, leseb commented on pkg/operator/ceph/cluster/osd/provision_spec.go
> +	if extraEnvVarsValue, err := k8sutil.GetOperatorSetting(context.TODO(), c.context.Clientset, controller.OperatorSettingConfigMapName, "OSD_EXTRA_ENV_VARS", ""); err != nil {
Correct, so the `--mkfs` also needs this? If so, let's add a small comment in the code why the prepare stage needs it too :)

2022-01-04 13:57 UTC, rzarzynski commented
> Overall I'm not sure if using the operator config is the right approach since this will affect all the clusters deployed by the operator. Can't we detect that the OSD is a crimson OSD and then append the needed env variable? Just like we append `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES`?

Thanks for the review!

I think it's beneficial the have the flexibility the manual approach brings (also for crimson-unrelated poking during development). Additionally, the auto-detection would be rather complex as it needs to not only differentiate between the classical OSD and crimson but also between crimson-dev and crimson-release builds. The target audience of this feature are mostly developers.

2022-01-04 14:30 UTC, leseb commented
> > Overall I'm not sure if using the operator config is the right approach since this will affect all the clusters deployed by the operator. Can't we detect that the OSD is a crimson OSD and then append the needed env variable? Just like we append `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES`?
> 
> Thanks for the review!
> 
> I think it's beneficial the have the flexibility the manual approach brings (also for crimson-unrelated poking during development). Additionally, the auto-detection would be rather complex as it needs to not only differentiate between the classical OSD and crimson but also between crimson-dev and crimson-release builds. The target audience of this feature are mostly developers.

Understood

> > Overall I'm not sure if using the operator config is the right approach since this will affect all the clusters deployed by the operator. Can't we detect that the OSD is a crimson OSD and then append the needed env variable? Just like we append `TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES`?
> 
> Thanks for the review!
> 
> I think it's beneficial the have the flexibility the manual approach brings (also for crimson-unrelated poking during development). Additionally, the auto-detection would be rather complex as it needs to not only differentiate between the classical OSD and crimson but also between crimson-dev and crimson-release builds. The target audience of this feature are mostly developers.

If it's a dev flow only, how about we go with the following approach:

* On every container definition use `EnvFrom`
* Where `EnvFrom` points to a CM using `ConfigMapRef` with a `Name` and mark `Optional: true` in case the CM does not exist

We can call this configmap `rook-ceph-daemon-env-override`?
What do you think?

2022-01-04 15:01 UTC, rzarzynski commented
After the very first reading the idea looks promising! I will be experimenting with it to see whether this could a matter of just a dedicated file for crimson in the `examples` directory.

2022-02-03 22:00 UTC, rzarzynski commented
Closing as #9647 got merged.

2022-02-03 22:00 UTC, closed without merging