operator: Document that the `rook-ceph-operator-config` ConfigMap is …
rook/rook pull request #9821
Opened 2022-03-02 08:58 UTC by matthiasr

**Description of your changes:**

We discovered the hard way that configuration through the environment
does not work if this ConfigMap is not present altogether. Document this
in all the places someone might look for hints.

**Which issue is resolved by this Pull Request:**

Closes #9806.

cc @travisn

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2022-03-02 08:59 UTC, matthiasr commented
Side note: the link for the two "skip tests" check boxes does not contain any information about skipping tests.

2022-03-02 18:35 UTC, BlaineEXE approved these changes

2022-03-02 18:52 UTC, travisn requested changes
Thanks for the doc update! just a couple minor suggestions...

2022-03-02 18:52 UTC, travisn commented on Documentation/ceph-advanced-configuration.md
> +## Configuration using environment variables
This doc is intended for advanced configurations, and adding it to the common issues doc seems sufficient. How about if we revert the changes in this doc?

2022-03-02 18:52 UTC, travisn commented on Documentation/ceph-common-issues.md
> +## Configuration from the environment is ignored
```suggestion
## Operator environment variables are ignored
```

2022-03-02 19:03 UTC, travisn commented
> Side note: the link for the two "skip tests" check boxes does not contain any information about skipping tests.

Good catch, it shows how often that text is actually read. #9823

2022-03-03 08:41 UTC, matthiasr commented on Documentation/ceph-common-issues.md
> +* [Configuration from the environment is ignored](#configuration-from-the-environment-is-ignored)
```suggestion
* [Operator environment variables are ignored](#operator-environment-variables-are-ignored)
```

2022-03-03 14:37 UTC, travisn approved these changes

2022-03-03 14:43 UTC, merged