Fix rook-ceph-cluster helm chart for cephobjectstore storageclass without/empty parameters
rook/rook pull request #9854
Opened 2022-03-08 13:13 UTC by Zempashi

Fix rook-ceph-cluster helm chart with passing no parameter on CephObjectStore storageclass

Before pull-request:
```
cephObjectStores:
  - name: ceph-objectstore
    [...]
    storageClass:
      parameters: {}
```
gives
```
$ helm template . -f values.yaml --debug
Error: YAML parse error on rook-ceph-cluster/templates/cephobjectstore.yaml: error converting YAML to JSON: yaml: line 9: did not find expected key
[...]                                                               
---                                     
apiVersion: storage.k8s.io/v1           
kind: StorageClass                      
metadata:                               
  name: s3                              
provisioner: default.ceph.rook.io/bucket
reclaimPolicy: Delete                   
parameters:                             
  objectStoreName: ceph-objectstore     
  objectStoreNamespace: default         
  {}                                    
```
And
```
cephObjectStores:
  - name: ceph-objectstore
    [...]
    storageClass:
      parameters:
```
gives 
```
Error: YAML parse error on rook-ceph-cluster/templates/cephobjectstore.yaml: error converting YAML to JSON: yaml: line 11: could not find expected ':'                                                            
---                                      
apiVersion: storage.k8s.io/v1            
kind: StorageClass                       
metadata:                                
  name: s3                               
provisioner: default.ceph.rook.io/bucket 
reclaimPolicy: Delete                    
parameters:                              
  objectStoreName: ceph-objectstore      
  objectStoreNamespace: default          
  null                                   
```

After the PR this is fixed (and obviously supports putting parameters)

Note: this was not really evident for me that `region: us-east-1` is the "magic" default value to use if not using Zone/ZoneGroup, may be we could a comment the default values

2022-03-08 14:12 UTC, Zempashi commented
I've spotted other place where this problem might occur (but with less chance, because it requires parameters to work correctly):
- https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml#L22
- https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml#L23

I can also change those if you wish to.

2022-03-08 18:08 UTC, travisn requested changes
For the commit message:
- Please add a sentence or two describing the change in the commit message. Nothing fancy, but you can see the commit history for examples.
- There is a typo in cephojbectstore

> I've spotted other place where this problem might occur (but with less chance, because it requires parameters to work correctly):
> 
> * https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml#L22
> * https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml#L23
> 
> I can also change those if you wish to.

Yes, sounds great if you could update those as well, thanks!

2022-03-08 20:49 UTC, travisn reviewed
In the commit message, did you mean this?
"Test **existence** of parameters to avoid printing artifacts that break yaml"

2022-03-09 00:04 UTC, travisn commented
> Inspired by https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#testing-truthiness
> 
> Meaning a "true" value, something different from empy sequence, map, string.
> 
> Quote from https://pkg.go.dev/text/template: "If the value of the pipeline is empty, no output is generated;" "Test emptiness" ?

Got it, I learned a new word!

2022-03-09 00:04 UTC, travisn approved these changes

2022-03-09 00:04 UTC, merged