core: add `Phase` in `additionalPrinterColumns` for all CRs
rook/rook pull request #9910
Opened 2022-03-15 06:16 UTC by subhamkrai

**Description of your changes:**
this commit adding `Phase` in `additionalPrinterColumns` for
all the CRs.

this is how it looks now, example:

```
$ kc get cephfilesystem
NAME   ACTIVEMDS   AGE     PHASE
myfs   1           4m57s   Ready

srai@ ~
$ kc get cephblockpool
NAME                    PHASE
device-health-metrics   Ready
replicapool             Progressing

srai@ ~
$ kc get cephclient
NAME     PHASE
cinder   Ready
glance   Ready
```

Closes: https://github.com/rook/rook/issues/9883
Signed-off-by: subhamkrai <srai@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #9883 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-03-16 19:10 UTC, BlaineEXE commented on pkg/apis/ceph.rook.io/v1/types.go
> +// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`,description="Phase"
Why was this conversation marked resolved? Is there a reason this description must be left here?

2022-03-16 19:15 UTC, travisn commented on pkg/apis/ceph.rook.io/v1/types.go
> +// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`,description="Phase"
oh I thought it was removed like the one up on line 41, guess it's still there...

2022-03-17 09:40 UTC, leseb requested changes
https://github.com/rook/rook/pull/9910/files#r827005109 needs to be addressed

2022-03-21 05:47 UTC, subhamkrai commented on pkg/apis/ceph.rook.io/v1/types.go
> +// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`,description="Phase"
ahh, I removed it in another place but forgot to remove it from here. Updated now.

2022-03-21 08:19 UTC, leseb approved these changes

2022-03-21 13:14 UTC, travisn approved these changes

2022-03-21 13:15 UTC, merged