docs: update the s3 client example for accesing RGW
rook/rook pull request #9968
Opened 2022-04-01 14:46 UTC by thotz

**Description of your changes:**
Couple of modification to existing example for s3 client regarding how
to access the ceph object store. Added details to fetch the
`BUCKET_NAME`, updated the `AWS_ENDPOINT` and `AWS_HOST` details.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-04-04 08:07 UTC, leseb approved these changes

2022-04-04 14:05 UTC, travisn requested changes

2022-04-04 14:05 UTC, travisn commented on Documentation/ceph-object.md
> +s5cmd --endpoint-url http://$AWS_HOST:$PORT cp s3://$BUCKET_NAME /tmp/rookObj-download
need to keep the test obj name in the url, right?
```suggestion
s5cmd --endpoint-url http://$AWS_HOST:$PORT cp s3://$BUCKET_NAME/rookObj /tmp/rookObj-download
```

2022-04-05 13:58 UTC, travisn approved these changes

2022-04-05 13:58 UTC, merged